### ISSUE TITLE
Show label with HUSD equivalent in profile (S)

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#1009]
Reproduce:
1. Go to https://dho.hypha.earth/hypha/proposals/
2. Check Contribution "First Contribution of the new Hypha DAO"
3. See Label "1.00 HUSD"
4. Go to Profile https://dho.hypha.earth/hypha/@leonieherma1
5. Check Contribution card and see Label "0"
6. Open https://dho.hypha.earth/hypha/proposals/30013 and check if label "1.00USD" is there

Expected behaviour:
I expected to also see the 1.00HUSD Label on the card in the profile and see the label in the project detail page.

Experienced behaviour:
The label in the profile says 0 (not 1.00HUSD) and it is missing in the project detail page

To Do:

- [x] Add label to project detail page https://dho.hypha.earth/hypha/proposals/30013
- [x] Show correct amount in profile preview widget (1.00 HUSD)
- [x] If you can reduce the decimals to 0, so show 1HUSD instead of 1.00 HUSD

<img width="901" alt="image" src="https://user-images.githubusercontent.com/75991832/164535376-3a5c53d9-bee2-4de2-9004-ced2a2611155.png">

**Comment by jmgayosso** [comment]
@leonieherma1 now this is on dev could you test please?

**Comment by leonieherma1** [comment]
@jmgayosso @DaniPoot I just did a test contribution with the following token:

https://dao-dev.hypha.earth/hypha/proposals/30375

<img width="960" alt="image" src="https://user-images.githubusercontent.com/75991832/166991071-b0113004-826d-42bd-9cea-6ad45218a0db.png">

But the label shows 200 HUSD 

<img width="164" alt="image" src="https://user-images.githubusercontent.com/75991832/166991296-f26d5ff5-14fa-4318-82ef-743e65299f68.png">


so that is wrong - the label should show 100. 

We have 100 Hypha toke (a 50 cents) so that is 50 USD + 50 HUSD = 100 USD

Please change the label to: 

- [ ] value (= hypha token value + HUSD value) 
- [ ] change HUSD to USD
- [ ] don't show decimals if they are 0 (e.g. 100 USD - not 100.00 USD) if possible don'T show decimals at all (just round the number or don't show it)
- [ ] Add a tooltip that shows all token on hover:
- 100 HYPHA - 50 Cash - 100 Voice

Let me know if you have questions about this.
