### ISSUE TITLE
Filter Search Page not working

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#1010]
Reproduce:
1. Go to https://dho.hypha.earth/hypha/proposals/ and check that the contribution "First Contribution of the new Hypha DAO
" shows up
2. Then go to search and search for "DAO" with the filter dropdown "Voting"

Expected behaviour: 
The contribution shows up in the search results

Experienced behaviour:
The contribution doesnt show up in the search results 

<img width="1304" alt="image" src="https://user-images.githubusercontent.com/75991832/164536664-ce863699-2ce8-430c-9c7b-af98434d44f8.png">

**Comment by jmgayosso** [comment]
@leonieherma1 ready to test
