### ISSUE TITLE
Sidebar Glitching (M)

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#1015]
Steps:
Load site on brave browser, log in

Expected result:
See full width sidebar on wide browser window

Actual result:
Side bar is glitching on all wider window settings, resizing the window too. 

Browser: Brave on OS X
Version: [Version 1.37.116 Chromium: 100.0.4896.127 (Official Build) (arm64)](https://brave.com/latest/)

As a DHO user i would like to see the sidebar without glitching:

https://user-images.githubusercontent.com/75991832/164577454-cc415a92-9374-41d5-abdf-3d28477534b4.mov

**Comment by n13** [comment]
Same thing resizing the window, so it's not about one specific width that is causing the problem


https://user-images.githubusercontent.com/65412/164585220-827b4633-7bd9-4d72-952d-a13cce9233f6.mov

**Comment by n13** [comment]
<img width="548" alt="image" src="https://user-images.githubusercontent.com/65412/164585489-f23afdb5-d1c5-4bd2-ba93-df5e8508098a.png">
