### ISSUE TITLE
Members joined date incorrect (S)

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#1017]
Reproduce:
1. Go to https://dho.hypha.earth/hypha/
2. Check "New Members" joined date

Expected behaviour:
I want to see the date the user joined and the user avatar should be clickable

Experienced behaviour:
I see 14.01.2021 for all users and user avatar is not clickable

Note: on the Members page all members have 14.02.2021 as joined date:

<img width="948" alt="image" src="https://user-images.githubusercontent.com/75991832/164581536-f376959b-b7c3-4ea7-8812-5d5e2830bce8.png">
 
<img width="312" alt="image" src="https://user-images.githubusercontent.com/75991832/164581316-cbb03d1f-ea0a-4545-94ad-1b66eb24821f.png">

**Comment by jmgayosso** [comment]
@leonieherma1 now is on dev, can you test please?
