### ISSUE TITLE
Show Hypha Logo in sidebar navigation (S)

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#1020]
Reproduce:
1. Go to https://dho.hypha.earth/hypha/
2. Check Logo in the sidebar

Expected behavior:
Show the Hpyha Logo

Experienced Behaviour: 
Blue circle with hy

<img width="225" alt="image" src="https://user-images.githubusercontent.com/75991832/164709125-ca2de0aa-e683-467a-bb37-f6cde20fc6f5.png">

**Comment by jmgayosso** [comment]
@leonieherma1 now is on dev, let us know any comment please
