### ISSUE TITLE
Hide "SEEDS" in Issuance Widget [S]

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#1050]
**Summary**
As a DAO user I don't want to see the SEEDS issuance because it is confusing.

**AC**
- [x] Remove SEEDS number 
- [x] Add "see more" link. to /treasury
- [x] Add HOVICE to https://dho.hypha.earth/hypha/treasury (to be consistent)

**Place**
- [x] https://dho.hypha.earth/hypha/organization
- [x] https://dho.hypha.earth/hypha/treasury
<img width="236" alt="image" src="https://user-images.githubusercontent.com/75991832/165626819-b9a14a2b-8e77-4c60-9150-c36e195ed29b.png">
<img width="1370" alt="image" src="https://user-images.githubusercontent.com/75991832/165626877-0bcbd47a-ce6c-4473-91b2-89370fcefb02.png">

**Comment by jmgayosso** [comment]
@leonieherma1 ready to test

**Comment by leonieherma1** [comment]
@josejulio I can still see SEEDS here:

<img width="300" alt="image" src="https://user-images.githubusercontent.com/75991832/166554916-05120386-15c9-4406-8f81-ae6142379a98.png">

https://dao-dev.hypha.earth/hypha/organization

**Comment by leonieherma1** [comment]
@jmgayosso @DaniPoot can't test treasury because it is not loading on dev for me:

https://dao-dev.hypha.earth/hypha/treasury
