### ISSUE TITLE
Badge shows wrong Token Icons

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#1055]
Reproduce:
1. Go to https://dho.hypha.earth/hypha/organization/assets/badge/6164
2. Check Icons for Token

Expected behaviour:
All Tokens have different Icons

<img width="671" alt="image" src="https://user-images.githubusercontent.com/75991832/165978708-7004c645-99c4-4f33-8756-cd9c8d381f41.png">

Experienced behaviour:
I see the HUSD icon for all Tokens

<img width="932" alt="image" src="https://user-images.githubusercontent.com/75991832/165978586-42fe3ef9-3729-44b0-8b91-81eb0bd85c19.png">

**Comment by SorinStoica4** [comment]
Same situation for Generic Contribution 
![icons](https://user-images.githubusercontent.com/77914753/166094135-dc027f5d-6d89-486f-83db-578b6e2f434f.png)

**Comment by leonieherma1** [comment]
@pugakn @arsenijesavic the V doesnt really look like it is in the center right?

<img width="47" alt="image" src="https://user-images.githubusercontent.com/75991832/167711133-b762f235-5f35-42e4-b05b-cc55c548e5cd.png">

https://dao-dev.hypha.earth/hypha/proposals/30375
