### ISSUE TITLE
Homepage new Members Widget shows old members [S]

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#1061]
Reproduce:
1. Go to https://dho.hypha.earth/hypha/
2. Check the "New Members Widget"
3. All dates show 21.04.2021

Expected behaviour:
See the latest members (on the /members page I see the latest members joined in April 2022)

<img width="969" alt="image" src="https://user-images.githubusercontent.com/75991832/166126111-11dae830-fd96-4699-b763-ce6c7c911323.png">

Experienced behaviour:
I see members that joined 21.04.2021 (probably sorted alphabetically)

<img width="327" alt="image" src="https://user-images.githubusercontent.com/75991832/166126035-673d6205-c4e0-44e7-ac80-3a91b6278790.png">

**Comment by jmgayosso** [comment]
@leonieherma1 ready to test
