### ISSUE TITLE
Proposal Creation Wizard: Role Assignment Overview Screen missing Date, Duration, Deferral & Commitment (S)

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#1073]
Reproduce:
1.- Try to create a Generic contribution and go all the way to the Review step
2.- go out of the process without publishing
3.- Return to proposal creation and try to create a role assignemnt proposal

Expected behaviour:
<img width="982" alt="image" src="https://user-images.githubusercontent.com/75991832/166319159-a8bc0628-7029-4aec-b1ae-2995e4394a2a.png">

Experienced behaviour:

<img width="971" alt="image" src="https://user-images.githubusercontent.com/75991832/166319135-a4084182-45df-4402-9813-a9c7cefc3e8a.png">

**Comment by leonieherma1** [comment]
@arsenijesavic now we have a new bug where the start date is missing, see:

https://dao.hypha.earth/hypha/proposals/30777
https://dao.hypha.earth/hypha/proposals/30919

<img width="954" alt="image" src="https://user-images.githubusercontent.com/75991832/167673906-d73c2f62-b38c-44bf-8b91-e5e622776b1d.png">


Are all those bugs connected? Should we schedule a frontend dev call later or tomorrow with @jmgayosso and @pugakn  and try to figure this out? There seem to be many related bugs here

**Comment by arsenijesavic** [comment]
Yes, it is!

**Comment by jmgayosso** [comment]
@arsenijesavic can you test please?
