### ISSUE TITLE
Proposal: Title shows double, Role Archetype not showing

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#1080]
Reproduce:
1. Go to: https://dho.hypha.earth/hypha/proposals/30621
2. Check the Title "Strategic Anchor Role: Strategic Anchor Role"

Experienced behaviour:
Title shows up twice and Role Archetype "Catalysing and Connecting B7" is missing (Maybe because it was an extension of a n old document?)

Expected behaviour:
Title only shows up once and the Role Archetype "Catalysing and Connecting B7" shows up in the proposal detail page (it shows up on the preview card)

<img width="882" alt="image" src="https://user-images.githubusercontent.com/75991832/166482684-45da00bd-8ce3-4d44-bed5-7f3fb3149ebe.png">

**Comment by DaniPoot** [comment]
Hi @leonieherma1 , this proposal has the type 'Edit'. In these cases, we have the functionality to add the title and the origin title at only one. is it correct? or only show the default title. @jmgayosso

**Comment by leonieherma1** [comment]
@DaniPoot what is the proposal type "edit"? Where does the "title" and where does the "origin title" come from?

**Comment by DaniPoot** [comment]
@leonieherma1 We don't knowledge about this type. In the code exist validations for this type but we can't create this type. In this proposal exist a field `original` with more information. I can show the proposal like the assignment

**Comment by jmgayosso** [comment]
> @DaniPoot what is the proposal type "edit"? Where does the "title" and where does the "origin title" come from?

@Gerard097 do you know about it???

**Comment by leonieherma1** [comment]
@DaniPoot @jmgayosso @Gerard097 I know what it is now. In the old UI you could "edit" your active assingment and then repropose. So the difference is, extend only works when the periods are over. But I can "edit" the assignment anytime, and then have all the fields prefilled (e.g. just change my comitment or the title) and then propose so it can be voted on. We don't have that in the new UI. I will make a story to add it.

**Comment by jmgayosso** [comment]
> @DaniPoot @jmgayosso @Gerard097 I know what it is now. In the old UI you could "edit" your active assingment and then repropose. So the difference is, extend only works when the periods are over. But I can "edit" the assignment anytime, and then have all the fields prefilled (e.g. just change my comitment or the title) and then propose so it can be voted on. We don't have that in the new UI. I will make a story to add it.

So we can close this ticket???

**Comment by leonieherma1** [comment]
@DaniPoot @jmgayosso no it still doesnt show the role archetype. Edited assignments should also show it
