### ISSUE TITLE
Proposal List Filter: Badge Type missing

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#1082]
Reproduce:
1. Go to https://dho.hypha.earth/hypha/proposals/
2. Check the filter and try to filter for "Badge Assignment"

Expected behaviour:
I can filter by Badge Assignments

Experienced behaviour:
I can't see the filter for Badge Assignment

<img width="290" alt="image" src="https://user-images.githubusercontent.com/75991832/166485222-23afb634-452f-492f-8571-7624b2c0b292.png">

**Comment by jmgayosso** [comment]
@DaniPoot Could you implement the behaivor too for staging proposals?
