### ISSUE TITLE
Badge Proposal became "Generic Contribution"

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#1083]
Reproduce:
1. User Sorin @gradinagruiu went to his profile: https://dho.hypha.earth/hypha/@gradinagruiu
2. Clicked on the badge "Moderator" https://dho.hypha.earth/hypha/organization/assets/badge/6164
3. Clicked "Apply"
4. Went through the process of creation a badge assignment
<img width="992" alt="image" src="https://user-images.githubusercontent.com/75991832/166504798-3fa97541-9a62-4d24-9c2f-4bf9ba241e5b.png">

5. He. then clicked "publish"
<img width="1048" alt="image" src="https://user-images.githubusercontent.com/75991832/166505130-3077ca90-6854-4795-b743-48b834794957.png">

https://dho.hypha.earth/hypha/proposals/30619

Expected behaviour:

- [ ] Label says "Badge Assignment" 
- [ ] Proposal shows up in the "assignment column" in the profile
- [ ] Proposal list: proposal shows up when I filter for "badge assignment" (filter currently missing)

Experienced behavior:
Badge shows up as "generic contributon"

<img width="581" alt="image" src="https://user-images.githubusercontent.com/75991832/166505297-9fd43a04-1e4a-4f6c-8ba1-091690effb85.png">

**Comment by jmgayosso** [comment]
Hi @arsenijesavic could you get dev branch and test again, @DaniPoot fixed this, the keep alive component was generating the issue, @DaniPoot could you explain what was the problem?

**Comment by arsenijesavic** [comment]
@jmgayosso this is also closing https://github.com/hypha-dao/dho-web-client/issues/1073 ?

**Comment by jmgayosso** [comment]
> #1073

I think you should get dev changes and test, could you take a look please?

**Comment by jmgayosso** [comment]
@leonieherma1 this works for you? could you test please?
