### ISSUE TITLE
 Badge Tokens & Multiplier not correct [S]

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#1086]
Reproduce:
1. Go to https://dho.hypha.earth/hypha/organization/assets/badge/6161
2. Check Multiplier:
<img width="939" alt="image" src="https://user-images.githubusercontent.com/75991832/166525674-cf1ecf49-d1f7-45b1-b562-593d9696fdfc.png">
3. Click "apply"
4. Go through the process and check the step "compensation"
<img width="1260" alt="image" src="https://user-images.githubusercontent.com/75991832/166525835-da1fda5d-a6ae-486f-bf00-e42be3abdfbf.png">
5. Click next and check overview:
<img width="978" alt="image" src="https://user-images.githubusercontent.com/75991832/166525899-bcb95405-1167-4069-860c-0dacbb981ef9.png">

Expected behaviour: Check numbers, token names , tooltips and token images
- [x] Utility Token (HYPHA) Multiplier: x 1.03%
- [x] Cash Token Multiplier: x 1%
- [x] Voice Token Multiplier: x 1.01%

Experienced behaviour:
- [x] Cash Coefficient (HUSD) _Empty, wrong tooltip, wrong image_
- [x] Utility Coefficient (HYPHA) _x 3%, wrong tooltip_
- [x] Voice Coefficient (HVOICE) _x 1%, wrong tooltip_

**Comment by jmgayosso** [comment]
@DaniPoot please replace the token component to show correctly the coefficients for badge assignments
