### ISSUE TITLE
Add supporting documentation link to contribution

### ISSUE THREAD

**Issue by sceenius** [hypha-dao/dho-web-client#11]
Contributions do not show the link in read mode, See Clare - Brand Strategy & Activation (including hours and tangibles). Urgent, because there's a week left to approve her contribution and it does not fit in the descr field. 

![image](https://user-images.githubusercontent.com/24725582/89685884-39542d00-d8cb-11ea-853d-0da54fede828.png)

**Comment by sceenius** [comment]
Can you add the drop shadow to the member profile cards?

**Comment by gregory-latinier** [comment]
What does a drop shadow has to do with this current issue?
It's not the subject here.

**Comment by sceenius** [comment]
Oh shoot, wrong issue
