### ISSUE TITLE
Change organizaton icon in sidebar navigation (S)

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#1104]
**AC**

- [ ] Change organization icon in the sidebar to the following:

<img width="293" alt="image" src="https://user-images.githubusercontent.com/75991832/167043860-51832907-c7dc-45de-9cd6-3a4c9d1e3b5d.png">
<i class="fa-solid fa-chart-network"></i>

**Comment by arsenijesavic** [comment]
far fa-flag -> fas fa-chart-network

**Comment by leonieherma1** [comment]
@arsenijesavic let's change it to this one for now: 

<i class="fa-regular fa-building"></i>

**Comment by arsenijesavic** [comment]
> @arsenijesavic let's change it to this one for now:

@leonieherma1 what is the name?
