### ISSUE TITLE
Sidebar dissappears on small screens (S)

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#1114]
Reproduce:
1. https://dao.hypha.earth/hypha/
2. Make window so narrow the sidebar disappears
3. Click profile image - a sidebar now overlays from the side
4. Close the overlay with the close button
5. make window wide again

Expected Result: Sidebar reappears (because there is room)
Actual Result: Sidebar remains hidden even though there is room

Likely cause: The browser remembers I clicked "close" but fails to take into account I was merely closing an overlay - there's no other way to get rid of the overlay. 

Possible solutions by @n13:

- [ ] I think the solution is to never go into overlay mode; not have a close button on the sidebar.
- [ ] sidebar never disappears automatically, even when the window gets very small; it only disappears when the user is explicitly closing it. Then controlling the sidebar is always an intentional action.

**Comment by n13** [comment]
https://user-images.githubusercontent.com/65412/167809415-9f09b4fb-39f5-481b-97c1-67604e62568e.mov

**Comment by leonieherma1** [comment]
@pugakn Alex has the same problem: https://discord.com/channels/722537361480613950/732285564384051323/979150917049917450
