### ISSUE TITLE
Fixes on dev

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#1152]
- [x] Badge Creation - Cash token shows up twice
<img width="1101" alt="image" src="https://user-images.githubusercontent.com/75991832/168667148-0dd81651-3a31-4fea-bbf5-108e1942adf1.png">

- [ ] Bade Type Creation - Custom Icon not working (endless loading)
<img width="972" alt="image" src="https://user-images.githubusercontent.com/75991832/168667253-420e4f23-4246-4bee-86e2-16b6c2e38a6b.png">

- [x] Badge restriction Banner is not showing
<img width="972" alt="image" src="https://user-images.githubusercontent.com/75991832/168667377-3669127d-aab7-4e3d-90dd-4cdb8c5da75b.png">

- [x] Proposal Page "Sort by date descending" not working - did all these members sign on on febraury 14, 2021?
https://dao-dev.hypha.earth/hypha/members
<img width="1061" alt="image" src="https://user-images.githubusercontent.com/75991832/168667851-cf98e4e0-6f28-4174-b914-fb7c4eececbe.png">

- [ ] IPFs Upload missing for Generic Contributions
<img width="1002" alt="image" src="https://user-images.githubusercontent.com/75991832/168668441-5672cb37-5147-47b5-af1e-936da2deaf84.png">

- [x] Roles that I currently have for "voting" don't show up in profile plus some empty grey widgets
<img width="1312" alt="image" src="https://user-images.githubusercontent.com/75991832/168669002-22c21e0d-1573-4606-b89e-05b99725e6aa.png">

- [x] "from" small
<img width="459" alt="image" src="https://user-images.githubusercontent.com/75991832/168671605-1b5230a4-d5af-49d9-89e7-3c664a66fdb0.png">

**Comment by DaniPoot** [comment]
@leonieherma1  On the member's list which is the problem?. I verified the query and the date is correct exists many users with this creation date (2021-02-14)

**Comment by jmgayosso** [comment]
@leonieherma1 Can you test please? now all fixes are on dev, just regarding IPFS issues, I think is just the IPFS server is slow, I dont know why, but all from us side looks good, I will ask Sebastian if we have a way to validate the server status

**Comment by leonieherma1** [comment]
@DaniPoot @jmgayosso can you please check with Gery - I have confirmation from Joachim that all these people definetely signed up before 14. february 2022 - and not all on the same day. It's impossible @Gerard097

**Comment by Gerard097** [comment]
> 

It's very likely that the creation date (register) was afected by a migration process we did about that time (document graph migration) so that's why a all of those users have that date as their register date

**Comment by leonieherma1** [comment]
@DaniPoot sometimes the date is missing on the proposal detail page, sometimes it says "starting from" and sometimes just "starting May 22"

<img width="518" alt="image" src="https://user-images.githubusercontent.com/75991832/168898816-1edbdda1-0ef5-4546-8a25-2d0387d8d556.png">
https://dao-dev.hypha.earth/hypha/proposals/30473

<img width="496" alt="image" src="https://user-images.githubusercontent.com/75991832/168900469-fc702bd8-c9b2-432f-bb31-9e914f121375.png">
https://dao-dev.hypha.earth/hypha/proposals/30455

<img width="932" alt="image" src="https://user-images.githubusercontent.com/75991832/168900566-554fab23-5945-42e9-b66e-6abf820dbf14.png">
https://dao-dev.hypha.earth/hypha/proposals/30439

Please make sure when you test that those things are consistent

**Comment by leonieherma1** [comment]
@DaniPoot @jmgayosso also the badge assignment proposal links are broken:

https://dao-dev.hypha.earth/hypha/@johnnyhypha1
<img width="943" alt="image" src="https://user-images.githubusercontent.com/75991832/168901045-bed4a0dc-11d1-4e54-ac8e-49bd41014585.png">

**Comment by leonieherma1** [comment]
@DaniPoot please change tooltip to "Maximum amount of periods a badge holder can apply for"

**Comment by leonieherma1** [comment]
@DaniPoot plwase let me know when the issues are fixed

**Comment by leonieherma1** [comment]
@jmgayosso everything looking good, thanks
