### ISSUE TITLE
Update Link to Documentation & Discord Link (S)

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#1177]
**Summary**
As a DAO user I would like to be able go to the latest Documentation.

**AC**

- [ ] Updated link to documentation on https://dao.hypha.earth/hypha/ to: https://notepad.hypha.earth/DBKEBKmIRMqqn9heCRf21w
- [ ] Add Discord Icon (and link) to the support page: https://dao.hypha.earth/hypha/support
- [ ] Headline: Need support?
- [ ] Copy: Please read our Documentation for more info. If you are stuck with a problem you can also reach out to us on discord in the "dho-support" channel.
- [ ] Link to documentation: https://notepad.hypha.earth/DBKEBKmIRMqqn9heCRf21w
- [ ] Link to Discord: https://discord.com/channels/722537361480613950/732285564384051323

**Design**
<img width="307" alt="image" src="https://user-images.githubusercontent.com/75991832/169386154-62a47c0e-57a7-4c8b-854a-b923279d3586.png">
(same as on Dashboard)

**Comment by pugakn** [comment]
This was replaced with a setting on the DAO so it is dynamic now
