### ISSUE TITLE
Consistent use of loading indicator (S)

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#1178]
**Summary**
As a DAO user I would like to always see the same loading indicator on all screens / places

**AC**

- [ ] Use same loading indicator everywhere (the one from initial loading screen):
<img width="526" alt="image" src="https://user-images.githubusercontent.com/75991832/169398729-b5e157a3-fd77-4469-ad46-83defe3856d8.png">

- [ ] Do not use the one with the two gears  (too bulky / distracting)
- [ ] Login page, explore page, navigation logo, browser tab, etc....

**Comment by pugakn** [comment]
Proposed solution:
Create a loading-indicator component, that is just a wrapper of the quasar loading component and use it everywhere, this way we can avoid inconsistencies. @Funkalux
