### ISSUE TITLE
Wallet page should show payments per DAO (M)

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#1196]
**Summary**
As a DAO user I would like to see my payments on the wallet page for every individual DAO.

**AC**
- [ ] Make it possible to check which payment belongs to which DAO

URL: https://dao.hypha.earth/demoxdaox/@leonieherma1/wallet

Frontend Story: https://github.com/hypha-dao/dho-web-client/issues/1162

**Comment by leonieherma1** [comment]
@arsenijesavic @Gerard097 is this done?

**Comment by arsenijesavic** [comment]
@Gerard097 Can I start doing this https://github.com/hypha-dao/dho-web-client/issues/1162 ?

**Comment by Gerard097** [comment]
Yep, it's both on dev & prod
