### ISSUE TITLE
UI Improvements for Treasury Screen

### ISSUE THREAD

**Issue by sceenius** [hypha-dao/dho-web-client#122]
1. Replace text buttons with icon buttons and text hover and color circular background (white icons) to save space:
* New TRX- https://fontawesome.com/icons/plus-circle?style=solid
* Endorse TRX -  https://fontawesome.com/icons/check-square?style=solid
* View TRX - https://fontawesome.com/icons/eye?style=solid
2. Change User Circle color to White - https://fontawesome.com/icons/user-circle?style=solid
3. Add "ACTIONS" heading to last column
4. Change "ID#" to "ID" and move "#" to second row and unbold it
5. Remove "My Requests" and default to "Open" (TBD)
6. Lower the aggregated tabs on the right side to where the table begins

![image](https://user-images.githubusercontent.com/24725582/94870654-1733e280-0416-11eb-8a13-825fc705d2f2.png)

**Comment by gregory-latinier** [comment]
Remove "My Requests" and default to "Open" (TBD) <= I wouldn't do that. Personally that's the only part that interests me.

**Comment by sceenius** [comment]
@gregory-latinier When testing, it was unclear to me what this does. Can we do the following instead:

- save the last view state and open it again without showing a separate link for "My Requests"
- highlight the opened view so it is clear or the user which view this is
- remove the link "My Requests"

**Comment by sceenius** [comment]
I don't see feature #1 on my machine..

**Comment by gregory-latinier** [comment]
My bad I forgot the icons

But if we remove the My requests link, how can we get back to it if the user chooses the OPEN filter ?

**Comment by sceenius** [comment]
Let's use the last active view for this.

**Comment by gregory-latinier** [comment]
I'm sorry but I still don't understand the changes I have to do.

What are the filters ?
What is the default filter the first time the user opens the page ?
Should I remember the last filter used ?

**Comment by sceenius** [comment]
ok, maybe I missed something with the filter lol. 
I don't see there's much to save in the last view, there is only All, Open, and Search. 
Unless we have other filter parameters I would say let's not save the view and keep the code simple?

**Comment by gregory-latinier** [comment]
So we use the search input at the top them
And we only have 2 items ALL | OPEN

It's just that as an average user I personally only use the MY REQUEST filter. With only All and Open I would have to type every time my account in the search bar.
So I wouldn't even bother to do that and wouldn't use the screen anymore

**Comment by sceenius** [comment]
Yep. 

I see where you come from. This screen is really not meant for the average user. You'd check your redemptions via the wallet.
