### ISSUE TITLE
Sidebar Glitching (S)

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#1224]
Reproduce:

1. Go to dao.hypha.earth
2. 13' screen at 75% zoom
3. See Screen flickering
4. Changing the zoom level to 70 or 80% solves it 

https://github.com/hypha-dao/dho-web-client/issues/1114#issuecomment-1138714739

**Comment by n13** [comment]
Testing on 13" laptop, I can't reproduce it anymore
