### ISSUE TITLE
Proposal Creation Wizard: max allowed period count

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#1258]
Reproduce:
1. Create a role assignment
2. Pick e.g. 28 periods
3. See error message: you must select less than 27 periods

<img width="568" alt="image" src="https://user-images.githubusercontent.com/75991832/171500198-7502cb95-0454-4ff6-b783-2ca297b9da1d.png">

4. Click to select 26 periods and click next and "publish to staging"
5. see error message: you must select less than 26 periods
<img width="615" alt="image" src="https://user-images.githubusercontent.com/75991832/171500502-fc3791b4-ae04-4141-8311-65bbe5b11480.png">

Expected behaviour:
Consistent use of max periods

Experienced behaviour: 
Mixed messages (less than 27 and less than 26 periods)

We are also working on changing the limit to 52 periods, see https://github.com/hypha-dao/dho-web-client/issues/1102

**Comment by leonieherma1** [comment]
> @leonieherma1 @Gerard097 Can we have the max number of periods on a setting from the backend so we can read it? Also maybe would be useful for owners of DAOs to be able to configure it?

yes good idea - is it possible to adjust per document type? E.g. assignments 12 periods and badge assignment 26?

**Comment by leonieherma1** [comment]
@pugakn good idea - I will add it to the design with massimo and create a story

**Comment by Gerard097** [comment]
Let's discuss it a bit more tomorrow after stand up, there are a few things that we might or might not need to chage/add
