### ISSUE TITLE
Banners: Use default text for hypha when no copy is filled in  (M)

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#1259]
**Summary**
As a DAO user I would like to see some default text on my banners so they don't look empty before I costumize the text.

**AC**
Add the following Banner text as a default:

- [ ] Dashboard:

Welcome to {DAO Name} 

The Hypha DAO provides simple tools and a framework to set up your organization from the ground up, together with others, in an organic and participative way. Our fraud resistant & transparent online tools enable you to coordinate & motivate teams, manage finances & payroll, communicate, implement governance processes that meet your organizational style.

- [ ] Proposals:
Every vote counts

Decentralized decision making is a new kind of governance framework that ensures that decisions are open, just and equitable for all participants. In the {DAO Name} DAO we use the 80/20 voting method as well as HVOICE, our token that determines your voting power. Votes are open for 7 days.

- [x] Also add a dynamic placeholder here, so the % number changes:

<img width="636" alt="image" src="https://user-images.githubusercontent.com/75991832/171503562-17fe4917-a5d1-46ab-964c-e382254494dd.png">

- [ ] Members:

Find & get to know other {DAO Name} members

Learn about what other members are working on, which badges they hold, which DAO's they are part of and much more.
- [ ] Organization:

Learn everything about {DAO Name}

Select from a multitude of tools to finetune how the organization works. From treasury and compensation to decision-making, from roles to badges, you have every lever at your fingertips.

**Comment by arsenijesavic** [comment]
@leonieherma1 This is backend change so I will reassign to @Gerard097

**Comment by arsenijesavic** [comment]
@leonieherma1 Yes I am, when dao gets created default values gets initiated and among them are banner settings. We would need to retroactively add for already created daos. @Gerard097

**Comment by Gerard097** [comment]
@arsenijesavic I'm still needing the values to set the backend variables
