### ISSUE TITLE
Add duration limit to assignment

### ISSUE THREAD

**Issue by sceenius** [hypha-dao/dho-web-client#126]
Assignments can be held for a maximum of 3 lunar cycles or 12 lunar periods (approx 3 months). We will restrict the selection of periods longer than 3 months on the UI, but not in the Smart contract.

For this, we will set the default ending period to 3 months for any new or extended assignment (it can be edited to shorten the assignment period). 

Once we reach the extension period (currently set at xx weeks before expiration) a warning message appears on the card/form and the "Extend" button is shown on the card (next to "Claim"). 

This button will invoke the new Edit function so that other properties of the assignment can be changed at the same time.

The copied assignment proposal will go through the regular 80/20/1T1W/1WK voting process and results will be merged with the original assignment after the vote has passed successfully.

**Comment by gregory-latinier** [comment]
Is it always restricted to 3 months ? Even for an extend request ?
