### ISSUE TITLE
Increase drop shadow

### ISSUE THREAD

**Issue by sceenius** [hypha-dao/dho-web-client#13]
Increase drop shadow on cards to the same value as in the https://dho.hypha.earth/#/assignments view

box-shadow: 0 1px 5px rgba(0,0,0,0.2), 0 2px 2px rgba(0,0,0,0.14), 0 3px 1px -2px rgba(0,0,0,0.12);

**Comment by gregory-latinier** [comment]
To this value you mean ? box-shadow 0 8px 12px rgba(0,0,0,0.2), 0 9px 7px rgba(0,0,0,0.14), 0 7px 7px 7px rgba(0,0,0,0.12)

The one you suggested is barely visible

**Comment by sceenius** [comment]
Oh yes, my mistake.

**Comment by sceenius** [comment]
Can you add the drop shadow to the member profile cards?
