### ISSUE TITLE
Enable profile link in sidebar (also for non members)

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#1385]
Reproduce:
1. https://dao.hypha.earth/regencivics/@leonieherma1
2. Try to access your profile via the sidebar

Expected behaviour:
I should be able to click on the profile icon

Experienced behaviour:
The profile button is disabled

<img width="1042" alt="image" src="https://user-images.githubusercontent.com/75991832/175427560-c6d99fe7-ec5e-47e6-be42-f5bf9f985c71.png">

**Comment by leonieherma1** [comment]
@Funkalux still disabled for me....

<img width="1787" alt="image" src="https://user-images.githubusercontent.com/75991832/177189140-3b00e1ce-84bd-4f07-bc12-531ed6fccf10.png">

**Comment by Funkalux** [comment]
That's because it's not merged into development yet =)

**Comment by leonieherma1** [comment]
@Funkalux lol makes sense. Let me know when I can test. All the stories in "testing" lane should be on dev :) otherwise they can be in pending pr
