### ISSUE TITLE
Suspension cards for assignments show up as blank on the UI

### ISSUE THREAD

**Issue by sceenius** [hypha-dao/dho-web-client#139]
![image](https://user-images.githubusercontent.com/24725582/95871770-0cdde680-0d3c-11eb-99a4-3771fc303637.png)

There is no additional info when opening the json file. 

We want to show the same data as we do with edit/create

**Comment by gregory-latinier** [comment]
We are circling back to the fact that it's not a database.
This is suspension proposal so it doesn't contain much information.
So I need to manage the join in the UI which will add more requests.
Expect some more lagging on this screen.

**Comment by sceenius** [comment]
I think we need to bite the bullet since the suspension is a) super
sensitive and b) totally unclear what it is about.
