### ISSUE TITLE
add button to clear cache after 7 seconds

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#1444]
Reproduce>
1. Open dao.hypha.earth

Expected behaviour:
I expect the website to load

Experienced behaviour:
Website loads really slow

Solution:

- [ ] Implement a button that offers to "clear site data"
- [ ] Automatically force clearing site data after 7 seconds

arseni story (add button to clear cache and force clear cache after 7 seconds)

**Comment by arsenijesavic** [comment]
closing as it is fixed with https://github.com/hypha-dao/dho-web-client/pull/1447
