### ISSUE TITLE
Comments on wrong proposal

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#1515]
Reproduce:
1. Go to https://dao.hypha.earth/hypha/proposals/28096
2. Check the comments

Expected behaviour:
I should not see any comments

Experienced behaviour:
I see the comments from HIP 3 proposal

Note: After refreshing it works and I don't see any comments

**Comment by evgenibir** [comment]
@leonieherma1 

On my side

The Response for 1st time visiting was correct i.e. 

Comments: `(0)`

Looks like this issue is related to #1516 

I will investigate this issue and will fix if I will find a weakness in code during next week after my current stuff.
