### ISSUE TITLE
search shows wrong titles

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#1516]
Reproduce:
1. Go to https://dao.hypha.earth/hypha/
2. Search for "council"
3. Set filter to "active"

Expected behaviour:
I should not see "Mark Epstein" for the North Star Badge (he never applied for it) - for me it shows Joachim

Experienced behaviour:
I see "Mark Epstein" on the north star badge card

<img width="945" alt="image" src="https://user-images.githubusercontent.com/75991832/186414253-53fc7b27-cf06-4e4e-a85d-64552040de59.png">
<img width="958" alt="image" src="https://user-images.githubusercontent.com/75991832/186414374-08ce5b5c-1564-4a0d-80fa-94abcf66c39f.png">

Is this a caching issue?

**Comment by evgenibir** [comment]
@leonieherma1 

On my side

The Response for 1st time visiting was correct i.e.

"North Star Badge
Joachim Stroh"

I will investigate this issue and will fix if I will find a weakness in code during next week after my current stuff.
