### ISSUE TITLE
Copy invite link should be main CTA

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#1522]
Please make the following design changes:

https://dao.hypha.earth/hypha/members

- [ ] make "copy invite link" the main CTA button (blue background)

<img width="867" alt="image" src="https://user-images.githubusercontent.com/75991832/186699202-0e57926e-593f-43d7-ba0e-a3112631cd0d.png">

**Comment by evgenibir** [comment]
Hi @leonieherma1!

I checked the design here https://xd.adobe.com/view/7cc1de2c-4b1e-466b-8ac4-eb37f309c3bb-2992/screen/da59cea8-a4c9-4f6f-81c5-208b16a1e122/ and the button looks correct. There is a "Become a member" button next to it, which should be blue, but the design is probably not ready yet, so we don't add it. Should I make the "Copy invite link" button blue for now?
![image](https://user-images.githubusercontent.com/18167258/188111485-6e96a534-5686-477b-a917-43fc6d8936a8.png)

**Comment by leonieherma1** [comment]
> Hi @leonieherma1!
> 
> I checked the design here https://xd.adobe.com/view/7cc1de2c-4b1e-466b-8ac4-eb37f309c3bb-2992/screen/da59cea8-a4c9-4f6f-81c5-208b16a1e122/ and the button looks correct. There is a "Become a member" button next to it, which should be blue, but the design is probably not ready yet, so we don't add it. Should I make the "Copy invite link" button blue for now? ![image](https://user-images.githubusercontent.com/18167258/188111485-6e96a534-5686-477b-a917-43fc6d8936a8.png)

Hey @evgenibir yes so there is two cases:

1. I am NOT a member of the DAO. I will go to this page and see the main CTA (blue) that says become member
2. I am ALREADY a member of the DAO. I should not see the "become a member" main CTA (blue) because I am already a member. So this button for me is hidden. Now the secondary CTA (copy invite link) should become the main CTA (blue).

let me know if you have questions

**Comment by evgenibir** [comment]
> > Hi @leonieherma1!
> > I checked the design here https://xd.adobe.com/view/7cc1de2c-4b1e-466b-8ac4-eb37f309c3bb-2992/screen/da59cea8-a4c9-4f6f-81c5-208b16a1e122/ and the button looks correct. There is a "Become a member" button next to it, which should be blue, but the design is probably not ready yet, so we don't add it. Should I make the "Copy invite link" button blue for now? ![image](https://user-images.githubusercontent.com/18167258/188111485-6e96a534-5686-477b-a917-43fc6d8936a8.png)
> 
> Hey @evgenibir yes so there is two cases:
> 
> 1. I am NOT a member of the DAO. I will go to this page and see the main CTA (blue) that says become member
> 2. I am ALREADY a member of the DAO. I should not see the "become a member" main CTA (blue) because I am already a member. So this button for me is hidden. Now the secondary CTA (copy invite link) should become the main CTA (blue).
> 
> let me know if you have questions

Thanks!
