### ISSUE TITLE
Config Page: Explore banner (anchor dao only)

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#1558]
Summary:
As a Anchor DAO I would like to be able to change the copy and header image of the /explore page.

AC:
- add another section at the end of the "design" / "Banners" section
- Only make it visible for anchor daos
- add a field to upload header image
- add a field to change headline
- add a field to change description

<img width="1165" alt="image" src="https://user-images.githubusercontent.com/75991832/187935748-f7c4537f-8f09-40c0-8e36-de05e197b58d.png">

**Comment by arsenijesavic** [comment]
@Gerard097 Is there a way to identify anchor dao ?
