### ISSUE TITLE
DAO specific treasury (frontend)

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#1570]
Implement the multi tenant treasury frontend:

Backend:
https://github.com/hypha-dao/dao-contracts/issues/177

Design:
https://xd.adobe.com/view/27bc7fff-1845-449c-913a-4ecfb3c9461c-72ef/screen/1ca18329-6141-46b8-a7a2-c1d473049de2

**Comment by arsenijesavic** [comment]
@leonieherma1 I'm closing this one because we need to redefine the scope due to backend changes not keeping up with the design (payable in instalments)

**Comment by leonieherma1** [comment]
@arsenijesavic I cannot test this because I don't see the dao switcher on the treasury page 

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/75991832/191022715-c82642d6-42d2-455c-a961-62f22d972248.png">


and also "no data" on dev

**Comment by arsenijesavic** [comment]
@leonieherma1 This is not finished because it requires design changes

**Comment by leonieherma1** [comment]
> @leonieherma1 This is not finished because it requires design changes

which design changes do you mean?

**Comment by arsenijesavic** [comment]
> > @leonieherma1 This is not finished because it requires design changes
> 
> which design changes do you mean?

New updates on backend added payment in instalments, one row in table is not longer one payment but it can be multiple, so current UI is not reflecting the data. Because redemption can be paid in multiples it also mean that there are multiple signatures. We can discuss this with Luigi
