### ISSUE TITLE
Add "Change DAO name" to config page

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#1595]
Summary:
As a DAO admin I would like to be able to change the DAO name

AC:

- [ ] Add field to config page "General" with "DAO name"
- [ ] Allow max of 50 characters

Design
<img width="1278" alt="Screenshot 2022-09-15 at 19 54 48" src="https://user-images.githubusercontent.com/75991832/190533955-3b970a45-9a80-4dba-89d2-a8ce09280be1.png">

**Comment by evgenibir** [comment]
Hello @leonieherma1! 

In the course of solving this issue, I added a new field to change the name, but I noticed that editing other fields did not work. There is a transaction, but after refreshing the page everything is as it was. Can you please tell me if this has worked before?

**Comment by leonieherma1** [comment]
@arsenijesavic
