### ISSUE TITLE
Show actual compensation when commitment is reduced

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#1596]
Summary:
As a DAO user I would like to see my current compensation when I reduce my commitment or change my deferral.

AC:

- [ ] Show correct token (Cash, Utility & Voice) when I change my commitment
- [ ] Show correct token (Cash, Utility & Voice) when I change my deferral

Example:
https://dao.hypha.earth/hypha/proposals/31372

Design:
tbd

**Comment by arsenijesavic** [comment]
@pugakn this is still an issue
this proposal has reduced commitment:
<img width="881" alt="Screenshot 2023-02-09 at 13 05 57" src="https://user-images.githubusercontent.com/7712798/217912894-5a4889f4-2f44-4673-a64c-ed68ba04e618.png">

this is what should display:
<img width="884" alt="Screenshot 2023-02-09 at 13 06 36" src="https://user-images.githubusercontent.com/7712798/217913029-6688b116-4b86-4d11-a64a-f49a462a9111.png">
