### ISSUE TITLE
Payment document 

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#1601]
Implement pricing plan in the DAO where people can send monthly payments

### Specs

Each DAO has a pricing plan - can be a document
Freemium is free
Other pricing plans have a fee
Users need to pay fee monthly
They need to pay in Hypha tokens

### Possible implementation

We should look into the best way to implement this

But the basics are

We need to keep track what pricing plan a DAO is on
We need to be able to take / burn tokens - they send Hypha tokens, we burn them
We need to know what times they paid and how much
We need to be able to check if they're fully paid up

Frontend allows a user to 
- See what they've paid for
- See when they need to pay next
- Remind for payment with some leeway
- Allow them to pay

We could model this on roles and periods - we could hav a payment doc, with periods, some of which have been paid, some are unpaid, and that's basically it. Then all we need is an action to burn these tokens and make entries in the payment doc.

**Comment by n13** [comment]
Ok I added details above
