### ISSUE TITLE
Mobile: Proposal Detail Screen

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#1620]
Summary:
As a DAO user I would like to be able to see the details of the proposals on mobile.

Design:
https://xd.adobe.com/view/128aaa68-0398-4b35-b42c-477803d7b6da-47d9/screen/e2242c19-7749-4d73-b3bd-08d32fc00aa9/

**Comment by evgenibir** [comment]
Hello @leonieherma1! 

I partially implemented the mobile design integration for the proposal details when I did the mobile integration of the proposal creation wizard, could you please send the design for the landscape orientation of the mobile phone? Now the voting widget covers almost the entire screen.
