### ISSUE TITLE
Heart should be filled after liking a comment

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#1622]
Reproduce:
1. Go to https://dao.hypha.earth/hypha/proposals/35814
2. Like a comment

Expected behaviour:
I expect the heart to be filled after liking a comment

Experienced behaviour:
The heart is empty after liking a comment

<img width="968" alt="image" src="https://user-images.githubusercontent.com/75991832/191825636-877a657b-f1d7-44b1-bc62-b81eb82a9dda.png">

**Comment by evgenibir** [comment]
hi @leonieherma1! this issue seemed to me a quick fix and I was distracted by it, I checked, but the heart is really painted over after the user likes it, can someone else test it?
![image](https://user-images.githubusercontent.com/18167258/191966927-4d746dd9-8e9f-417e-a0c6-15e424ccba4f.png)

**Comment by evgenibir** [comment]
@arsenijesavic do you have any idea what it could be related to?

**Comment by leonieherma1** [comment]
@arsenijesavic @evgenibir it is still not working for me:

Before it was just the heart but when I like it it suddenly said "0"

<img width="949" alt="image" src="https://user-images.githubusercontent.com/75991832/192544419-2f31915d-d3b8-4920-b6d5-e8c9e8265dba.png">

but after reloading it works:
<img width="934" alt="image" src="https://user-images.githubusercontent.com/75991832/192545136-df433d84-2ae4-4577-b58e-cf485bafcbef.png">


when i try to "unlike" the comment - it is not working either:

<img width="1121" alt="image" src="https://user-images.githubusercontent.com/75991832/192545368-88d3aa6d-1563-4b64-b5f4-747771ccb4fa.png">

if I refresh it also doesnt work.

When I click on /dashboard and then go back to the proposal detail, then it works:
![Uploading image.png…]()
