### ISSUE TITLE
Organisation Page: Markdown shows wrong in preview

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#1631]
Reproduce:
1. Go to https://dao.hypha.earth/hypha/organization
2. Check "Passed generic contributions"

Expected behaviour:
See the preview text in the right format (bold, italic, etc..)

Experienced behaviour: 
I see the markup

<img width="1038" alt="image" src="https://user-images.githubusercontent.com/75991832/192021230-d5d2b81d-fcca-4b73-adb0-fc9bfcf3d97b.png">

**Comment by evgenibir** [comment]
@leonieherma1 
![image](https://user-images.githubusercontent.com/18167258/201047160-f51d14ff-ac64-434f-886c-3bb7ac5c366d.png)
If I use the same plugin that we use to parse the markdown in proposal details, then I have no control over these transfers. The only option I see is to increase the height of the block (screenshot 2)
![image](https://user-images.githubusercontent.com/18167258/201047594-ef2af279-02fd-438a-b587-fe8e569573f7.png)

**Comment by leonieherma1** [comment]
@evgenibir what are our options?

**Comment by evgenibir** [comment]
> 

I think we need to consult with Arseniy or someone about the design, because I really don't know how best to proceed in this situation...

**Comment by leonieherma1** [comment]
@arsenijesavic can you help?

**Comment by arsenijesavic** [comment]
@leonieherma1 I suggested to @evgenibir we strip down the markdown for this preview so it's showing as plain text in this part, but inside the proposal, it shows formatted text
