### ISSUE TITLE
Banner: align X with copy

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#1634]
Reproduce:
1. Go to https://dao.hypha.earth/hypha/members
2. See X on banner

Please align X with copy on Banner on following pages:

- [ ] https://dao.hypha.earth/hypha/
- [ ] https://dao.hypha.earth/hypha/proposals/
- [ ] https://dao.hypha.earth/hypha/members
- [ ] https://dao.hypha.earth/hypha/organization
- [ ] https://dao.hypha.earth/hypha/explore

<img width="951" alt="image" src="https://user-images.githubusercontent.com/75991832/192023370-a018c7b1-7bdb-49e9-91ca-3f733d91c8a1.png">

**Comment by evgenibir** [comment]
@leonieherma1 X must be on the same level as the title?

**Comment by leonieherma1** [comment]
> @leonieherma1 X must be on the same level as the title?

yes

**Comment by evgenibir** [comment]
@leonieherma1 
![image](https://user-images.githubusercontent.com/18167258/201036570-4328657a-4ba4-4b51-bc22-d3ef3e9df2d9.png)
Are you sure? I checked the design (screenshot) and there is the same solution as in dev, the close button is above the text. I think it will look strange if I put it on the same level with the title

**Comment by leonieherma1** [comment]
@evgenibir ok you might be right. let's leave it
