### ISSUE TITLE
Support Page: Link Button is not active (blue) when on page

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#1646]
Reproduce:
1. Go to https://dao.hypha.earth/demoxdaox/support
2. Check button colour

Expected behaviour:
The button should be active colour (blue) because I am on the page

Experienced behaviour:
The button is white (not active)

<img width="1089" alt="image" src="https://user-images.githubusercontent.com/75991832/192295654-2f9be6b1-57c5-44e1-b295-d2f3ffec39f3.png">

**Comment by evgenibir** [comment]
@leonieherma1 at the moment there is no button here, this is plain text, could you give me a link to which the user should go?

**Comment by leonieherma1** [comment]
@evgenibir I mean the "question mark icon" - it should be blue when I am on the page.
<img width="1375" alt="image" src="https://user-images.githubusercontent.com/75991832/200137903-5ace0d54-8940-4a0f-8ea0-2ee6d7cd746f.png">



Same behavior as the "gear icon" when I am on the configuration page:
<img width="1360" alt="image" src="https://user-images.githubusercontent.com/75991832/200137888-6c0088c4-9e35-441f-adbd-f7c34de3136f.png">
