### ISSUE TITLE
Keep 3 column layout consistent

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#1649]
Reproduce:
1. check the following three pages (should all have 3 column layout):

<img width="782" alt="image" src="https://user-images.githubusercontent.com/75991832/192303943-9ccc4571-bcfa-4e62-91ee-95180434554c.png">
<img width="786" alt="image" src="https://user-images.githubusercontent.com/75991832/192303985-695f69ee-473f-4c1c-8df2-215829b747bd.png">
<img width="789" alt="image" src="https://user-images.githubusercontent.com/75991832/192304080-ade0b2b5-0069-4137-aeb9-be8e296b7e91.png">

**Comment by evgenibir** [comment]
@leonieherma1 on full hd everything is in fine, with a smaller width the cards are wrap
![image](https://user-images.githubusercontent.com/18167258/201099613-e1490eaa-c4f8-4a28-bc5b-0af7fcf40f11.png)
![image](https://user-images.githubusercontent.com/18167258/201099668-0008d8fb-51e5-4351-93dc-f800db1e4b32.png)
![image](https://user-images.githubusercontent.com/18167258/201099733-950641c9-0f9f-49c9-8263-5e929880b772.png)

**Comment by leonieherma1** [comment]
@evgenibir ok but why are the three pages different? (my screenshots). I did not change the resolution but Members page fits 3 columns. Proposal & Explore only fit 2.

**Comment by evgenibir** [comment]
> @evgenibir ok but why are the three pages different? (my screenshots). I did not change the resolution but Members page fits 3 columns. Proposal & Explore only fit 2.

at what resolution was it tested?

**Comment by leonieherma1** [comment]
@evgenibir I can't reproduce it anymore...maybe it was fixed with some of the mobile updates in the latest release?

**Comment by evgenibir** [comment]
> 

I think yes, can I close this issue?

**Comment by leonieherma1** [comment]
> > 
> 
> I think yes, can I close this issue?

I already closed it
