### ISSUE TITLE
Proposal Cards should always be the same height

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#1654]
Reproduce:

1. Go to https://dao.hypha.earth/hypha/proposals/
2. Check height of cards:

<img width="666" alt="image" src="https://user-images.githubusercontent.com/75991832/192541781-8d579d85-c6aa-4251-83b7-a2c70550f31b.png">

Note: probably because 1 card has a comment?

**Comment by evgenibir** [comment]
This bug was fixed a long time ago. The task is outdated.
