### ISSUE TITLE
Downgrade Plan flow

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#1658]
Summary:
As a DAO user I would like be notified if I didn't pay and downgraded my plan.

AC:

- [x] Show pop up banner 14 days before plan expires
- [x] once the 14 days is over please show the red pop up
- [x] option 1: reactivate your DAO (link to price manager)
- [ ] option 2: downgrade to free plan: downgrade the following options:
- [ ] only keep first 5 users (check if they are admins - the admins get priority)

<img width="645" alt="image" src="https://user-images.githubusercontent.com/75991832/192784266-86202bff-ff19-4d11-a91c-72aecd117ef1.png">

Design:
https://xd.adobe.com/view/02cc95e9-2dd6-4a80-8396-42856518e49d-579f/

**Comment by arsenijesavic** [comment]
@Gerard097 check this out
