### ISSUE TITLE
Staging Card: Date missing

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#1668]
Reproduce:
1. Go to https://dao.hypha.earth/hypha/proposals/
2. Check cards in "staging"

Expected behaviour:
I see the date when the card was put into staging

Experienced behaviour:
I don't see the date 

<img width="350" alt="image" src="https://user-images.githubusercontent.com/75991832/194342543-2ce41407-6cba-4635-a274-0882ba47ff59.png">

**Comment by evgenibir** [comment]
@leonieherma1 ballot_expiration_t

**Comment by evgenibir** [comment]
@leonieherma1 this problem occurs because the server returns ballot_expiration_t: null for staged proposals

**Comment by leonieherma1** [comment]
@evgenibir is this then a backend story for Gery? Or how can we make the server return a value?

**Comment by evgenibir** [comment]
> 

yes, i think we need talk to him, maybe he can add new key in staged propodal object
