### ISSUE TITLE
[badge] Assignment card not same as role-assignment

### ISSUE THREAD

**Issue by sceenius** [hypha-dao/dho-web-client#170]
badge-assignment **card** same as role-assignment card (title=name, subtitle=badge name, avatar=user, badge=sidebar)

**Comment by sceenius** [comment]
For badge-assignment proposal: 

1 remove the title field on form (show badge title in write mode and name in read mode)
2 show the title of the badge in the subtitle on card
3 show the badge on the card (side area)

**Comment by gregory-latinier** [comment]
1 remove the title field on form (show badge title in write mode and name in read mode) <= I don't understand what you expect here.
If I remove the title field, I don't understand what you want to display.
Does "show badge title in write mode" means prefill the title input ?
"name in read mode" <= name of the proposer ?

**Comment by sceenius** [comment]
@gregory-latinier This is identical to the role-assignment, there is only a read-only title field, 

1 showing the title of the role (here: badge) when creating the proposal
2 showing the name of the role (here: badge) holder when view the assignment

**Comment by sceenius** [comment]
Waiting for issue #182 to resolve
