### ISSUE TITLE
Remove expired assignments from view

### ISSUE THREAD

**Issue by sceenius** [hypha-dao/dho-web-client#173]
There is a confusion why expired assignments are still visible in the view. Let create a historical view for these and move them out of the active view. The assumption is that claim can no longer be submitted when the assignment has expired.

**Comment by gregory-latinier** [comment]
That's not true, an assignment can be expired but have  unclaimed periods for the concerned user

Here is my suggestion => hide all expired assignments, if the user is connected keep his expired assignment in the main view if there are unclaimed periods

**Comment by sceenius** [comment]
Perfect!
