### ISSUE TITLE
Retrieve profile from Hypha onboarding service

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#1738]
Currently onboarding service requires the Cognito authenticated user to search and get user profiles.

Goal of this task is to implement API endpoint that would return public profiles without authentication.

**Comment by leonieherma1** [comment]
@Alex-IS is this still blocked?

**Comment by Alex-IS** [comment]
@leonieherma1 It's not. I've figured it out. Need to make a PR on `hypha-dao/ppp-client-api`
