### ISSUE TITLE
Remove Private Key field for members after X days

### ISSUE THREAD

**Issue by 3yekn** [hypha-dao/dho-web-client#174]
The document graph maintains a node with a ```created_date``` for each member document. I think that we should disallow using the private key field if the member document's created_date is older than X days (45 days?).  This gives them a grace period for account setup and getting started while also eliminating this risk.

**Comment by gregory-latinier** [comment]
I'm still using my PK when Anchor is acting strange <_<

**Comment by sceenius** [comment]
Yes, this is too early to turn off PK. I would say we need at least 50+%
adoption and no stability issues with Anchor and theLight wallet functional
(in beta).
