### ISSUE TITLE
Comment: emoji button overflows borders

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#1807]
right top and left border radius same as input

<img width="209" alt="image" src="https://user-images.githubusercontent.com/75991832/200945955-af337ce0-6ab9-432c-9811-617681de6154.png">

**Comment by evgenibir** [comment]
> Not fixed
> 
>  emoji.button.overflow.mp4

![image](https://user-images.githubusercontent.com/18167258/213991586-ad6da2e4-868c-48f8-ab49-d80f00e9bbaf.png)

It's strange because everything is fine with me, try clearing the browser cache

**Comment by arsenijesavic** [comment]
@pmmm @evgenibir I can confirm its working! moving to done
