### ISSUE TITLE
fix votes not loading on graphql

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#1814]
Summary:
Voting widget behaves unpredictably

Notes:
- check race condition on fetching data on the page
- i think something happen before something else
- and then sometimes things are shown correcy

<img width="604" alt="image" src="https://user-images.githubusercontent.com/75991832/201110611-96e40613-22c3-400b-a4d6-b17b7e323d25.png">

**Comment by arsenijesavic** [comment]
@Alex-IS moving this to you as its backend

**Comment by Alex-IS** [comment]
This is most probably related to #1908
