### ISSUE TITLE
DAO specific Treasury Frontend 

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#1822]
Here is the original FE story: https://github.com/hypha-dao/dho-web-client/issues/1570
Backend Story: https://github.com/hypha-dao/dao-contracts/issues/177

@Gerard097 please check with @evgenibir what needs to be changed here.

- [ ]  change contract- redeem action (different parameter)

**Comment by evgenibir** [comment]
@leonieherma1, Gerry said me that @Alex-IS already working on this issue

**Comment by Alex-IS** [comment]
@evgenibir I've pushed last night to this branch `feature/redemption-graphql` It is not finished yet, I have to fix profile image and the actions. However, I will not be able to start working again on this before my tonight ( so after today's meeting )
