### ISSUE TITLE
Token Sale "Object" error (Buy Hypha Token Button)

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#1844]
Reproduce:
1. go to https://dao-dev.hypha.earth/fastdao/login
2. login as admin
3. go to https://dao-dev.hypha.earth/fastdao/plan
4. click "buy hypha token"

Expected behavior:
I should see the token sale website and be able to purchase hypha token

Experienced behaviour:
- nothing happens when I click on the button
- when something happens for some user they see the "object" error on t he token sale website
- it works when you remove the parameters from the URL

**Comment by leonieherma1** [comment]
@Alex-IS can you share a link for testnet token sale for the frontend? @pug

**Comment by Alex-IS** [comment]
@leonieherma1 @pugakn Currently it is deployed to https://dp9rw57cx84kg.cloudfront.net
