### ISSUE TITLE
Proposal Creation Wizard: Badge Type

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#1849]
Redesign the badge type creation flow:

URL: https://dao.hypha.earth/hypha/proposals/create

https://xd.adobe.com/view/35b56d65-b989-47b5-b84e-b82d92dd011f-60e6/screen/7c3ebe49-eae6-4bc0-85a6-95d82d6bdaa5

**Comment by evgenibir** [comment]
@leonieherma1 we refuse the badge restrictions field?

**Comment by evgenibir** [comment]
![image](https://user-images.githubusercontent.com/18167258/206169794-d5c86909-aef9-48bb-b4de-4654df7a3188.png)
also, when the user uploads their icon here, where and how will it be displayed?

**Comment by leonieherma1** [comment]
@evgenibir the badge icon will be displayed on the overview page:

<img width="615" alt="image" src="https://user-images.githubusercontent.com/75991832/206239596-96ed0ffc-f0c4-4fd5-b38f-09ed06f3830d.png">
 then the user can "go back" and change it again

**Comment by leonieherma1** [comment]
@evgenibir custom badges will not have badge restrictions

system badges will have badge restrictions (can be set on the configuration screen) - Luigi is designing it right now
