### ISSUE TITLE
Proposal Creation Wizard: Badge Assignment

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#1851]
Redesign the Badge Assignment Flow:

URL: https://dao.hypha.earth/hypha/proposals/create

Note: The circle dropdown should be hidden (via a feature flag) until Milestone 5 - March 2023)

Design:
https://xd.adobe.com/view/35b56d65-b989-47b5-b84e-b82d92dd011f-60e6/screen/03a520c6-9175-4f3a-8eda-d6ae939c67e5/

**Comment by evgenibir** [comment]
@leonieherma1 Can I get a little more information on this issue? What exactly should I do? Hide badge assignment card button when creating a proposal?

**Comment by leonieherma1** [comment]
@evgenibir please redesign the current flow to create a badge assignment in the DAO:

1. Create badge assignment screen now:
<img width="996" alt="image" src="https://user-images.githubusercontent.com/75991832/205340149-a08739ae-77ba-4c89-baf3-e84b301e7d00.png">


New Design:
<img width="988" alt="image" src="https://user-images.githubusercontent.com/75991832/205340190-f802e83b-b543-44de-958c-238f5295fabd.png">
https://xd.adobe.com/view/35b56d65-b989-47b5-b84e-b82d92dd011f-60e6/screen/0050c336-4a0a-487a-90b2-54ad902a403d/

**Comment by evgenibir** [comment]
@leonieherma1 the new design is missing the Date / Duration step, is this some kind of bug? without this we can't create a badge assignment
![image](https://user-images.githubusercontent.com/18167258/206150137-59a17e1f-3b17-4cfb-beff-cb12172ebdd6.png)

**Comment by leonieherma1** [comment]
@evgenibir we are not doing start date or duration for badges anymore. they start as soon as the proposal is voted in and last forever (until someone suspends a badge assignment of someone)

**Comment by pmmm** [comment]
I tested the flow, but the start date step is there (visible) and can't select it to finish the creation process.

https://user-images.githubusercontent.com/2647958/213509830-a2c55e05-c290-4328-9288-6be8bcea4939.mp4

**Comment by evgenibir** [comment]
> I tested the flow, but the start date step is there (visible) and I can't select it to finish the creation process.
> 
> Expected Behaviour: It should let me select the date or the date should not be visible at all.
> 
> Experienced Behavior: I can't move further to finalize the badge proposal
> 
> Tested on staging: Version: 0.2.21

Hi @pmmm, you tried push "reset selection" button? And this not frontend issue because i get dates array from backend. Can you speak with Gerry about it?

**Comment by pmmm** [comment]
Hi @evgenibir , yes. here a recent video:


https://user-images.githubusercontent.com/2647958/214641213-a2d71fb1-ca67-49dc-8a20-0e363e0fc37d.mp4
