### ISSUE TITLE
Votes for extensions not showing up

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#1862]
Reproduce:
1.  Go to https://dao.hypha.earth/hypha/proposals/
2. Vote on a assignment extension e.g. https://dao.hypha.earth/hypha/proposals/41144
3. Vote gives success messages

Expected behavior:
The Quorum and Unity should change when members vote, as well as the number of votes in the title "Votes (0)"

Experienced behaviour:
The quorum and unity don't change, neither does the voting number:

<img width="322" alt="image" src="https://user-images.githubusercontent.com/75991832/205084675-e0e37c0d-26fa-4bce-a56b-aa156460fc81.png">

**Comment by evgenibir** [comment]
@leonieherma1 i already fixed it, i think we can close this issue
