### ISSUE TITLE
Extension card not showing Proposal Type

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#1892]
Reproduce:
1. Go to https://dao.hypha.earth/hypha/proposals/
2. Check preview of any extension

Expected behviour:
I should see the label for the proposal type (e.g. Badge Assignment) and possibly for role assignments (Salary Band and commitment) and the label "Extension"

Experienced behaviour:
I only see the label for "Extension"

<img width="312" alt="image" src="https://user-images.githubusercontent.com/75991832/206740214-eec69aa0-844a-4a84-9b03-1c396aa1d4d3.png">

**Comment by evgenibir** [comment]
@leonieherma1 Can we postpone this task until there is an active document of type "Extension"? So that I can get the object and add the required fields for those tags?

**Comment by leonieherma1** [comment]
@evgenibir tthere is no proposal type extension? how do extensions work now? Can you check with Gery to get the info you need

**Comment by evgenibir** [comment]
> @evgenibir tthere is no proposal type extension? how do extensions work now? Can you check with Gery to get the info you need

@Hi @leonieherma1! You misunderstood me, I'm sorry, I meant until someone creates a proposal to expand their role in the DAO, I meant it.

**Comment by leonieherma1** [comment]
@evgenibir haha yes good idea! thanks for clarification
