### ISSUE TITLE
Banner not expanding for longer text and not pausing for a week on mobile

### ISSUE THREAD

**Issue by sceenius** [hypha-dao/dho-web-client#192]
Nik reported that the banner is bothering him a lot on the mobile phone. Can we hide it on mobile screens or resize it and make the 1 week dismiss work on mobile? 

![image](https://user-images.githubusercontent.com/24725582/98881160-62023a80-2457-11eb-8537-1213d25519a0.png)

**Comment by gregory-latinier** [comment]
I just tested the dismiss, it works.
It's not displayed anymore on my mobile.

I'll improve the design
