### ISSUE TITLE
Edit staged proposal bug

### ISSUE THREAD

**Issue by evgenibir** [hypha-dao/dho-web-client#1928]
Edit staged proposals doesn`t work

[Nik - just wanted to report the same]

Steps to reproduce:
1 - Create proposal 
2 - Publish on staging
3 - Click on "Edit Proposal" in the overview

Expected result:
I am editing the proposal

Actual result:
A screen appears with "Complete your draft proposal". 
The button "Continue Proposal" does not work - nothing happens clicking on it
I can't edit the staged proposal. 

<img width="1030" alt="image" src="https://user-images.githubusercontent.com/65412/211441892-82bffdf6-1808-4de5-b2aa-e5cf728537f1.png">

**Comment by pmmm** [comment]
Hi @evgenibir 
Expected result:
Continue editing the proposal and publishing.

Atual result:
Can't continue the create the proposal or publishing it
Video: https://adilo.bigcommand.com/watch/c8Lx9hLv

Staging Demoxdaox
Google Chrome V 109.0.5414.87

**Comment by arsenijesavic** [comment]
@evgenibir check @pmmm last comment i updated video
