### ISSUE TITLE
Open transaction (eye icon) does not work

### ISSUE THREAD

**Issue by dappdever** [hypha-dao/dho-web-client#194]
The button is enabled but clicking the icon doesn't do anything.  No error in console.

**Comment by sceenius** [comment]
Assuming this works now, I can't really test it and it is for viewing only.

**Comment by gregory-latinier** [comment]
The transaction id is now correctly picked but for some reason the network is undefined.
It comes from env var but they are correctly set in the deployment. I'm not sure what's wrong now.
