### ISSUE TITLE
Upvote Election: Dashboard

### ISSUE THREAD

**Issue by arsenijesavic** [hypha-dao/dho-web-client#1940]
As a DAO User 
I would like to be able to have UpVote Election Dashboard
So that I can manage to whole process in the one place.

[Design](https://xd.adobe.com/view/c8ce8f1d-72de-4836-9373-96fb5d7f130f-9d9d/screen/453c60ca-f79f-421d-96e1-6d3147c4bc7d/)

Upvote Election Dashboard should be new screen/route
the screens should change automatically based on the timer

- [x] add sing-up voting screen
<img width="1374" alt="Screenshot 2023-01-21 at 08 49 21" src="https://user-images.githubusercontent.com/7712798/213872326-35d20537-92c4-4b24-ac6b-9333e346f2aa.png">

- [x] add round/rounds voting screen
<img width="1374" alt="Screenshot 2023-01-21 at 08 49 34" src="https://user-images.githubusercontent.com/7712798/213872334-4620a224-83d3-4dd2-8b48-ea1daa7fbc4d.png">

- [x] add chief delegate round screen
<img width="1374" alt="Screenshot 2023-01-21 at 08 49 55" src="https://user-images.githubusercontent.com/7712798/213872339-e6040d12-d211-4652-baaa-7eef891344c1.png">

- [x] add head delegate round screen
<img width="1374" alt="Screenshot 2023-01-21 at 08 50 04" src="https://user-images.githubusercontent.com/7712798/213872344-33c3b1e7-22b6-40e7-8954-65d985c2c4e7.png">

- [x] add voting result screen
<img width="1374" alt="Screenshot 2023-01-21 at 08 50 13" src="https://user-images.githubusercontent.com/7712798/213872345-624c6812-75a5-4b7b-9794-5170eed52ba2.png">

**Comment by evgenibir** [comment]
@arsenijesavic for this we should create new badges? Voter and Delegate right?
![image](https://user-images.githubusercontent.com/18167258/215100422-898bd243-f048-4c1c-bd0d-07d5c0e80191.png)

**Comment by arsenijesavic** [comment]
@evgenibir Yes they will be available on backend here:
https://github.com/hypha-dao/dho-web-client/issues/1947
https://github.com/hypha-dao/dho-web-client/issues/1948

do you need any additional specs ?

**Comment by evgenibir** [comment]
> 

No, thanks
