### ISSUE TITLE
Proposal Publish: Fix blinking issues 

### ISSUE THREAD

**Issue by arsenijesavic** [hypha-dao/dho-web-client#1961]
Steps:
1. create proposal
2. publish it to staging
3. publish it

Expected result:
When you click publish proposal screen should not blink

Actual result:
When you click publish proposal screen is blinking

Video: 
https://www.screencast.com/t/TyLJk3DY3

**Comment by pmmm** [comment]
https://user-images.githubusercontent.com/2647958/214858550-3f521e2b-7890-4818-b477-5b303dc3d80e.mp4

@arsenijesavic just add here the video for redundancy...
