### ISSUE TITLE
Revision of salary fields

### ISSUE THREAD

**Issue by sceenius** [hypha-dao/dho-web-client#20]
**ALL FORMS**
- [x] On all forms, remove %HUSD field 
- [x] On all forms, remove Liquid Seeds field
- [x] On all forms, remove text "%HUSD" in description
- [x] On all forms, display all percentages without decimals and display all token values with 2 decimals and a separator for thousands (use localized display for currency)

**ASSIGNMENT FORM**
- [ ] Compute the token value based on Smart Contract function and multiply by 4 (monthly) if toggle is TRUE
- [ ] Add smart contract function to provide token values (including point-in-time SEEDS price) @dappdever
- [x] Add subheading and spacing before token fields (see below)
- [x] Add USD equivalent to subheading 

**CONTRIBUTION FORM**
- [ ] Compute the token value based on Smart Contract function 
- [x] Make token fields editable if toggle is TRUE (see below)
- [x] Enable smart contract to allow user to input either integers or assets (but not both) @dappdever  
- [x] Add subheading and spacing before token fields (see below)

**ROLE FORM**
- [x] Replace the USD equivalent with a B1-B7 dropdown (see below for list of values)

Revised assignment form:
![image](https://user-images.githubusercontent.com/24725582/92158525-0897e280-edfa-11ea-9ca3-9ab6984002c8.png)

- [x] toggle token switch will compute the monthly token salary (4 times period)
- [x] untoggle will revert to the default display, salary per period (weekly)

Revised contribution form:

![image](https://user-images.githubusercontent.com/24725582/92158816-793eff00-edfa-11ea-87ea-abbc56d10735.png)

- [x] toggle token switch will erase and disable the USD and DEFERRED% fields and enable the token fields for editing
- [x] BUT it will keep the computed tokens for the previously entered USD and DEFERRED% fields (for easier editing)
- [x] untoggle will erase the token fields and enable the USD and DEFERRED% fields for editing

**Comment by sceenius** [comment]
@dappdever This needs further discussion:

1) If we allow this on the Assignment object, it will no longer be connected to the role compensation
2) Hence a (future) token salary should be defined on the Role object to be used as a template
3) For now, I propose to do this on the Contribution object instead, where I see the most common use case

From what I understand, the UI does not send any assets/token values to the contract, so this would be a change (you mentioned the smart contract is able to process tokens).

**Comment by gregory-latinier** [comment]
For roles, replace the USD equivalent with a B1-B7 dropdown <= what's this ?

**Comment by sceenius** [comment]
Display all percentages without decimals and display all token values with 2 decimals and a comma to separate thousands (ideally use localized display for currencies).

**Comment by sceenius** [comment]
Salary buckets B1-B7 as follows (store the numeric value, display the "Bx - xxxxx" value:

B1 - 70,000
B2 - 90,000
B3 - 110,000
B4 - 130,000
B5 - 1500,000
B6 - 170,000
B7 - 190,000

**Comment by sceenius** [comment]
We also need to display the USD equivalent from the role on the assignment form. Let's discuss how/where.

**Comment by gregory-latinier** [comment]
> We also need to display the USD equivalent from the role on the assignment form. Let's discuss how/where.

No problem, I'll wait for the information to start this task

**Comment by sceenius** [comment]
Note: token computation coming from contract at a later release

**Comment by dappdever** [comment]
@sceenius @gregory-latinier - here's how the contract will determine whether the proposal (including edits) is setting assets directly OR if the smart contract should calculate them.  It is based whether the client passes any of the known asset values or not.  

This is the function:
``` c++
bool hyphadao::is_proposal_direct_assets (const map<string, asset> &assets) 
{
    string known_asset_keys[] { "hypha_salary_per_phase", "hvoice_salary_per_phase", 
                                "seeds_escrow_salary_per_phase", "husd_salary_per_phase",
                                "hypha_amount", "hvoice_amount", "husd_amount", "seeds_escrow_amount"};

    for (int i{0}; i < std::size(known_asset_keys); i++)
	{
		if (assets.find(known_asset_keys[i]) != assets.end()) {
            // detected a known asset key, assume proposal must be setting them directly
            return true;
        }
	}
    
    // didn't find any known asset keys, assuming proposal needs to calculate assets
    return false;
}
```

**Comment by sceenius** [comment]
On the Contribution form, if tokens are edited, display "N/A" on the both the USD equivalent and %Deferred fields. See mockup.
![image](https://user-images.githubusercontent.com/24725582/92496705-7a8b7580-f1c6-11ea-8079-d6b18d337c13.png)

**Comment by gregory-latinier** [comment]
I never send the USD and deferred so in the proposal they will always be empty
Should I hide them ?

**Comment by sceenius** [comment]
Hiding works too. Either way,

**Comment by gregory-latinier** [comment]
I mean in both the form and the view

**Comment by sceenius** [comment]
Yes, in both makes sense.

**Comment by sceenius** [comment]
Done, pending smart contract from @dappdever

**Comment by dappdever** [comment]
@gregory-latinier re: this line item: 
```
Add smart contract function to provide token values (including point-in-time SEEDS price) @dappdever
```
This can't be added as a smart contract function, but as an off chain web service. I think we decided that this isn't needed for now though.  Can you confirm?

**Comment by gregory-latinier** [comment]
Yes that's fine we don't use it for now.
The calculations are made in the form as an indication and I send the assets.
In all the views the assets are taken directly from the smartcontract without calculations, except for the estimated deferred seeds field
