### ISSUE TITLE
Add return to active view button 

### ISSUE THREAD

**Issue by sceenius** [hypha-dao/dho-web-client#200]
Add the same "view" button to return to the active view (from the historical view) to the roles-assignments view (there is no button). Let me close this one and add a new one for this.

![image](https://user-images.githubusercontent.com/24725582/99090959-39845880-259d-11eb-95b7-ca2901a24cff.png)

**Comment by gregory-latinier** [comment]
It's not the same thing here
For role assignment we are talking about archived proposals
while for assignment it's active but expired assignment object
