### ISSUE TITLE
[assignment] Dynamic commitments

### ISSUE THREAD

**Issue by sceenius** [hypha-dao/dho-web-client#203]
This feature allows the owner of a role-assignment to adjust the commitment level. 

Note: this feature requires successful transition to documents. 

**Business Rules**
- only the owner can adjust the assignment
- the actions are effective immediately (no voting period)
- the status of the assignment goes to "adjusted" (and shows in the ribbon "ADJUSTED"  with color red (same as suspend))
- the claims for the **adjusted period** are pro-rated to the start date of the pause and zero if the entire period is affected
- [NEW] the commitment level cannot be higher than the original commitment level from the role-assignment
- [NEW] rename the "Edit" function to "Modify"
- [NEW] show the current commitment level on the card, yellow when normal, red when below normal

**UI/UX**
- we add another ellipse menu to adjust an assignment
- the icon for adjust is https://fontawesome.com/icons/sliders-h?style=solid
- we input the adjustment through a slider with a maximum value (commitment level of role-assignment)
- use slider component with 5% stepper and +/- buttons and add text 0-MAX% with MAX = %commitment of assignment)
- add help text for "Modify" - "If you modify your assignment you will propose your edits in a new vote. Once passed, your edits will merge with the existing assignment."
- add help text for "Adjust" - "If you adjust your assignment, your %commitment will be immediately reflected on your next claim (no vote is necessary). Multiple adjustments during the same claim period will be included in the calculation."
* add help text for "Withdraw" - "If you withdraw your assignment, it will be removed from the DHO and claims will no longer be processed, effective from the period you withdraw the assignment. "

![image](https://user-images.githubusercontent.com/24725582/103232602-df4f1500-4908-11eb-80f0-3b8a27a085d2.png)

**Comment by gregory-latinier** [comment]
@dappdever is the smartcontract ready for this feature?

**Comment by sceenius** [comment]
From our dev call:

There are two possible related tracks related to this feature: 

1) backwards-looking time tracking and 
2) forward-looking time adjustments

The focus for this particular issue is on #2 only, to 

a) support multi-role-assignments (shifting the percentages if your work shifts)
b) announcing pauses in your engagements (vacation, detox, etc)
c) making it visible to anyone else in the org that your engagement level in that role has changed
d) allowing for quick adjustments for the upcoming quest feature ("yes I like to participate, but need reduce my role-assignment first to stay below 100%")

**Comment by Gerard097** [comment]
@gregory-latinier the smart contract action that has to be called for this functionality is: `adjustcmtmnt`

Parameters with example:

```
{
    "issuer": "gerard01234" -> [name],
    "adjust_info": [
        [
            "assignment": ca294a25b4e422f47ade67f6a5cfbcb4684fa8dbdc11b543b65b61b4370ba9d9 -> [checksum256]
            "new_time_share_x100": 70 -> [int64_t] 
        ]
    ] -> [ContentGroups] 
}
```
  
Smart Contract code: https://github.com/hypha-dao/dao-contracts/blob/7be2287971a977a03c9d78bb27c218f75237d62b/src/dao.cpp#L578-L596

**Comment by lukegravitt** [comment]
@sceenius Any additional help text for the 'Suspend' option as well for consistency?

**Comment by sceenius** [comment]
@lukegravitt Yes, let's use this icon for suspend - https://fontawesome.com/icons/ban?style=solid

**Comment by lukegravitt** [comment]
One question for @gregory-latinier / @Gerard097

How do we determine the assignment's _original_ time commitment? This is needed for 2 cases: to determine if the current time commitment is below the original and to know how high to allow the bar to go.

I'm not positive but I think my current PR will only let you lower your commitment since we haven't distinguished between original and current on the frontend.

**Comment by Gerard097** [comment]
There is an item in the details group within content_groups `'time_share_x100'`. This field specifies the original approved commitment in the range [0, 100]. 
i.e. 
```
              {
                "label": "start_period",
                "value": "BAD6C07306D7B0E6DFABFB668486EBA7497E622F51EF596057C5CEAB26C4780A",
                "type": "checksum256",
                "content_sequence": 12
              },
              {
                "label": "time_share_x100",
                "value": "50",
                "type": "int64",
                "content_sequence": 13
              },              
              {
                "label": "content_group_label",
                "value": "details",
                "type": "string",
                "content_sequence": 0
              },
              {
                "label": "husd_salary_per_phase",
                "value": "0.00 HUSD",
                "type": "asset",
                "content_sequence": 2
              },
              {
                "label": "seeds_escrow_salary_per_phase",
                "value": "225189.9136 SEEDS",
                "type": "asset",
                "content_sequence": 5
              },
              
              {
                "label": "hypha_salary_per_phase",
                "value": "1143.27 HYPHA",
                "type": "asset",
                "content_sequence": 4
              },
              
              {
                "label": "period_count",
                "value": "8",
                "type": "int64",
                "content_sequence": 14
              },
              {
                "label": "hvoice_salary_per_phase",
                "value": "3849.40 HVOICE",
                "type": "asset",
                "content_sequence": 3
              }
```

**Comment by lukegravitt** [comment]
Ok great, this is helpful. We are ysing this value appropriately on the frontend then.

Followup - after I've made an adjustment and lowered my commitment, how would I see that new value?

**Comment by Gerard097** [comment]
There is an edge going from the assignment document with the name `lastimeshare` and points to the last adjusted commitment (TimeShare document)
![image](https://user-images.githubusercontent.com/21144013/112225506-884c9980-8bf2-11eb-92b1-93c69bea6e00.png)

In the TimeShare document you can search for the item `time_share_x100`
![image](https://user-images.githubusercontent.com/21144013/112225718-d5c90680-8bf2-11eb-9af2-c42ff0a3d140.png)

**Comment by leonieherma1** [comment]
@gregory-latinier @dappdever @lukegravitt @Gerard097 I did a test run but get the following error in the console when I try to adjust the commitment to 50%:

![image](https://user-images.githubusercontent.com/75991832/114791365-a3b74a00-9d43-11eb-9f5a-003418cf9af9.png)

![image](https://user-images.githubusercontent.com/75991832/114791290-81bdc780-9d43-11eb-8fca-5acef6733406.png)

![image](https://user-images.githubusercontent.com/75991832/114791437-cfd2cb00-9d43-11eb-8044-f83fd91c640a.png)


URL: https://dao-dev.hypha.earth/#/documents/assignment/johnnyhypha1
Test Role: Johnny Hypha
Document: Test Role April 6

**Comment by leonieherma1** [comment]
@josejulio @Gerard097  I still can't adjust my assignment. I followed the following steps:

1. I logged in as Johnny Hypha on https://dao-dev.hypha.earth/#/dashboard
2. I went to "my assignments" and tried to adjust the assignment "test role april 6"
3. I tried to adjust to "50%" and clicked "Yes"
4. I got the message "Transaction processing. Please refresh"
5. There is no refresh button on the side (only history)
6. I clicked on a different screen and back to "my assignments"
7. When I check the assignment it still says "100%" and not "50%" as expected.

<img width="1440" alt="Screenshot 2021-04-19 at 19 29 18" src="https://user-images.githubusercontent.com/75991832/115324834-d4362400-a147-11eb-9c8a-6bcf666dec8a.png">
<img width="1436" alt="Screenshot 2021-04-19 at 19 29 03" src="https://user-images.githubusercontent.com/75991832/115324847-d7311480-a147-11eb-8492-c5e85e91371d.png">
<img width="1440" alt="Screenshot 2021-04-19 at 19 28 35" src="https://user-images.githubusercontent.com/75991832/115324852-da2c0500-a147-11eb-9ef5-2a923648f9ae.png">

**Comment by Gerard097** [comment]
@leonieherma1 Just checked on the backend side and the commitment was actually modified (actually 5 times 🤣 so I need to add a condition to check if the new commitment is different than the previous one or error out)

![image](https://user-images.githubusercontent.com/21144013/115327259-37c64e80-a154-11eb-82ce-34e857f25960.png)

I think this is a matter of the UI to pick the right item for display. @lukegravitt I believe rn it's picking the assignment document item 'time_share_x100'. Could you change that to use 'time_share_x100' from the document pointed by the edge lastimeshare instead? This edge get's updated every time the user changes commitment and should be present on all assignments (even if user hasn't changed his commitment)

**Comment by Gerard097** [comment]
Update: 
I pushed some changes to Test env to fail when trying to set new commitment to the same value of current commitment.

![image](https://user-images.githubusercontent.com/21144013/115340047-a236b900-a16b-11eb-943e-29fc498e346e.png)

**Comment by lukegravitt** [comment]
The client has been updated to show the Adjusted ribbon on the card, and the current and max % on the sidebar.
https://github.com/hypha-dao/dho-web-client/commit/4ad975ec34bb6ff7f22a3a044575ad738dbc5604
