### ISSUE TITLE
Allow user to specify Telos endpoint

### ISSUE THREAD

**Issue by dappdever** [hypha-dao/dho-web-client#204]
The user should be able to specify another endpoint in the UI.  The user should be able to save it in local storage to be used for future sessions.

**Comment by sceenius** [comment]
@dappdever Is this an admin/configuration setting for the entire DHO? Not sure if  a user would understand this.

**Comment by dappdever** [comment]
It would be at the user level. It's an advanced feature. The UI will have default endpoint(s) available also, as it does today, or even allow the user to choose from a drop down list.

The Light Wallet, as an example, comes with a list of endpoints, pings each one on startup, and then uses that one for the user.

**Comment by sceenius** [comment]
Can we implement a heuristic like in the Light Wallet to determine what is
the best (e.g. most responsive) endpoint?

**Comment by gregory-latinier** [comment]
https://github.com/JoinSEEDS/seeds_light_wallet/blob/88b39c95d8f2bb841d34a14f3b5ef979313ab5eb/lib/providers/notifiers/connection_notifier.dart

We can replicate this process.

At the start of the app I ping all the endpoints and pick the fastest.
We can either let the user choose after if he's not OK with the selected network or simply keep this choice hidden from the user
