### ISSUE TITLE
Proposals: v2

### ISSUE THREAD

**Issue by arsenijesavic** [hypha-dao/dho-web-client#2061]
## Design
https://xd.adobe.com/view/b3579d9c-c8b7-43c1-9fe1-a5a11f92e3ad-e604/

## Passing Criteria

- [x] as a DAO user, I want to have the ability to see staging proposals in the list view
- [ ] as a DAO user, I want to have the ability to see the proposal history
- [ ] as a DAO user, I want to have the ability to see the circle name on the proposal card
- [ ] as a DAO user, I want to have the ability to see the archetype name on the proposal card

**Comment by evgenibir** [comment]
@arsenijesavic can you update design link because this link have not proposal card design?
