### ISSUE TITLE
Remove MIN TIME COMMITTED from role

### ISSUE THREAD

**Issue by sceenius** [hypha-dao/dho-web-client#21]
Per Joost -

I am passionate about dropping these two from role definitions as they introduce a whole lot of perverted incentives into the organisation stopping it from adapting where and when needed.
We pay people, not roles, so compensation needs to be linked to people. Minimum time assumes we can predict that noone can make a valuable contribution in less with we simply don't know. Perhaps I can offer lots of value in 5% of my time. And let's honour changing priorities requiring me to shift roles and give other less attention for a while. I really feel this is a big one.

**Comment by sceenius** [comment]
Per Sensemaking Circle meeting today (Game of Hypha), we're good to move this forward. 

The only change is to REMOVE the %MIN COMMITTED from the Role object as well as the program logic to enforce this limit.

**Comment by sceenius** [comment]
The role form in view mode still shows min committed - 
![image](https://user-images.githubusercontent.com/24725582/92274424-355ffe80-eebb-11ea-99ce-eb2329fbd093.png)

**Comment by gregory-latinier** [comment]
Sorry, I missed this view. It's fixed now.
