### ISSUE TITLE
DHO My Profile - My Active Assignments Widget

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#215]
**Summary:**
As a DHO user I would like to see My Active Assignments displayed on my profile page so I can see it on one glance.

**Description:**
URL: https://dho.hypha.earth/#/@accountname

The widget shows a number of cards. When the user clicks on one of the cards he gets to the respective assignment (e.g. the role on the roles page) and can read more info about the role there. 

_Design Question: What happens if there is more cards? arrow / swipe / bigger widget? to be done_

**Acceptance Criteria:**

The following items should be displayed:

Widget
- [ ] Headline "My Active Assignments"
- [ ] All current roles / quests / badges / contributions assigned to the user should be displayed

Cards
- [ ] Icon for type of assignment (quest, badge, role, contribution)
- [ ] Name of the proposal (e.g. Quest for Icon Design)
- [ ] Subheadline with more Info about the assignment
- [ ] Like Button (with number how many likes the proposal has)
- [ ] Comment Button (with number of how many comments the proposal has)
- [ ] Share Icon (Get a link to the respective proposal card) - Possible to integrate with discord? 
- [ ] Show more button / arrow to swipe right and see more cards **(to be done)**
- [ ] Final Card Layout / Info **to be done**

**Ressources:**

Attachement: 
Designs

Responsive Designs:
**To be done** 

<img width="627" alt="Screenshot 2021-03-19 at 16 20 37" src="https://user-images.githubusercontent.com/75991832/111847768-211ba600-88cf-11eb-844f-a3292bb744be.png">

**Comment by leonieherma1** [comment]
@lukegravitt that is the current copy for dynamic commitment: 

_If you adjust your assignment, your % commitment will be immediately reflected on your next claim (no vote is necessary). Multiple adjustments during the same claim period will be included in the calculation._

![image](https://user-images.githubusercontent.com/75991832/120722238-afde9e80-c48c-11eb-904f-0d4ac491da6d.png)

I think it is pretty straight forward, unless @sceenius wants to do another iteration?

**Comment by lukegravitt** [comment]
I think mentioning the term 'prorated' would be helpful -- it should be clear the pay is adjusted only for the portion that where your commitment is reduced
