### ISSUE TITLE
DHO My Profile - My Voting History Widget

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#217]
**Summary:**
As a DHO user I would like to see My Voting History displayed on my profile page so I can see it on one glance.

**Description:**
URL: https://dho.hypha.earth/#/@accountname

The widget shows a list of my past votes. The information displayed is the vote (Yes / No / Abstain) the type of proposal (e.g. contribution, role, quest) and the name (e.g. Design Icons) as well as the date. And a little arrow that the user can click to get to the respective proposal and see more info. 

_Question: What happens when i click on the "more" button? New page, widget folds out to the bottom, scrolls down?_

**Acceptance Criteria:**

The following items should be displayed:

Widget
- [x] Headline "My Voting History" 
- [ ] List of all proposals that the user participated in the past with his vote (or abstain)

List Item
- [x] You "voted Yes", "voted No", "abstained" on the "contribution", "role", "quest", "badge""name of proposal"
- [x] Date when the user voted e.g. August 1, 2020 
- [ ] Arrow that takes me to the respective proposal / role / quest, etc.. to see more info
- [ ] Show more button / arrow to swipe right and see more cards **(to be done)**
- [ ] Final Card Layout / Info **to be done**

**Ressources:**

Attachement: 
Designs

Responsive Designs:
**To be done** 

<img width="647" alt="Screenshot 2021-03-19 at 16 27 30" src="https://user-images.githubusercontent.com/75991832/111848162-0d247400-88d0-11eb-9cb6-4fdb4a528f77.png">

**Comment by lukegravitt** [comment]
We need to know what to do with the 'more' button here too. As I said in the other issue, votes are transactions, so maybe this links to the same page, except with a 'vote' filter? Maybe our transaction list can be sorted, filtered, etc.
