### ISSUE TITLE
Emergency message banner

### ISSUE THREAD

**Issue by sceenius** [hypha-dao/dho-web-client#22]
On top of the screen, add an emergency banner with text pulled in from a resource with the option to enable and disable the banner. 

- [ ] Quasar - https://quasar.dev/vue-components/banner - with standard colors for green, blue, yellow and red
- [ ] add activity to left side bar called "Update Banner", visible to Admins only (Max to create this group)
- [ ] Update Banner will open a default dialog box with 2 fields (message text input and level dropdown) and 3 buttons [cancel], [add] and [delete] (in red)
- [ ] for level dropdown, use "success" (green), "info" (blue), "warning" (yellow) and "danger" (red)
- [ ] banner is displayed on top, centered text with [DISMISS] button

**Comment by dappdever** [comment]
Do you think we should have a ```level``` and text message?  The level would indicate whether the color of the dialog or banner should be green, yellow, or red.  For example, it'd be cool to use green for release notes, red for some type of outage, and yellow for something in between.  @sceenius

**Comment by sceenius** [comment]
Love it, https://quasar.dev/vue-components/banner

**Comment by gregory-latinier** [comment]
Before putting this in the todo list I need more info:
What is the requested design ? Colors, action buttons, etc
From what part of the smartcontract should I pull the message ?

**Comment by sceenius** [comment]
@gregory-latinier Use the standard red, yellow and green from Quasar - https://quasar.dev/vue-components/banner - and use the single line message with the [dismiss] button at the end. 

As to the message, as @dappdever said level and message, not sure where we can set this? We don't have an admin section yet. Maybe set externally like we do with the Enroller?

**Comment by dappdever** [comment]
> @gregory-latinier Use the standard red, yellow and green from Quasar - https://quasar.dev/vue-components/banner - and use the single line message with the [dismiss] button at the end.
> 
> As to the message, as @dappdever said level and message, not sure where we can set this? We don't have an admin section yet. Maybe set externally like we do with the Enroller?

I can add this to the smart contract.

**Comment by gregory-latinier** [comment]
I need the smartcontract information in order to start this task. Thanks

**Comment by dappdever** [comment]
@gregory-latinier I deployed two additional actions to the testnet.  These actions are invoked as follows:

```
      ACTION setalert (const name &level, const string &content);
      ACTION remalert ();
```

```level``` is a ```name``` value so must follow the same rules as an account name, and content can be any string.

These set and remove the ```alert_level``` key on the config.names array, and ```alert_content``` on the config.strings array.

You can check the existence of either/both to determine whether to include a dialog banner with the content.

**Comment by sceenius** [comment]
From @gregory-latinier 
![image](https://user-images.githubusercontent.com/24725582/92342564-32b60280-f08f-11ea-827f-2c830b14244c.png)

**Comment by sceenius** [comment]
@gregory-latinier Banner needs to be at the top of the screen for full screen width but can be min height to show the [dismiss] button.

**Comment by gregory-latinier** [comment]
Does the banner sit on top on the menu and profile icons like an overlay or does it push everything down a bit ?
When a user click "Dismiss" what happen ?
1. The banner is never shown again until a new message is updated in the smartcontract
or
2. The banner is hidden for the current session but comes back if the user refresh the page

**Comment by sceenius** [comment]
Yes, on top pushing down a bit (see current Discord banner below). When clicking on [dismiss] the banner is hidden for the current session only. 
![image](https://user-images.githubusercontent.com/24725582/92390552-1777e100-f0e9-11ea-9f0f-ac7078426059.png)

**Comment by sceenius** [comment]
Add some top and bottom margin, same as with the bottom message - 
![image](https://user-images.githubusercontent.com/24725582/92493604-b290b980-f1c2-11ea-93b8-a19c666dad65.png)

**Comment by sceenius** [comment]
Add an icon for the 4 types before the message (same row, see spinner above) - 

success - https://fontawesome.com/icons/check-square?style=solid
info - https://fontawesome.com/icons/info-circle?style=solid
warning - https://fontawesome.com/icons/exclamation-triangle?style=solid
danger - https://fontawesome.com/icons/radiation?style=solid

**Comment by sceenius** [comment]
Can you change the yellow to the orange - https://quasar.dev/vue-components/banner - #FF9800

**Comment by gregory-latinier** [comment]
Too late the issue was validated and is now shipped.
It will be done on another issue for another release
