### ISSUE TITLE
Avoid duplicate account creation

### ISSUE THREAD

**Issue by sceenius** [hypha-dao/dho-web-client#237]
Purpose:

Some users are creating a second SEEDS/TELOS account when they sign up with the DHO. Let's add extra text to avoid this confusion in the registration form (see below).

From:
---------------------------------
Register Account
Please use the guided form to create a new SEEDS account and membership registration.
Already have an account? Login here.
Just visiting? Continue as guest.
---------------------------------

To:
---------------------------------
Register Account
Please use the guided form to create a new SEEDS account and membership registration. Please note that you can use your existing SEEDS account (e.g. from the Passport) to login to the DHO (use the link below to sign in).
Already have an account? Login here.
Just visiting? Continue as guest.
---------------------------------

![image](https://user-images.githubusercontent.com/24725582/104128004-225eae80-5333-11eb-9419-dfbcd346a87d.png)

**Comment by Rieki7** [comment]
"Just grab your "Private Key" from the backup key section of the SEEDS Passport or Light Wallet to login!
