### ISSUE TITLE
DEV DHO - Assignments error message: "the proposal would start before the endorsement"

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#254]
**Summary:**

When I try to "propose" my assignment (for a role or badge) I get the following error message:
"The proposal would start before the endorsement. Please change the start cycle". 

**Scenario**
- Log in to https://dao-dev.hypha.earth/#/roles and navigate to 'Roles' section.
- Apply to a role 
- Chose a start date: Only Feb 5 and Feb 6 show up as possible start dates (no other dates are clickable)
- Hit save
- Click "propose" on the card
- See error message

**Expected Result**
The assignment should get proposed

**Actual Result**
The user get's an error message and the assignment doesn't get published for voting

**Other Descriptions & Screenshots**

<img width="1149" alt="Screenshot 2021-02-04 at 18 10 53" src="https://user-images.githubusercontent.com/75991832/106966998-5fd91080-6714-11eb-8fef-2ea96beebb20.png">
<img width="648" alt="Screen_Shot_2021-02-04_at_5 00 04_PM" src="https://user-images.githubusercontent.com/75991832/106966944-433cd880-6714-11eb-91d2-fea4ce63ce19.png">

**Comment by sceenius** [comment]
This is happening for Badges

**Comment by leonieherma1** [comment]
> This is happening for Badges

And roles assignments as well right?

**Comment by sceenius** [comment]
Yes

**Comment by gregory-latinier** [comment]
The reason why we added this a while ago was to avoid having documents start before their validated votes.
Should I remove this rule everywhere ?

**Comment by leonieherma1** [comment]
> The reason why we added this a while ago was to avoid having documents start before their validated votes.
> Should I remove this rule everywhere ?

If that was the reason we should probably keep it @sceenius? But the problem is that the user fills everything in, and only gets the negative feedback when trying to propose. I suggest:

1. Disable (grey out) the dates that are before the vote. (Are we going to have the voting time increased in the "hell yeah vote"? - Then it could be complicated)
2. Give an error message right when trying to pick it in the sidebar / overlay when the users tries to save the document.

**Comment by sceenius** [comment]
Let's keep it. This is also related to the missing table for lunar cycles (see other issue - https://github.com/hypha-dao/dho-web-client/issues/255)
