### ISSUE TITLE
DEV DHO - Badges should not allowed to be saved without entering the max cycles restriction

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#255]
**Summary:**

When a user creates a new badge, he shouldn't be able to save the draft when the field "max cycles" is empty. 

**Scenario**
- Log in to https://dao-dev.hypha.earth/#/documents-proposal/badge and navigate to 'Badges' section.
- Create a badge
- Leave the "max cycles" empty
- Hit save
- Click "propose" on the card
- See error message "Transaction error, please check the console"
- When you fill in the field "max cycles" the proposal works

**Expected Result**
The user should not be able to save the badge draft without getting a warning to fill in the "max cycles" field

**Actual Result**
The user doesn't get an error message when saving the draft. He gets the error message later in the console.

**Other Descriptions & Screenshots**
<img width="398" alt="Screenshot 2021-02-04 at 18 15 52" src="https://user-images.githubusercontent.com/75991832/106967530-53a18300-6715-11eb-94b8-c498ee196fc8.png">
<img width="1440" alt="Screenshot 2021-02-04 at 18 16 07" src="https://user-images.githubusercontent.com/75991832/106967536-57350a00-6715-11eb-8890-dd4796422a22.png">

**Comment by sceenius** [comment]
[dao-dev.hypha.earth-1612476786402.log](https://github.com/hypha-dao/dho-web-client/files/5929294/dao-dev.hypha.earth-1612476786402.log)

**Comment by sceenius** [comment]
Max cycles error is fixed, but the calendar shows no entries to select from.
