### ISSUE TITLE
DEV DHO - small UI Design bugs

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#256]
**Summary:**
There is a small number of design errors, that can probably be easily fixed.

**1. Alignments of Cards**
![alignment of cards](https://user-images.githubusercontent.com/75991832/106967728-a713d100-6715-11eb-8ce2-cf7ddfb35e97.png)

**2. Position of arrows**
![alignment icons](https://user-images.githubusercontent.com/75991832/106967820-c579cc80-6715-11eb-9cb3-9cc1d4386826.png)

**3. Alignment of field and copy**
![alignment field and copy](https://user-images.githubusercontent.com/75991832/106967886-df1b1400-6715-11eb-96d8-8500e6877616.png)

**4. Sidebar (e.g. edit profile, create assignment, etc...) cut off on mobile (Pixel 2)**
https://dao-dev.hypha.earth/#/roles - click "apply" 
<img width="490" alt="Screenshot 2021-02-04 at 18 23 21" src="https://user-images.githubusercontent.com/75991832/106968073-2ef9db00-6716-11eb-88f1-392d55613eb9.png">

**Comment by sceenius** [comment]
Icon missing in badge-assignment

![image](https://user-images.githubusercontent.com/24725582/106972427-d713a200-671e-11eb-90da-b08f2ee514fd.png)

**Comment by gregory-latinier** [comment]
2. there is nothing I can do it's built in
3. Alignment of what ? Both are split evenly and on the top

I have the icon 
![image](https://user-images.githubusercontent.com/13222767/107129259-76be6500-68c4-11eb-8aaf-86ea7b2eb790.png)

**Comment by sceenius** [comment]
@leonieherma1 I'm with @gregory-latinier - this would require a more serious redesign, maybe do this with the updated UI/UX. Pls approve if that is ok,

**Comment by leonieherma1** [comment]
> @leonieherma1 I'm with @gregory-latinier - this would require a more serious redesign, maybe do this with the updated UI/UX. Pls approve if that is ok,

@sceenius @gregory-latinier yes that makes sense. I just thought maybe it is an easy css fix to make it look good. But I wanted to redesign that anyway (maybe have an overlay instead of the sidebar). So happy to create a design and update this later.
