### ISSUE TITLE
DEV DHO - Connection with site lost

### ISSUE THREAD

**Issue by sceenius** [hypha-dao/dho-web-client#257]
The app is not starting and shows a blank screen (also with certificate error, but this is not related)

When switching to private/incognito browsing without a secure connection, the app is starting. 

Certificate error:
Failed to load resource: net::ERR_CERT_DATE_INVALID

**Comment by sebastianmontero** [comment]
Hi @sceenius, I'm working on this, waiting for Rieki to provide access to NameCheap.

**Comment by sebastianmontero** [comment]
Hi @sceenius, issue should be solved, sorry for the delay, I was just given access to NameCheap

**Comment by sceenius** [comment]
Perfect, thank you!
