### ISSUE TITLE
Recast of the salary token based on [EDIT] of Assignment object

### ISSUE THREAD

**Issue by sceenius** [hypha-dao/dho-web-client#27]
Problem:

Any edits for %Committed, %Deferred or %HUSD are not updated in the contract. Reason: We did not expect % values nor  assets (here salary tokens) being submitted to the contract from the UI.  

Solution:
The smart contract accepts %values and recalculates (termed: recast) the salary tokens before writing it back to the blockchain (via merge). To avoid any surprise, the new salary will be computed and displayed on the UI before proposing the change. 

Options:
1) The new salary is computed based on the previous tokens (no side effect, possible b/c we removed Liquid Seeds)
2) The new salary is computed based on the current market value (see side effect below)

Side Effect:
Any change in the %value will trigger a recalculation of the salary, which is likely to change since the Assignment started. This will cause confusion, since the salary can be negatively impacted (e.g. you earn less Seeds for the USD equivalent). To avoid this, we show the new salary on the UI (as we do now), but via a smart contract function

**Comment by dappdever** [comment]
Adding this screenshot and notes from Discord: 
![image](https://user-images.githubusercontent.com/32852271/90178475-f89c5e00-dd79-11ea-9a16-927c74b8e753.png)

On the left is the current assignment agreement/document/object and on the right is the proposed doc that will be merged into the existing one if/when the proposal passes.

**Comment by sceenius** [comment]
From DISCORD - 

max-gToday at 3:39 PM
NOTE: calling the token recast is only applicable to the 11 proposals that were created before I deployed the hotfix yesterday.  That hotfix included the change to recast token quantities when the edit proposal is created, so new edit proposals should be fine.

As we discussed, this dynamic recast approach is how users are currently expecting this to work, but has unintended and likely hard-to-track-down consequences down the road.  It also prevents users from proposing direct edits to token quantities. We discussed a way to have a transparent 'de-coupling' of the token calculation helpers.  The 'helper' can isolate the logic into a service that could be called from multiple clients. I will work on this more as part of the refactor and move to logic to a service to be easily queried. 

In the meantime, should I go ahead and call this dynamic recast on the 11 open edit assignment proposals?

Joachim StrohToday at 3:32 PM
Yes, please from my end.
Can you also look at option 1 as a viable alternative to recasting based on existing assets vs. calculating new assets. That has no unintended consequences, but I doon't know if this is possible. I think yes after removing Liquid Seeds.
Re Price increase. We can hold off on doing it manually until we sort this out. We haven't made the announcement yet.
(from Rieki, this gives us a bit more time to think it through)
Sorry, I meant option 1

max-gToday at 3:39 PM
@Joachim Stroh - yes, option #2, short-term is implemented.  The part about moving the logic to a service can happen in the coming days/weeks.
oh, hold on :slight_smile:
I'm not following option 1: 
The new salary is computed based on the previous tokens (no side effect, possible b/c we removed Liquid Seeds)

Joachim StrohToday at 3:40 PM
ok, so you take what we currently have as a token salary, then use the multipliers from the %values to adjust it
e.g. you change your %deferred from 50% to 100% ----> take the current Def Seeds and incr by 50% (+bonus) and decr the HUSD by 50%

Nikolaus HegerToday at 3:42 PM
If we remove liquid seeds it should be “as if” we set liquid seeds % to 0

A bit tricky because normally that would increase husd but we want to keep husd fixed and adjust the deferred percentage so the husd stay the same the liquid seeds go to 0 and the deferred seeds increase accordingly
max-gToday at 3:42 PM
That feels more complex to me because there are more permutations

Joachim StrohToday at 3:43 PM
Yes, but -------> no recalc based on market rate!

Nikolaus HegerToday at 3:43 PM
Or just transfer liquid to the escrow with the deferred multiplier instead of paying them out and phased them out on the ux

Joachim StrohToday at 3:44 PM
Yes, that's secondary to me, first question is a math question whether this is a bijective function (works both ways)

max-gToday at 3:44 PM
Here are the formulas currently implemented, under "New" tabs: https://docs.google.com/spreadsheets/d/1Njp-kksptrVi7kWEAFk14zx55yw08G37mb1JurWwH7k/edit#gid=482437161
Google Docs
Hypha Financial Calcs
Salaries


Globals
Moon Phase/ Year,2.03%
Seeds per USD,90.9091
USD per SEED, $ 0.0110000 ,346.4476386
Deferral Rewards
Hypha / $1,0.6
Seeds Bonus,30%
Test 1,Test 2,Test 3,Test 4,Test 5,Test 6,Test 7,Test 8,Test 9,Test 10,Test 11,Test 11
Role Test Num,1,2,5,3,4,4,4,4,4,4,x,x
R...

Yes, that's secondary to me, first question is a math question whether this is a bijective function (works both ways)
@Joachim Stroh it's definitely possible, but a bit of algebra. Is there an advantage to this option?
I guess it normalizes to control for changes in calcs from their original assignment proposal date.

Joachim StrohToday at 3:47 PM
Yes! Think about it this way - you've been in your assignment for a year, and now you change your commitment from 100% to 95% - your ENTIRE salary is recalculated and you will (potentially) earn a lot LESS because of this (small) change.

max-gToday at 3:47 PM
And the change is coming from the price of Seeds, right?

Joachim StrohToday at 3:48 PM
Precisely

max-gToday at 3:54 PM
Currently, we are calculating the rate for Seeds at the time of assignment proposal creation. Should we instead be calculating this each time a claim is made on a pay period?  If not, I think it should be recast at time of edit.  If it isn't recast on either of those events, then we could lock that rate in for life by continuing extensions.
My hunch is that the intended policy is to recalculate it frequently, but I could be wrong. It might be unspecified

Joachim StrohToday at 3:56 PM
I think we should lock this rate in, which also makes the recast a lot easier (no math needed). But let's simmer both options for a while.

max-gToday at 3:57 PM
Locked in per assignment or per member?

Joachim StrohToday at 3:58 PM
Assignment. As soon as you apply for another role, the current market value should apply.
Let me think about a better analogy for this.
Say, you're an expat and get paid in Indonesian rupiah, but never ever use the rupiah and instead exchange it for USD. This is akin to getting SEEDS and the echange rate is .. changing. You would not expect to get paid more or less Rupiah....

max-gToday at 4:02 PM
Good point
I agree
The agreement is locked at that point and the exchange rate shouldn't matter. :thumbsup:

Joachim StrohToday at 4:03 PM
Yes

**Comment by dappdever** [comment]
This has been deployed

**Comment by sceenius** [comment]
![DHO RECAST (5)](https://user-images.githubusercontent.com/24725582/91748330-d41fee80-eb8d-11ea-8c00-2db0c14838e3.png)
