### ISSUE TITLE
[R] The amount of "USD EQUIV" is not showing on role-assignment

### ISSUE THREAD

**Issue by sceenius** [hypha-dao/dho-web-client#273]
Expected: Show the amount B1-7 on the form
Actual: No data is shown

![image](https://user-images.githubusercontent.com/24725582/107976496-a6860080-6f87-11eb-83b6-e7fa3315932d.png)

**Comment by gregory-latinier** [comment]
Where exactly does it not show?
![image](https://user-images.githubusercontent.com/13222767/107989282-44062200-6fd2-11eb-9768-1e7d018e94ff.png)

**Comment by sceenius** [comment]
Sorry, my comment got lost somewhere, check the role-assignment for "ROLECAP TEST", there is not USD EQUIV in the header.

**Comment by gregory-latinier** [comment]
OK it was not on role assignment but on the role assignment proposals :)
