### ISSUE TITLE
[R] Dates in payouts table in wallet showing created date

### ISSUE THREAD

**Issue by sceenius** [hypha-dao/dho-web-client#277]
Expected: Showing date of the transaction
Actual: Showing migration date

![image](https://user-images.githubusercontent.com/24725582/107977562-4f812b00-6f89-11eb-8bc3-dd9ac4a80d53.png)

**Comment by sceenius** [comment]
This looks like this - no date.

![image](https://user-images.githubusercontent.com/24725582/107998213-9afbff00-6fb2-11eb-8dbb-6e01fb3b34ee.png)

**Comment by gregory-latinier** [comment]
Apparently the staging data doesn't have the payment_date attribute.
On my end I'll consider this fixed for production
