### ISSUE TITLE
Badge assignment is returned in the query for role assignments (claim button on badges)

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#328]

**Comment by gregory-latinier** [comment]
it's not the actual issue

the problem is that a badge assignment is returned in the query for role assignments

**Comment by sebastianmontero** [comment]
@gregory-latinier do you have an example where this is happening?

**Comment by leonieherma1** [comment]
> @gregory-latinier do you have an example where this is happening?

@sceenius said it happened to him this morning on one of his badges

**Comment by sebastianmontero** [comment]
@gregory-latinier are you using the following query? It does not return any badges for joachimstroh

`query assignments($first:int, $offset: int, $user: string) {
    var(func: has(assignment)){
      assignedto as assignment @cascade{
        created_date
        content_groups {
          contents  @filter(eq(value,$user) and eq(label, "assignee")){
            label
            value
          }
        }
      }
    }
    assignments as var(func: uid(assignedto))@cascade{
      content_groups {
          contents  @filter(eq(value,"assignment") and eq(label, "type")){
            label
            value
          }
        }
    }
    assignments(func: uid(assignments), orderdesc:created_date, first: $first, offset: $offset){
      hash
      content_groups{
        expand(_all_){
          expand(_all_)
        }
      }
    }
  }`

**Comment by gregory-latinier** [comment]
Yep https://github.com/hypha-dao/dho-web-client/blob/develop/src/store/assignments/actions.js#L96

**Comment by gregory-latinier** [comment]
Ok I found what he did, it's in the global assignments list
