### ISSUE TITLE
Claim error

### ISSUE THREAD

**Issue by sceenius** [hypha-dao/dho-web-client#334]
Expected: Claim payment on role-assignment card
Actual: cannot claim my period (user joachimstroh), see transaction error below

claimnextper
assertion failure with message: edge does not exist: from fa1c3113c15d53bc030fd3e2f1e8cd8074dafda2f06a977279c2a4924dfce0c3 with edge name of badge

```User: joachimstroh
Action: 0
Contract: dao.hypha
Method: claimnextper
Data: {"assignment_hash":"E02DE6CC4757DAA785ED499BC865621FFDD93F97BC125B3D8E6F80AE043F4772"}
```

**Comment by leonieherma1** [comment]
![Uploading image.png…]()

**Comment by lukegravitt** [comment]
As discussed in standup, quick fix involves 2 steps:

1. Update hashes in the assignment documents that are orphaned by roles/proposal hash changes to reattach them
2. Add code when roles/proposal hashes change to update the hash set in the assignment.

Longer term, transition entirely to using edges, which first requires this: https://github.com/hypha-dao/dao-contracts/issues/61

**Comment by dappdever** [comment]
I have added the code here, still working on it
https://github.com/hypha-dao/daoctl/blob/fix/role-hash/cmd/fix.go#L40

**Comment by sceenius** [comment]
From Max: 
I believe that I fixed your claim pay problem, and I claimed a few periods but you have several more to claim I believe. Can you try and check amounts?

From Joachim:
1 Claim works and correctly added 3 new transactions to the table
2 All tokens were added and seem in line except for HYPHA (higher than in my calc here [1], could be an outdated schedule in my link below)
3 Diffs as follows:
+404 HYPHA
+8,584 HVOICE
+770 HUSD

[1] https://docs.google.com/spreadsheets/d/1xngcdfqhoqE9uCUURybUDU5pCYrI3UjY6aIgf1auD38/edit#gid=1791166910

**Comment by dappdever** [comment]
We should go through this on one of the calls with @Gerard097 and @sceenius to walk through the amounts
