### ISSUE TITLE
Change link to help documentation

### ISSUE THREAD

**Issue by sceenius** [hypha-dao/dho-web-client#34]
New link: https://notepad.hypha.earth/5dC66nNXRVGpb1aTHaRJXw (from top right rescue ring icon)

**Comment by gregory-latinier** [comment]
Why not simply change the content of the existing one ?
Create a new document, copy paste the existing data for archive.
Override the existing content with the new data.

It avoid unnecessary modification in the code

**Comment by sceenius** [comment]
It's on the hypha,earth domain now, moving out of the diglife.coop domain. All future changes are happening in the doc of course.
