### ISSUE TITLE
Register new account: Forbidden

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#352]
Summary:

New user (massimohypha) cannot register for the DHO because of the "Forbidden" error message.

https://dho.hypha.earth/#/register

Expected Result
As a new user I should be able to register in the DHO without getting the error "forbidden" (when filling in all forms correctly - no error on form fill ins are shown)

Actual Result
As a new user I try to register and get a "forbidden" error.

Other Descriptions & Screenshots
Please find attached the screenshots of the form and the console.

https://cdn.discordapp.com/attachments/826471199890604082/829995663634202634/signup.jpg
https://cdn.discordapp.com/attachments/826471199890604082/830083007259869194/signup_errors.jpg

**Comment by gregory-latinier** [comment]
@dappdever 

The registration API respond with the forbidden message without any additional information

**Comment by leonieherma1** [comment]
@Gerard097 I still get the forbidden error on the dev dao:

![image](https://user-images.githubusercontent.com/75991832/115076355-af2c8180-9eb9-11eb-8f00-f4ff366e968d.png)
