### ISSUE TITLE
Dev DHO error: Proposal would start before endorsement

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#354]
**URL:** https://dao-dev.hypha.earth/#/documents-proposal/assignment

**Summary:**
As a dev DHO user I should be able to propose assignments without getting errors. 

**Expected Result**
As Johnny Hypha should be able to propose my assignment (apply for the role "test role april 12" by Johnson D. Zimmermann) in the dev DHO.

**Actual Result**
When trying to post an assignment with the start date april 17 I get the following error: "The proposal would start before the endorsement. Please change the start cycle."

Other Descriptions & Screenshots

![image](https://user-images.githubusercontent.com/75991832/114611692-8bb9ca80-9c5e-11eb-92f9-66d4e16b6429.png)
![image](https://user-images.githubusercontent.com/75991832/114611846-ad1ab680-9c5e-11eb-8e66-887573115651.png)

**Comment by lukegravitt** [comment]
This should be resolved on test via this change: https://github.com/hypha-dao/dho-web-client/commit/ef9838b1e19be8a27d943b915be8823fcd023668
