### ISSUE TITLE
Extend button missing

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#365]
![image](https://user-images.githubusercontent.com/75991832/115259090-d0c27e80-a0ee-11eb-969a-27232c22e629.png)

**Comment by lukegravitt** [comment]
This should be resolved on test by this commit: https://github.com/hypha-dao/dho-web-client/commit/178ef93c447106a71dc53bba7a1c96e80c9c591c

**Comment by leonieherma1** [comment]
@lukegravitt just for your info, currrently the extend button shows up on dev dao too early (my assignment should go for 6 more periods)

https://dao-dev.hypha.earth/#/documents/assignment/johnnyhypha1

![image](https://user-images.githubusercontent.com/75991832/115768631-cc54ca80-a367-11eb-836d-8836dd85426c.png)

**Comment by lukegravitt** [comment]
It's 15 days right now--- I could change it to 2 voting periods (that would be 2 days on test, 14 days on live) if that makes more sense.

**Comment by leonieherma1** [comment]
> It's 15 days right now--- I could change it to 2 voting periods (that would be 2 days on test, 14 days on live) if that makes more sense.

yes please, sounds good. would make testing easier

**Comment by lukegravitt** [comment]
This particular issue is resolved now.
