### ISSUE TITLE
Release Native Ballots, Dynamic Commitments & Bugs

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#374]
Summary:
As a DHO dev team we want to release the following stories / bugs combined:

https://github.com/hypha-dao/eosio-contracts/issues/26
#365 
#352 
#203
#334 ?
#373 ?

Action Plan:
- [x] Monday (April 26): Banner Notification in DHO: "Creating new proposals for the DHO is disabled from Apr 30 - May 7" @sceenius 
- [x] Monday (April 26); DHO Support & Discord: 

**Important Announcement**
We will disable creation of new proposals from April 30 through May 7 due to maintenance and upgrade work. You will be able to vote on existing proposals during this time, but you cannot create any new proposal.  Please ensure that you submit any new proposal before April 29 so they can be presented and voted on at the next Tuesday DHOsday call on May 4.

- [x] Tuesday (April 27): Notify organisation members in during the DHOsday meeting: Deadline to put up new proposals for next Tuesday DHOsday (May 4) is Thursday (April 29)
- [x] Thursday (April 29): ! Friday Midnight UTC (= @lukegravitt 5pm)! Disable "old proposals" (remove create new proposal + buttons / grey out?)
- [x] - [ ] Monday (May 3): Collective Testing @lukegravitt @leonieherma1 @augusto @sceenius @juliolrmonteiro @Gerard097 
- [x] Tuesday (May 4): Notify organisation members in during the DHOsday meeting: Posting proposals will be possible again from Friday May 7
- [ ] Thursday 12pm UTC (May 6) !Thursday afternoon @lukegravitt ! - Friday release native ballots, bugs & dynamic commitments
- [ ] -Friday (May 7): Collective Testing / Standby for feedback & bugfixing
- [ ] Friday (May 7): Pop Up Notification in DHO: Posting proposals is possible again
- [ ] Friday (May 7): Discord: Explain new features (short video of dynamic commitments), native ballots & bug fixing

Did I miss anything @dappdever @lukegravitt @sceenius?

**Comment by dappdever** [comment]
I looked into the mem2 assignment and pay claim.  The first period is pro-rated based on the elapsed time in that period, so it is less than all subsequent period claims, generally. Besides that, each period that is claimed is the same amount, which matches the assignment.

Here's an screenshot of the assignment.  
@Gerard097 I believe the assignment document should have an edge named "start" that points to the first period. Has then been replaced with the inittimeshare and currenttimeshare edges? 

![image](https://user-images.githubusercontent.com/32852271/116000746-70847e80-a5bf-11eb-8ac7-727d75320ace.png)

Here is a screenshot of the timeshare documents. On 2021-04-23 22:19:53, the user changed it from 100% commitment to 40% commitment, and the new timeshare document was appended to the prior one. 

![image](https://user-images.githubusercontent.com/32852271/116000790-a3c70d80-a5bf-11eb-8a10-affa5565a9ba.png)

I think the currenttimeshare edge is still pointing to the 100% commitment document. @Gerard097 Can you take a look? Should the edge be updated to point to the 40% document?
![image](https://user-images.githubusercontent.com/32852271/116001062-b55ce500-a5c0-11eb-89b4-961970843ec8.png)

**Comment by Gerard097** [comment]
> I looked into the mem2 assignment and pay claim. The first period is pro-rated based on the elapsed time in that period, so it is less than all subsequent period claims, generally. Besides that, each period that is claimed is the same amount, which matches the assignment.
> 
> Here's an screenshot of the assignment.
> @Gerard097 I believe the assignment document should have an edge named "start" that points to the first period. Has then been replaced with the inittimeshare and currenttimeshare edges?
> 
> ![image](https://user-images.githubusercontent.com/32852271/116000746-70847e80-a5bf-11eb-8ac7-727d75320ace.png)
> 
> Here is a screenshot of the timeshare documents. On 2021-04-23 22:19:53, the user changed it from 100% commitment to 40% commitment, and the new timeshare document was appended to the prior one.
> 
> ![image](https://user-images.githubusercontent.com/32852271/116000790-a3c70d80-a5bf-11eb-8a10-affa5565a9ba.png)
> 
> I think the currenttimeshare edge is still pointing to the 100% commitment document. @Gerard097 Can you take a look? Should the edge be updated to point to the 40% document?
> ![image](https://user-images.githubusercontent.com/32852271/116001062-b55ce500-a5c0-11eb-89b4-961970843ec8.png)

@dappdever I went through the file history of `assignment_proposal.cpp` and it seems like the `start` edge from assignment to first period was never implemented after migration to Document graph. I noticed it a while ago but I assumed you did it for some reason :p (I should have asked tbh). I'll push a small PR with it.

**Comment by dappdever** [comment]
I audited/tested the mem2 test from @leonieherma1 spreadsheet.  It looks correct to me. See screenshot here: 
![image](https://user-images.githubusercontent.com/32852271/116109811-249b0d80-a683-11eb-9bed-cafc7c9a5200.png)
