### ISSUE TITLE
Add pending transaction for HUSD and SEEDS redemption

### ISSUE THREAD

**Issue by sceenius** [hypha-dao/dho-web-client#403]
Issue: After submitting a request for redemption of HUSD or buying SEEDS there is no indicator of a pending transaction.
Solution: Add transaction to transaction table view with a pending state, followed by a completed state once done.

**Comment by lukegravitt** [comment]
In the old version, you could only redeem in the wallet page and the transaction would show up there immediately -- maybe just need to redirect there when a redemption is done in the profile page?
