### ISSUE TITLE
Use query that filters on timestamp where period.details.start_time value is in the future

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#406]
Frontend story for #388

**Comment by lukegravitt** [comment]
{ 
  periods as var(func: type(Document)) @cascade {
    content_groups {
      contents @filter(eq(label, "type") and eq(value, "period")) {}
    }
  }
    
  filterByDate as var(func: uid(periods)) @cascade {
    content_groups {
      contents @filter(eq(label, "start_time") and gt(time_value, "2021-06-01T00:00:00.291Z") and lt(time_value, "2021-06-05T23:59:59.291Z")) {}
    }
  }
    
  periods(func: uid(filterByDate), first: 30) {
    content_groups(orderasc: content_group_sequence, first: 1) {
      contents(orderasc: content_sequence) {
        expand(_all_)
      }
    }
  }
}
