### ISSUE TITLE
Add Matomo analytics to client

### ISSUE THREAD

**Issue by lukegravitt** [hypha-dao/dho-web-client#410]
```html
<!-- Matomo -->
<script type="text/javascript">
  var _paq = window._paq = window._paq || [];
  /* tracker methods like "setCustomDimension" should be called before "trackPageView" */
  _paq.push(['trackPageView']);
  _paq.push(['enableLinkTracking']);
  (function() {
    var u="https://track.hypha.earth/";
    _paq.push(['setTrackerUrl', u+'matomo.php']);
    _paq.push(['setSiteId', '1']);
    var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
    g.type='text/javascript'; g.async=true; g.src=u+'matomo.js'; s.parentNode.insertBefore(g,s);
  })();
</script>
<!-- End Matomo Code -->
```

**Comment by lukegravitt** [comment]
@sceenius Can you check if you are getting some data now? (from localhost probably) as I added this and its giving me success responses now. Do we have details for viewing the data in discord somewhere?

**Comment by sceenius** [comment]
This is here https://track.hypha.earth/ did you login with Cloudron? I prob need to give you edotor access. 

What I see:
![image](https://user-images.githubusercontent.com/24725582/119728547-982a6900-be41-11eb-8d9d-f9ef3e119cce.png)

**Comment by lukegravitt** [comment]
Okay good, looks like it's working, but I'll followup to confirm details after its on test server a bit.
