### ISSUE TITLE
Add memo field to the profile section for the EOS wallet

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#422]
**Summary:**
As a user I would like to be able to add the "Memo" for my EOS Wallet in my profile so that I can get paid in EOS.

1 thing we'll need in the profile section for EOS wallet is the "Memo" as the UX is that people are setting up an exchange account and accepting EOS to it (which requires the memo field). 

**Acceptance Criteria:**
- [ ] Add Memo Field to the profile section right below the EOS field
- [ ] Highlight Memo field and add following text: EOS account (Preferred payment method)

**Ressources:**

Links to other issues
![image](https://user-images.githubusercontent.com/75991832/119896227-fe73c200-befb-11eb-90b5-ade34e8445d2.png)

**Comment by lukegravitt** [comment]
Why is this the responsibility of the end user? The backend should just choose a reasonable memo.

**Comment by Gerard097** [comment]
Because it is something required by some exchanges, it's not like just a descriptive message on the transaction but necesary info to send the tokens to the right wallet i.e. 
![image](https://user-images.githubusercontent.com/21144013/120016400-2cafdb00-bfaa-11eb-92a8-04aee5d702d8.png)

**Comment by leonieherma1** [comment]
@Gerard097 if you need to check in with the treasurers, I think Nick (nikolaus#6776) , Joachim or Alex (Alex Prate
#3418) are the right people to ask.
