### ISSUE TITLE
HVOICE showing as 2x USD amount for Contribution proposals

### ISSUE THREAD

**Issue by dappdever** [hypha-dao/dho-web-client#43]
The HVOICE for one-time contributions is being calculated as 2x USD but should be calculated as 1x USD.  For example, proposal #306 has an HVOICE amount of 29,230 on chain but shows as 58,460 in the client.

![image](https://user-images.githubusercontent.com/32852271/91183379-653c2480-e6b9-11ea-92a7-cb8792c79052.png)

![image](https://user-images.githubusercontent.com/32852271/91183403-6cfbc900-e6b9-11ea-94c1-c38d88a23966.png)

**Comment by sceenius** [comment]
@gregory-latinier Can we confirm that this has been implemented and close?

**Comment by sceenius** [comment]
@gregory-latinier The wallet view shows HVOICE as well, is that coming from the smart contract or do you compute that? If so, is the calc the same as with the form?

**Comment by sceenius** [comment]
@gregory-latinier I see the existing contributions showing HVOICE as 2x - is that a value you store with the proposal? I assumed this is calc in realtime. Also, as the price of SEEDS changes, these values would change too.

**Comment by gregory-latinier** [comment]
Fixed with the new salary display

**Comment by gregory-latinier** [comment]
> @gregory-latinier The wallet view shows HVOICE as well, is that coming from the smart contract or do you compute that? If so, is the calc the same as with the form?
> 
> ![image](https://user-images.githubusercontent.com/24725582/92273916-478d6d00-eeba-11ea-9525-6e0e3a4e1895.png)

These data is taken directly from the smartcontract
