### ISSUE TITLE
Add remaining Scenarios to Cypress Functional tests

### ISSUE THREAD

**Issue by julioholon** [hypha-dao/dho-web-client#440]
These are the needed tests. Plus add Cypress to Github.

**Needed ones:**
- [x] Create a Role
- [x] Approve a Role (vote up & activate)
- [x] Role Assignment
- [x] Approve an Assignment (vote up then activate)
- [ ] Create a Contribution
- [ ] Approve a Contribution (vote up then activate)
- [ ] Claim Pay

**Other ones:**
- Edit User Profile
- Withdraw from an Assignment
- Reduce Commitment
- Extend Assignment
- Suspend Assignment
- Create a Badge
- Badge Assignment  (vote up then activate)
- Archiving Roles
- Redeeming Wallet?
- Register a User
- Enroll Someone

**Comment by juliolrmonteiro** [comment]
https://docs.google.com/document/d/1yUelI694kRWb9fE5WTEXmHGjyPl_HQNRKAKgzg2D3OE/edit

**Comment by leonieherma1** [comment]
@lukegravitt Are we using this at the moment?
