### ISSUE TITLE
DHO-specific configurations

### ISSUE THREAD

**Issue by 3yekn** [hypha-dao/dho-web-client#445]
This issue is to document some configurations that need to be updated to be DHO-specific. 

Here is the settings document (viewable with ```daoctl get documents --type settings```).

| Contract or DHO Setting | Current Setting  | Future Setting | Notes |
| ------------- | ------------- | -------------- | --------------| 
| DHO | voting_duration_sec  | voting_duration_sec  | later, this can move to the proposal to support variable duration voting periods
| DHO | husd_token_contract  | peg_token_contract  | optional setting if a DHO wants to support paying a peg, could be ```BMUSD``` or ```BMGBP```, but default is neither.  They cannot use the same as Hypha because it grants access to treasury.
| DHO | | peg_token_symbol | asset value such as ```0.00 BUSD```
| DHO | hypha_token_contract  | reward_token_contract  | a token contract can hold many tokens, so we would likely re-use ```token.hypha``` but not required
| DHO |   | reward_token_symbol  | this is hard-coded many places now (in smart contracts and UI) as ```[HYPHA, 2]```, and we'll need to update to be data-driven
| DHO | hvoice_token_contract  | governance_token_contract  | 
| DHO ||   | governance_token_symbol  | also hard-coded, many places, needs to be data-driven (symbol includes both the string and precision; the string must be all capital letters and fewer than 8 characters)
| n/a | last_ballot_id  |   | no longer needed
| n/a | publisher_contract  |  | no longer needed
| Contract | seeds_escrow_contract  | escrow_contract | any DHO can use the escrow contract for any transferable token
| Contract | seeds_token_contract  | seeds_token_contract | I think all phase 1 DHOs could have native support for SEEDS
| n/a | telos_decide_contract  |  | no longer needed
| DHO | treasury_contract | treasury_contract | required if and only if the DHO is using peg token functionality
| DHO | hypha_deferral_factor_x100  | reward_token_price | this governs the value of HYPHA token vs USD and is used to calculate HYPHA values based on a USD input. It's an integer now - 13, which is applied in the contract, but it should probably an asset value, like "16.00 USD". 
| n/a | last_sender_id  |  | no longer needed
| Contract | paused  | paused | this is currently a contract level setting - not DHO level; may want to allow pausing DHO by DHO ❓ 
| n/a | seeds_deferral_factor_x100  |  | no longer needed
| n/a | last_sender_id  |  | no longer needed
| DHO | root_node  | root_node | this is duplicative to the edge pointing to the settings document, so may not be needed
| Contract | client_version | client_version | We probably haven't been updating this. It is just the semantic version number plus the commit hash
| Contract | contract_version | contract_version | 

## Additional notes
- The number of available tokens is fixed in the current design, e.g. a reward token, governance token, peg token, and SEEDS. However, we may want to support a dynamic set of compatible tokens. A DHO may have 8 different tokens that they hold and want to have available for payouts on proposals. 
- ```enrollers``` are currently defined as a permission on the contract, and this needs to be based on the enroller assigned a badge within a specific DHO
- ```roles```, ```assignments```, ```badges```, and ```badge assignments``` belong to a DHO but this is only indicated by the edges that exist from the ```root_node``` to the documents. We will need to enforce scenarios where a user is a member of one DHO where they hold the ```treasurer``` badge but they may not in a 2nd DHO. They should not get the 1% pay boost for assignment pay on the 2nd DHO.  
- the escrow 'unlock' event is currently hard-coded into the contract to the SEEDS ```golive``` event. We currently are not using escrow, so it's no big deal, but we'll need to address before we enable escrow options for a DHO. The UI will need to be updated also. (TODO: I need to give @leonieherma1 and @lukegravitt some docs or preso on this.)
- IMHO, we should migrate to the new recurring payment model soon unless other phase 1 DHOs are all going to use the same existing calendar.  We need to discuss this with @Gerard097 to ensure it can work with the ```adjustable commitment``` feature.
- Determining if a document, e.g. ```assignment```, is approved requires checking the edges. We may want to start leveraging the ```certificates``` functionality so that approvals on documents is more explicit and can be found **in** the document (although certificates are not part of the hash). 
- We should implement the ```UUID``` functionality soon. 

Current settings document as reference:
```
ContentGroups
  ContentGroup
    content_group_label                settings                                                         
    root_node                          52a7ff82bd6f53b31285e97d6806d886eefb650e79754784e9d923d3df347c91 
    voting_duration_sec                900                                                              
    updated_date                       2021-04-01T15:50:55.000                                          
    husd_token_contract                husd.hypha                                                       
    hypha_token_contract               token.hypha                                                      
    last_ballot_id                     hypha1....1tg                                                    
    publisher_contract                 publsh.hypha                                                     
    seeds_escrow_contract              escrow.seeds                                                     
    seeds_token_contract               token.seeds                                                      
    telos_decide_contract              trailservice                                                     
    hvoice_token_contract              voice.hypha                                                      
    treasury_contract                  bank.hypha                                                       
    client_version                     1.0.13 0c81dde6                                                  
    contract_version                   v0.2.0 618f051                                                   
    hypha_deferral_factor_x100         13                                                               
    last_sender_id                     527                                                              
    paused                             0                                                                
    seeds_deferral_factor_x100         100                                                              
  ContentGroup
    content_group_label                system                                                           
    type                               settings                                                         
    node_label                         Settings        
```

**Comment by lukegravitt** [comment]
| Current Setting  | Frontend Config | Where Used |
| ------------- | ------------- | -------------- |
| voting_duration_sec  | voteDurationSeconds | on assignment/badge propsal, to enable `extend` button |
| husd_token_contract  | husdToken | redeem, buy seeds, wallet, treasury |
| hypha_token_contract  | hyphaToken | wallet, treasury |
| hvoice_token_contract  | hvoiceToken | wallet (supply only) |
| seeds_escrow_contract  | seedsEscrow | wallet/deferred seeds |
| seeds_token_contract  | seedsToken | wallet/liquid seeds, treasury |
| telos_decide_contract  |  decide | profile, history lists (historical votes), registration <br />wallet <--- this is a bug i think? |
| treasury_contract | treasury | redeem/redemptions, treasury |
| hypha_deferral_factor_x100 | hyphaMultiplier |  assignment/contribution creation |

**Comment by dappdever** [comment]
Yes, we need to update the wallet to pull HVOICE balance from voice.hypha instead of telos_decide_contract.  The ```voice.hypha``` uses the standard data structure for tokens, so the balance would be derived like this: 
```cleos -u https://api.telos.kitchen get table voice.hypha hyphanewyork accounts```

As of now, users are not seeing new HVOICE issuance or decay in their wallet. Maybe this should be a new ticket for a hotfix?

**Comment by lukegravitt** [comment]
Opened #446

**Comment by lukegravitt** [comment]
Hardcoded data/details:

- [ ] Token names
- [ ] Token icons
- [ ] Deferred seeds (retrieval mechanism)
- [ ] That Hypha is 'deferred'
- [ ] Which tokens are paid (e.g hvoice_salary_per_phase)
- [ ] How many tokens
- [ ] How hypha/husd/hvoice are calculated from usd value and commitment level

Frontend - Must be done:

- [ ] Update all queries using 'has' to instead use edges from DHO root node (over 20 queries)

**Comment by leonieherma1** [comment]
https://github.com/hypha-dao/dao-contracts/issues/113

**Comment by leonieherma1** [comment]
@Gerard097 I am cleaning up the board, can I close this issue? It will not be deleted just not showing up at the board anymore
