### ISSUE TITLE
Extended assignment not working as expected

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#455]
Summary:

As a DHO user I would like to be able to extend my current assignment and see all the data that I put in the draft when proposing it.

Scenario

- My assignment: "Facilitating and Space Holding B4" showed the "extend" button in the "https://dho.hypha.earth/#/documents/assignment/leonieherma1" view
- I clicked "extend" and the sidebar with the assignment details opened

Expected Result

- I should be able to add a "title" in a separate field
- I should be able to add HUSD, HYPHA, and HVOICE 
- I should see the placeholder that says "new Key Results" 
- I should not see the "extend" button active anymore after proposing
- After proposing I should see the fields for date, commitment and deferred filled in

<img width="508" alt="Screenshot 2021-07-05 at 09 16 14" src="https://user-images.githubusercontent.com/75991832/124432248-b5702280-dd71-11eb-92ac-41ce86ad1345.png">

Actual Result

- I was not able to add a title
- I am not able to add HUSD, HYPHA, HVOICE (fields are not clickable)
- I did not see the placeholder copy (but the same copy from my old assignment)
- After proposing I can still see the "extend button"
- The fields "date", "commitment" and "deferred" are empty
<img width="505" alt="Screenshot 2021-07-05 at 09 20 08" src="https://user-images.githubusercontent.com/75991832/124432852-5d85eb80-dd72-11eb-8ead-847b499d9a46.png">

Second attempt:

- I then clicked "extend" again to see what happens and this time was able to add a title field and saw the right placeholder copy but was still not able to add the compensation. It seems like the "extend and claim buttons" are generally not updating.

- Also can not add a new start date (it is still the original start date from May) - is that supposed to be like that? If yes it is confusing because if I add 12 periods from May it is July so it doesn't seem like I can extend.

**Comment by lukegravitt** [comment]
Extending only lets you edit the number of periods, nothing else is changeable -- so that part is as expected. I think the display issues have to do with the graph not updating (this would be a missing 'original' edge, I think)
