### ISSUE TITLE
New Homepage

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#462]
**Summary:**
As a DHO user I would like to see all relevant DHO specific information on the landing screen.

**Description:**
https://dho.hypha.earth/#/preview/

old URL:
/#

new URL:
/

**Acceptance Criteria:**

- [ ] Header https://github.com/hypha-dao/dho-web-client/issues/524
- [ ] KPIs https://github.com/hypha-dao/dho-web-client/issues/525
- [ ] Support Widget https://github.com/hypha-dao/dho-web-client/issues/526
- [ ] How it works Widget https://github.com/hypha-dao/dho-web-client/issues/527
- [ ] News Widget https://github.com/hypha-dao/dho-web-client/issues/528
- [ ] Member Widget https://github.com/hypha-dao/dho-web-client/issues/529

**Ressources:**

https://docs.google.com/document/d/1LvmEhgZv5hoeFbavVPf9cYCJkBn5077gpMjSPfiSzO8/edit#

https://xd.adobe.com/view/26643786-1dac-4585-8f94-f76023be3090-7337/

![image](https://user-images.githubusercontent.com/75991832/137357813-47b51ee7-6bd8-465a-a87e-a7388ed44bae.png)

https://cdn.discordapp.com/attachments/826471199890604082/902471374566735872/Component_94_182x.png

Responsive Designs:
**To be done** 
![Homepage Header](https://user-images.githubusercontent.com/75991832/138904856-b0398dbc-52b0-44f4-81b8-a8d64b4af6dd.png)

**Comment by lukegravitt** [comment]
oops :)
