### ISSUE TITLE
Staging for proposals

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#475]
**Summary:**
As a DHO user I would like to be able to "stage" my proposal or publish a draft so people can give feedback in the comment section and I can collect consensus before publishing it on chain.

**Description:**
We need in total 3 stages for proposals.

1. Personal Draft (just visible for yourself)
2. Staging (Visible for everyone but no voting widget)
3. Publish / Propose (Open for voting for everyone)

**Acceptance Criteria:**

- [ ] Add a "staging" button to the proposal creation wizards last step
- [ ] Show the staged proposals on my own profile page as well as the "proposals" overview page
- [ ] Add a label (e.g. "staged") to the proposal cards and detail view
- [ ] Add a "propose" button (only visible for user)

**Ressources:**

Attachement: 

https://xd.adobe.com/view/500c58dc-9103-41f4-a82a-bb390323fbd8-055f/screen/c20e1ce9-f9cf-4900-b68a-9bf9f9828c3e

**Comment by josejulio** [comment]
> We need in total 3 stages for proposals.

Will it be possible to go directly to any later state? i.e. from creating to draft, from creating to staging, from creating to publish, from draft to staging, from draft to publish and from staging to publish?

> * Personal Draft (just visible for yourself)

This is a little weird, IIUC you cannot have "private" data on the table. Is fine if the UI doesn't show it? Anyone with experience and willing to see other drafts could query the tables and see your draft. 

If this is OK i suggest o use some wording on the UI to say something like:
"Your proposal is a Draft, others cannot link to this proposal but these contents are not hidden/private"

**Comment by leonieherma1** [comment]
Hey @josejulio,


What is the stage "draft" that you are referring to?

I think we should have these three stages (we can rename them):

1. Draft (hidden)
2. Stage (visible but not on chain)
3. Publish (on chain)

The following scenarios should be possible (if possible :) )

1. From draft (hidden) to staging
2. From draft (hidden) directly to publish
3. From staging back to draft (hidden)
4. From staging to publish 


Lets discuss the question of "privacy" at standup with @sceenius

**Comment by lukegravitt** [comment]
Currently, we do drafts on the client only. If we want them to be personal, I think it can remain this way. We only need a backend for them if we want them to be 'shareable' while still a draft.

**Comment by leonieherma1** [comment]
> Currently, we do drafts on the client only. If we want them to be personal, I think it can remain this way. We only need a backend for them if we want them to be 'shareable' while still a draft.

Hm not sure if it needs to be shareable since it is "private" or hidden anyways right?

**Comment by josejulio** [comment]
> Hm not sure if it needs to be shareable since it is "private" or hidden anyways right?

downside is that it lives in your browser, so you can't start on mobile and finish on web (or vice versa), so maybe something the user should be aware (if not already)

**Comment by sceenius** [comment]
Good point @josejulio since we are able share proposals on staging, we should use the same method for drafts too (same tech, just not shareable)

**Comment by josejulio** [comment]
`suspend` and `proposeextend` are also proposals, are these allowed to be on staging mode too or they go straight to "publish" always ?

**Comment by leonieherma1** [comment]
Proposeextend should definitely be on staging. Suspend is probably not necessary because when I "suspend" I can not really edit the content, right? But if it is easier we can make everything the same structure and just hide the "staging" button in the UI for suspension

**Comment by leonieherma1** [comment]
@dappdever do you remember if there was a specific reason for having the "drafts" of proposals in the client only? Performance reason? Save ram for the contract?
