### ISSUE TITLE
Claim possible on suspended / expired roles

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#484]
Summary:

As a DHO user I should not be able to claim pay after my role is expired or suspended. 

User: SanMartin (Discord)

Scenario:
When accessing the assignment via the profile the claim button is not there.

But when accessing via the main menu https://dho.hypha.earth/#/documents/assignment the claim button shows up and the user was able to claim and received HUSD to the wallet.

Note:
The same happens for my (leonieherma1) current assignment. In the profile the "claim" button is greyed out but in the /assignments page the claim button shows up. But I am not able to claim there. I get the following error in the transaction:

```User: leonieherma1
Error: assertion failure with message: 
------------------- Stack Trace -------------------

dao.cpp : void hypha::dao::claimnextper(const eosio::checksum256 &)
	dao.cpp:280: All available periods for this assignment have been claimed: 268c15f664a8d984eb731579ef6463c2932f281d3c4424f0d6626d29dabac717

--------------------------------------------------

------------------- Log -------------------


--------------------------------------------------

Action: 0
Contract: dao.hypha
Method: claimnextper
Data: {"assignment_hash":"268c15f664a8d984eb731579ef6463c2932f281d3c4424f0d6626d29dabac717"}
```

![image](https://user-images.githubusercontent.com/75991832/127525662-3ee38f1d-37b5-4e10-8662-1eac84108e26.png)

**Comment by joostschouten** [comment]
This also happened for the last three claims on this account: https://telos.bloks.io/account/sonicsphinxy

**Comment by leonieherma1** [comment]
solution here: https://github.com/hypha-dao/dao-contracts/issues/134
