### ISSUE TITLE
Proposal Creation Wizard (L)

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#504]
Summary:
As a DHO user I would like to be able to easily set up new proposals so I can actively contributing in governing Hypha. 

Description:

old URL:
sidebar

new URL:
/proposals/create: Proposal Creation
Member (payout) Proposals
/create?type=assignment: Apply for Role
/create?type=contribution: Make a Contribution
/create?type=quest: Start a Quest
/create?type=badge-assignment: Apply for Badge
/create?type=edit Edit an Assignment
/create?type=extend Extend an Assignment (maybe this is just an edit?)
/create?type=suspend Suspend an Assignment (might want a separate type to differentiate this from suspension of archetype)

Acceptance Criteria:

- [ ]  One Time Activity
> - Quest Proposal
> - Quest Completion
> - Bridge 
> - Expense
> - Agency

- [ ] Recurring Activity

> - Role Assignment 
> - Badge Assignment
> - Recurring Expense

- [ ] Recurring Activity

> - Policy 
> - Circle
> - Strategy
>- Role Archetype
>- Badge Type

Ressources:

Design:
https://xd.adobe.com/view/27bc7fff-1845-449c-913a-4ecfb3c9461c-72ef/screen/0a4a1df4-4461-4190-b5af-007806879ad9/

Responsive Designs:
[To be done
](https://xd.adobe.com/view/d57f1da3-0da9-4813-ae90-42f91dbdf8a0-802c/screen/3047b3a9-6b7c-4441-8965-356241873a3c/)

**Comment by leonieherma1** [comment]
@jmgayosso some small feedback from the design meeting today. Let me know if you want an individual story:

- [ ] Make boxes same height for "Generic Contribution", "Recurring Activity" and "Organizational Asset"
- [ ] Make title above fields smaller - Lato Bold 15px (check design system for exact CSS https://xd.adobe.com/view/dff2df13-c8f4-480e-8a2e-2a74a54a6db5-8aa1/screen/a107c024-b148-437e-92b6-af9a1d9b414d/specs/)
- [ ] Rename "Publish to Staging" to "Publish"

**Comment by jmgayosso** [comment]
Hi @leonieherma1 

![Screen Shot 2022-02-17 at 19 51 19](https://user-images.githubusercontent.com/58195358/154602441-9b1bd0b4-19ee-4928-894b-1aafe624d83b.png)

Do you prefer the same height (Choose an option items), or aligned to top with diferent heights (Choose a proposal type items), is not easy change to same height and aligned to top, because the componente used is dinamic buttons we have to search in the deep styles for quasar to change this, please let me know

**Comment by leonieherma1** [comment]
@jmgayosso please use the same height. And shorten the copy of the first one to: 

This option is a simple payout for a one time contribution or expense.

**Comment by jmgayosso** [comment]
Done
