### ISSUE TITLE
Migrate queries to typed dgraph db - Search (M)

### ISSUE THREAD

**Issue by lukegravitt** [hypha-dao/dho-web-client#520]
For support of multi-dho and performance reasons, we are migrating our dgraph queries to graphql queries using a typed interface. Support for this includes all the following steps:

- [x] Add client graphql library (vue-apollo)
- [x] Migrate proposal list query
- [x] Create proposal detail query
- [x] Create home page query (# active proposals, new members, etc)
- [x] Create organization page query (circles?)

- [ ] Create search query

**Comment by jmgayosso** [comment]
@leonieherma1  search query was replaced by elastic search implementation, so I think we can move this ticket to done
