### ISSUE TITLE
New Homepage - Header

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#524]
![header DHO no background](https://user-images.githubusercontent.com/75991832/134052414-627335bf-01a2-4cb4-975e-83d9175bf0a3.png)
**Summary:**
As a DHO user I would like to see all relevant DHO specific information on the landing screen.

**Description:**
https://dho.hypha.earth/#/preview/
https://github.com/hypha-dao/dho-web-client/issues/462

old URL:
/#

new URL:
/

**Acceptance Criteria:**

Header:
- [ ] Show name of the DHO and short welcome text (that explains purpose of the DHO)
- [ ] Discover Hypha: Link to About Hypha
- [ ] Documentation: Link to support document (convert into Wiki) https://notepad.hypha.earth/5dC66nNXRVGpb1aTHaRJXw
- [ ] Possibility to click away the Welcome Box (and keep it hidden)
- [ ] Background color: #242F5D

**Ressources:**

https://docs.google.com/document/d/1LvmEhgZv5hoeFbavVPf9cYCJkBn5077gpMjSPfiSzO8/edit#

https://xd.adobe.com/view/26643786-1dac-4585-8f94-f76023be3090-7337/

![image](https://user-images.githubusercontent.com/75991832/137358166-06284309-3d6b-4408-80da-094daabe06c8.png)
![image](https://user-images.githubusercontent.com/75991832/137358208-c1c0bbfb-e73a-4326-85c7-9de576a9aa76.png)

**Comment by lukegravitt** [comment]
Do we have graphics to use on the right side of this header?

**Comment by lukegravitt** [comment]
This should be implemented into the welcome-banner component:

https://github.com/hypha-dao/dho-web-client/blob/develop/src/components/dashboard/welcome-banner.vue
Props: None

**Comment by jmgayosso** [comment]
@lukegravitt What do you mean with 'Possibility to click away the Welcome Box (and keep it hidden)
', could you explain me please?

**Comment by leonieherma1** [comment]
@jmgayosso hey :) so the idea was that you have a "x" on the corner of the header. And when you click the X the box disappears. It is because the box explains how voting works, what unitiy and quorum are etc... it is interesting for users who login for the first time, second time, maybe 10 times, but some might find it annoying to see it everytime.

So we have two options:
1. Always show the box after login and when the user clicks the "X" it disappears. It shows up again on next login
2. Once the user clicks "x" and the box disappears, the box stays hidden for X amount of logins (is that even possible?)
3. Once the user clicks "x" the box disappears forever

Which of those options are feasable? Which one is the easiest?

If all of them are really difficult, we can also leave this feature out and add it some time later.

Please let me know what you think

**Comment by jmgayosso** [comment]
> @jmgayosso hey :) so the idea was that you have a "x" on the corner of the header. And when you click the X the box disappears. It is because the box explains how voting works, what unitiy and quorum are etc... it is interesting for users who login for the first time, second time, maybe 10 times, but some might find it annoying to see it everytime.
> 
> So we have two options:
> 
> 1. Always show the box after login and when the user clicks the "X" it disappears. It shows up again on next login
> 2. Once the user clicks "x" and the box disappears, the box stays hidden for X amount of logins (is that even possible?)
> 3. Once the user clicks "x" the box disappears forever
> 
> Which of those options are feasable? Which one is the easiest?
> 
> If all of them are really difficult, we can also leave this feature out and add it some time later.
> 
> Please let me know what you think


Hi @leonieherma1 , really they are all feasibles but it depends on the backend, the option 1 is the easiest because it is just the front-end, I am going to implement that for the moment

**Comment by leonieherma1** [comment]
@jmgayosso sounds good, let's do that for now, thanks

**Comment by lukegravitt** [comment]
@jmgayosso @leonieherma1 

I'm planning to add support for a per-device setting for this and other values (probably using localStorage). The box will then show 1 time per device (and when this data is cleared). You could use localStorage for now.

**Comment by jmgayosso** [comment]
> @jmgayosso @leonieherma1
> 
> I'm planning to add support for a per-device setting for this and other values (probably using localStorage). The box will then show 1 time per device (and when this data is cleared). You could use localStorage for now.

Good Idea @lukegravitt , Im going to implement it
