### ISSUE TITLE
New Homepage - KPIs

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#525]
**Summary:**
As a DHO user I would like to see all relevant DHO specific information on the landing screen.

**Description:**
https://dho.hypha.earth/#/preview/
https://github.com/hypha-dao/dho-web-client/issues/462

old URL:
/#

new URL:
/

**Acceptance Criteria:**

Header:
- [ ] XX Total Equity Token distributed (link to treasury)
- [ ] XX Total Hypha Token distributed (links to treasury)
- [ ] XX New Proposals (links to proposals)
- [ ] XX Active Assignments (links to ?)

**Ressources:**

https://docs.google.com/document/d/1LvmEhgZv5hoeFbavVPf9cYCJkBn5077gpMjSPfiSzO8/edit#

https://xd.adobe.com/view/26643786-1dac-4585-8f94-f76023be3090-7337/

![image](https://user-images.githubusercontent.com/75991832/137358365-e53f8fb1-fbbf-4c50-a7b2-89814d3cd03d.png)

**Comment by lukegravitt** [comment]
All 4 KPI's should use the following component: https://github.com/hypha-dao/dho-web-client/blob/develop/src/components/dashboard/metric-link.vue

Props:
title: String
amount: String
link: String

?? linkLabel: String

Calculation of the individual metrics is not required for this story, just implementation of the shared component.
