### ISSUE TITLE
New Homepage - Support Widget

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#526]
**Summary:**
As a DHO user I would like to see all relevant DHO specific information on the landing screen.

**Description:**
https://dho.hypha.earth/#/preview/
https://github.com/hypha-dao/dho-web-client/issues/462

old URL:
/#

new URL:
/

**Acceptance Criteria:**

Support Widget:

- [ ] Title, Copy and Button with Link to discord channel (#dho-support)

**Ressources:**

https://docs.google.com/document/d/1LvmEhgZv5hoeFbavVPf9cYCJkBn5077gpMjSPfiSzO8/edit#

https://xd.adobe.com/view/26643786-1dac-4585-8f94-f76023be3090-7337/

![image](https://user-images.githubusercontent.com/75991832/137358417-6b97e674-5d89-45e6-a056-8fc127976886.png)

**Comment by lukegravitt** [comment]
This should be implemented here: https://github.com/hypha-dao/dho-web-client/blob/develop/src/components/dashboard/support-widget.vue

**Comment by jmgayosso** [comment]
Hi @lukegravitt, Do you have the invitation link to dho-support?? I can`t generate the invitation link, maybe this link could help you

**Comment by leonieherma1** [comment]
I don't think I have the permission to create an invite link. Maybe @sceenius can do it? It should look like this:

<img width="329" alt="Screenshot 2021-10-04 at 16 24 08" src="https://user-images.githubusercontent.com/75991832/135926936-8a285ae0-9812-466b-8a54-8cca65e1d339.png">

It's important to uncheck the checkbox "expire link in 24h" 

Accorrding to this article: https://www.alphr.com/discord-create-invite-link/

**Comment by leonieherma1** [comment]
@jmgayosso copy for support widget: "Please read our Documentation for more info. If you are stuck with a problem you can also reach out to us on discord in the "dho-support" channel."

**Comment by jmgayosso** [comment]
> @jmgayosso copy for support widget: "Please read our Documentation for more info. If you are stuck with a problem you can also reach out to us on discord in the "dho-support" channel."

done
