### ISSUE TITLE
New Homepage - How it works Widget

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#527]
**Summary:**
As a DHO user I would like to see all relevant DHO specific information on the landing screen.

**Description:**
https://dho.hypha.earth/#/preview/
https://github.com/hypha-dao/dho-web-client/issues/462

old URL:
/#

new URL:
/

**Acceptance Criteria:**

How to vote:
- [ ] Slider with graphic element and 5 slides (see copy docs)

**Ressources:**

https://docs.google.com/document/d/1LvmEhgZv5hoeFbavVPf9cYCJkBn5077gpMjSPfiSzO8/edit#

https://xd.adobe.com/view/26643786-1dac-4585-8f94-f76023be3090-7337/

![image](https://user-images.githubusercontent.com/75991832/137358066-3c052b09-c5be-4ad7-8bd6-e49e05389c1f.png)

**Comment by lukegravitt** [comment]
This should be implemented here: https://github.com/hypha-dao/dho-web-client/blob/develop/src/components/dashboard/how-it-works.vue

Props:
voteDuration: Number (in seconds)
quorum: Number (integer % 0-100 needed for proposal to pass)
unity: Number (integer % 0-100 needed for proposal to pass)
