### ISSUE TITLE
New Homepage - News Widget

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#528]
**Summary:**
As a DHO user I would like to see all relevant DHO specific information on the landing screen.

**Description:**
https://dho.hypha.earth/#/preview/
https://github.com/hypha-dao/dho-web-client/issues/462

old URL:
/#

new URL:
/

**Acceptance Criteria:**

News:
- [ ] 3 manually added news (see copy docs)
- [ ] show date of news (e.g 1 day ago - after one week show date. If it is easier just show date from the beginning)
- [ ] Add label for "announcement" and "new feature"
- [ ] Pagination

**Ressources:**

https://docs.google.com/document/d/1LvmEhgZv5hoeFbavVPf9cYCJkBn5077gpMjSPfiSzO8/edit#

https://xd.adobe.com/view/26643786-1dac-4585-8f94-f76023be3090-7337/

![image](https://user-images.githubusercontent.com/75991832/137357957-b090e504-03de-4836-ab7e-164bd78fc76d.png)

**Comment by lukegravitt** [comment]
This should be implemented in these two components:
https://github.com/hypha-dao/dho-web-client/blob/develop/src/components/dashboard/news-widget.vue
https://github.com/hypha-dao/dho-web-client/blob/develop/src/components/dashboard/news-item.vue

Props to news widget:
news: Array of news items (see below for props)

Props to news item:
title: String
author: String (username of author)
date: Date when posted
description: String (markdown?), news text

**Comment by jmgayosso** [comment]
> This should be implemented in these two components: https://github.com/hypha-dao/dho-web-client/blob/develop/src/components/dashboard/news-widget.vue https://github.com/hypha-dao/dho-web-client/blob/develop/src/components/dashboard/news-item.vue
> 
> Props to news widget: news: Array of news items (see below for props)
> 
> Props to news item: title: String author: String (username of author) date: Date when posted description: String (markdown?), news text

Hi @lukegravitt , We should add 'type' prop to know if is "announcement" or "new feature"?? Also regard to pagination, should be normal pagination or infinite Load more pagination. I think is better the Infinite scroll pagination

**Comment by lukegravitt** [comment]
A 'type' prop makes sense. 

And we can do infinite scroll since the news widget will be the last one on the page. Thoughts @leonieherma1 ?
