### ISSUE TITLE
New Homepage - Member Widget

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#529]
**Summary:**
As a DHO user I would like to see all relevant DHO specific information on the landing screen.

**Description:**
https://dho.hypha.earth/#/preview/
https://github.com/hypha-dao/dho-web-client/issues/462

old URL:
/#

new URL:
/

**Acceptance Criteria:**

Recent Members:
- [ ] Show last 5 members that joined
- [ ] Avatar, name, relative date joined, link to profile
- [ ] Link to /members page “view all XXX members”

**Ressources:**

https://docs.google.com/document/d/1LvmEhgZv5hoeFbavVPf9cYCJkBn5077gpMjSPfiSzO8/edit#

https://xd.adobe.com/view/26643786-1dac-4585-8f94-f76023be3090-7337/

![image](https://user-images.githubusercontent.com/75991832/137358296-dc3b0664-ea7a-4e48-bbce-0478daba2ca4.png)

**Comment by lukegravitt** [comment]
Should be implemented here: https://github.com/hypha-dao/dho-web-client/blob/develop/src/components/dashboard/new-members.vue

Props:
members: Array (of string -- usernames)
