### ISSUE TITLE
Project Detail Page - Suspended (S)

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#534]
**Summary:**
As a DHO user I would like to see all details of an active project on one overview page.

**Description:**

old URL:
sidebar

new URL:
/activity/<uuid>

**Acceptance Criteria:**

- [x] back button / breadcrumb navigation?
- [x] Title: Project Title

Proposal Detail Widget:
- [x] Label: Document Type
- [ ] Label: Circle
- [x] Label: Compensation (Salary Band or USD equivalent)
- [x] Titel of Proposal
- [x] Text field with Objectives, Key Results, Description, Documentation Link
- [x] Date & Duration
- [x] Commitment Level
- [x] Deferred Amount
- [x] HUSD, Hypha, HVOICE, Total USD equivalent
- [x] Avatar, Name, Link to profile, badges

Vote Widget:
- [x] Title: Suspended
- [x] Unity & Quorum
- [x] Instead of vote button, show: "You voted XX"
- [x] Activation Date

Last Votes Widget:
- [x] date
- [x] name
- [x] avatar
- [x] vote (yes, no, support, abstain, harmful, unicorns, etc...)
- [x] % of vote (of HVOICE in organisation - not per this vote (current status)
- [x] Pagination

Comment Widget:
- [x] not MVP see different story: #456 

**Ressources:**

Copy: https://docs.google.com/document/d/1KHC_6Cha8MC2NMKDV6XRXKuZGS7kPdVGuLtF_kSYvbU/edit#

Attachement: 

https://xd.adobe.com/view/2e6dc275-76dc-4722-a922-cc60c5d7d653-7b3e/screen/ed92893b-fa1e-4dcd-98a5-dbec5f34d913

![image](https://user-images.githubusercontent.com/75991832/135157449-a5961d54-2875-4f4e-b568-5f49161da43e.png)

**Comment by jmgayosso** [comment]
Hi @leonieherma1! Gerry told me we don't have suspended proposal types for now, but should be easy add thie validations to vote widgets when we have it

**Comment by leonieherma1** [comment]
@Gerard097 @jmgayosso we do have the suspend function at the moment:

<img width="881" alt="image" src="https://user-images.githubusercontent.com/75991832/154985044-038d5bbf-8514-4852-8d33-93c958f16254.png">

**Comment by jmgayosso** [comment]
My bad Leonie I mean on the MVP, I did not seen this user flow on MVP

**Comment by leonieherma1** [comment]
@jmgayosso yes we forgot it in the MVP Designs, I will add it with Massimo this week and create a separate story. Sorry!

**Comment by leonieherma1** [comment]
@DaniPoot @jmgayosso we have the designs for the suspend flow: https://xd.adobe.com/view/2e6dc275-76dc-4722-a922-cc60c5d7d653-7b3e/screen/ed92893b-fa1e-4dcd-98a5-dbec5f34d913

**Comment by leonieherma1** [comment]
@DaniPoot @jmgayosso can we add this process also for badges? (not contributions)
