### ISSUE TITLE
Project Detail Page - Archived (S)

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#535]
**Summary:**
As a DHO user I would like to see all details of an archived project on one overview page.

**Description:**

old URL:
sidebar

new URL:
/activity/<uuid>

**Acceptance Criteria:**

- [x] back button / breadcrumb navigation?
- [x] Title: Project Title

Proposal Detail Widget:
- [x] Label: Document Type
- [ ] Label: Circle
- [x] Label: Compensation (Salary Band or USD equivalent)
- [x] Titel of Proposal
- [x] Text field with Objectives, Key Results, Description, Documentation Link
- [x] Date & Duration
- [x] Commitment Level
- [x] Deferred Amount
- [x] HUSD, Hypha, HVOICE, Total USD equivalent
- [x] Avatar, Name, Link to profile, badges

Vote Widget:
- [x] Title: Archived
- [x] Unity & Quorum
- [x] Button: "You voted XX"
- [x] Date: This vote ended XX days ago

Last Votes Widget:
- [x] date
- [x] name
- [x] avatar
- [x] vote (yes, no, support, abstain, harmful, unicorns, etc...)
- [x] % of vote (of HVOICE in organisation - not per this vote (current status)
- [x] Pagination

Comment Widget:
- [x] not MVP see different story: #456 

**Ressources:**

Copy: https://docs.google.com/document/d/1KHC_6Cha8MC2NMKDV6XRXKuZGS7kPdVGuLtF_kSYvbU/edit#

Attachement: 
![image](https://user-images.githubusercontent.com/75991832/137367338-e42d646c-6048-4f8c-88dc-385e4bbc7e8a.png)

https://xd.adobe.com/view/d802317c-bf4d-4084-a77e-b6c2d046d49c-8d51/

Responsive Designs:
To be done

**Comment by jmgayosso** [comment]
Hi @Gerard097  Could you help us to get a proposal with archived state please? How we can get one to test???

**Comment by leonieherma1** [comment]
@DaniPoot @jmgayosso when I click "archive" on my proposal nothing happens, it just looks like this:

<img width="1291" alt="image" src="https://user-images.githubusercontent.com/75991832/160006482-9d1bf4c4-678e-4215-b835-6ea6828efaa5.png">
