### ISSUE TITLE
Proposal Detail Page - Staging (L)

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#536]
**Summary:**
As a DHO user I would like to see all details of an staged proposals on one overview page.

Backend Story done by Jose Julio: https://github.com/hypha-dao/dho-web-client/issues/475

**Description:**

old URL:
sidebar

new URL:
/activity/<uuid>

**Acceptance Criteria:**

- [ ] back button / breadcrumb navigation?
- [ ] Title: Project Title

Proposal Detail Widget:
- [ ] Label: Document Type
- [ ] Label: Circle
- [ ] Label: Compensation (Salary Band or USD equivalent)
- [ ] Titel of Proposal
- [ ] Text field with Objectives, Key Results, Description, Documentation Link
- [ ] Date & Duration
- [ ] Commitment Level
- [ ] Deferred Amount
- [ ] HUSD, Hypha, HVOICE, Total USD equivalent
- [ ] Avatar, Name, Link to profile, badges

Vote Widget:
- [ ] Title: Your proposal is on staging
- [ ] Explanation copy: https://docs.google.com/document/d/1KHC_6Cha8MC2NMKDV6XRXKuZGS7kPdVGuLtF_kSYvbU/edit
- [ ] Button: Publish
- [ ] Link: Edit Proposal

Last Votes Widget:
- [ ] date
- [ ] name
- [ ] avatar
- [ ] vote (yes, no, support, abstain, harmful, unicorns, etc...)
- [ ] % of vote (of HVOICE in organisation - not per this vote (current status)
- [ ] Pagination

**Ressources:**

Attachement: 
https://xd.adobe.com/view/26643786-1dac-4585-8f94-f76023be3090-7337/screen/ce6a53b2-c119-4dbf-9c43-b17a9d8a931f

https://xd.adobe.com/view/d802317c-bf4d-4084-a77e-b6c2d046d49c-8d51/

![image](https://user-images.githubusercontent.com/75991832/137359628-46aac809-fd2b-4f38-81aa-d8a55fae0a10.png)

Responsive Designs:
**To be done**

**Comment by jmgayosso** [comment]
Hey @leonieherma1 what is the diference with this task???  https://github.com/hypha-dao/dho-web-client/issues/324

**Comment by jmgayosso** [comment]
Oh sorry this is a specific state for this screen right?

**Comment by arsenijesavic** [comment]
@leonieherma1 We need to change that also on the backend 
> the voting period (7 days) should only start once the proposal is live:

@Gerard097 @josejulio @smonteroMW

**Comment by leonieherma1** [comment]
@arsenijesavic 
Please change the copy on both buttons to:
"Publish to Staging"

<img width="1002" alt="image" src="https://user-images.githubusercontent.com/75991832/168668730-07ae01d8-857a-4546-a38d-690f71eb0b6a.png">


And this copy to:
**Your proposal is on staging**
That means your proposal is not publish to the blockchain yet. You can still make changes to it, when you feel ready click "Publish" and the voting period will start. 

<img width="299" alt="image" src="https://user-images.githubusercontent.com/75991832/168669195-77074cf7-7c5a-4cb1-9052-034f2a23dc8f.png">

**Comment by leonieherma1** [comment]
@arsenijesavic the "edit proposal" button is not working as expected

<img width="349" alt="image" src="https://user-images.githubusercontent.com/75991832/168669515-99608916-3fc4-4191-a6d1-d1f24672f4a6.png">


Expected behaviour:

- [ ] Open the proposal creation wizard on the second screen / step 2 (I cannot change the document type anymore, correct?)
<img width="1325" alt="image" src="https://user-images.githubusercontent.com/75991832/168669648-83da8672-07fc-466b-900b-a0a2800483de.png">

- [ ] When I open it then the whole proposal content is gone:
 https://dao-dev.hypha.earth/hypha/proposals/30462
<img width="1784" alt="image" src="https://user-images.githubusercontent.com/75991832/168670097-e3b218bf-b504-44df-a337-6a6871b53bdf.png">

**Comment by leonieherma1** [comment]
@arsenijesavic staging should be toggled on as default

<img width="340" alt="image" src="https://user-images.githubusercontent.com/75991832/168670386-74022191-faec-4978-8c2f-b8b80407a34b.png">

**Comment by leonieherma1** [comment]
@arsenijesavic after clicking "publish" I see this screen:

<img width="1289" alt="image" src="https://user-images.githubusercontent.com/75991832/168670700-aa68dd2b-4f2d-4d12-a18f-23b466250146.png">


Label says "staging" and button says "publish" - but it should be published already (transaction was succesfull)
