### ISSUE TITLE
Salary Band Indicator

### ISSUE THREAD

**Issue by sceenius** [hypha-dao/dho-web-client#54]
We are adding a salary band indicator to the card and switch the position of the avatar the the card icon. We also replace "Assignment" with the full name of the user. Computation of bands that are not matching as follows:

B1 - [0..80,000]
B2 - ]80,000..100,000]
B3 - ]100,000..120,000]
B4 - ]120,000..140,000]
B5 - ]140,000..160,000]
B6 - ]160,000..180,000]
B7 - ]180,000..200,000+]

![image](https://user-images.githubusercontent.com/24725582/92139770-3d963c00-edde-11ea-953a-82f177e45eac.png)

**Comment by sceenius** [comment]
Let's do this only for contributions and assignments not for roles (switch avatar and icon). It will get confusing for users to see a person on a role (which is the owner/caretaker only). 
![image](https://user-images.githubusercontent.com/24725582/92274154-ae128b00-eeba-11ea-8286-34dfe745f7d0.png)

**Comment by sceenius** [comment]
Showing the salary bucket badges on the role is a great idea.

**Comment by gregory-latinier** [comment]
Could we keep the same design with the type on top right and display something more meaningful in the center?

**Comment by sceenius** [comment]
@gregory-latinier I have an idea now for the center avatar on the role card. We can either show a gray person icon (role not occupied) or better yet a random avatar... key is that the avatar should stay the same, so let's tie it to a string (e.g. email).

http://avatars.adorable.io/
https://www.tinygraphs.com/

**Comment by gregory-latinier** [comment]
> @gregory-latinier I have an idea now for the center avatar on the role card. We can either show a gray person icon (role not occupied) or better yet a random avatar... key is that the avatar should stay the same, so let's tie it to a string (e.g. email).
> 
> http://avatars.adorable.io/
> https://www.tinygraphs.com/

I don't mind either, tell me what you would like to see exactly.

**Comment by sceenius** [comment]
Let's try the first one, seems fairly new and looks more interesting.  
![image](https://user-images.githubusercontent.com/24725582/92389792-bf8caa80-f0e7-11ea-8d33-02cee2a77089.png)

Would be good to use a unique ID to create it like object ID, then round avatar (see above)

**Comment by sceenius** [comment]
https://github.com/adorableio/avatars-api-middleware

**Comment by sceenius** [comment]
The avatar changed when the role was approved - it is critical to keep the same avatar as to not confuse the user here. 
![image](https://user-images.githubusercontent.com/24725582/92494377-a527ff00-f1c3-11ea-9622-b17f3d2b7fb5.png)

**Comment by sceenius** [comment]
Add     ```line-height: 1.0;``` to the title (showing name here, but you can do for all titles)

**Comment by gregory-latinier** [comment]
OK I see I used the ID but the object changes when approved, it changes from a proposal to a role so it's a new ID. I'll use the title as a unique identifier them

**Comment by sceenius** [comment]
Line height still the same (see above) on role proposal. 

![image](https://user-images.githubusercontent.com/24725582/92515693-01018080-f1e2-11ea-9818-c0869e344c69.png)

**Comment by sceenius** [comment]
![image](https://user-images.githubusercontent.com/24725582/92518224-019c1600-f1e6-11ea-88c6-3b1fd73be076.png)

**Comment by gregory-latinier** [comment]
Can you force refresh the page ? The CSS was updated, I don't have the issue on testing

**Comment by sceenius** [comment]
On the ROLE card, switch title and subtitle (user name is less important than the title of the role, so make title of role black and bold, username/owner gray)

**Comment by sceenius** [comment]
We need to show the username somewhere. Let's put it on the form in parens after the title, e.g. "New ROle JS (@joachimstroh)
![image](https://user-images.githubusercontent.com/24725582/92956477-eecb5080-f434-11ea-8bb3-b82e60c54659.png)

**Comment by gregory-latinier** [comment]
I'll add this but please don't reopen tasks that are deployed in production.
