### ISSUE TITLE
Badge Type Detail Page

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#548]
**Summary:**
As a DHO user I would like to see all details about a certain archetype on one page.

**Description:**

Same as: https://github.com/hypha-dao/dho-web-client/issues/474

old URL:
https://dho.hypha.earth/#/documents/badge

new URL: (?)
/organization/badge/xy
/badge/xy
/badge-type/xy
/activity?type=badge-type-xy

**Acceptance Criteria:**

- [x] Headline: Badge XY
- [x] Apply Button - takes user to Creatzion Wizard with respective archetype preselected in "role assignment"

**Ressources:**

Designs:
[to be done](https://xd.adobe.com/view/2e6dc275-76dc-4722-a922-cc60c5d7d653-7b3e/screen/d50da329-7d72-4e02-a014-8829e5ae400f/)

<img width="1341" alt="image" src="https://user-images.githubusercontent.com/75991832/154722117-650831e7-b9e3-4120-b7fd-e1ef8cc5b402.png">

**Comment by jmgayosso** [comment]
Hi @leonieherma1 we should can suspend the badge from this screen? for the moment the backend respond with a validations error for this proposal type. with the archetypes works correctly but not for this.
![Screenshot_2022-03-02-02-22-28_4480x1080](https://user-images.githubusercontent.com/58195358/156443512-b8fd0572-5a7d-4f7f-a696-1cd8d8c4c971.png)

**Comment by leonieherma1** [comment]
@jmgayosso are you saying that badges can not be suspended from the backend at the moment?

Can you verify @Gerard097 ?

**Comment by jmgayosso** [comment]
> @jmgayosso are you saying that badges can not be suspended from the backend at the moment?
> 
> Can you verify @Gerard097 ?

yes, I talked Gerry and he is fixing the issue, is just change a validation.
