### ISSUE TITLE
Moon calendar cycles are missing

### ISSUE THREAD

**Issue by sceenius** [hypha-dao/dho-web-client#55]
User cannot select eval date. 
![image](https://user-images.githubusercontent.com/24725582/92153782-c9b25e80-edf2-11ea-8542-79fcbc3a3274.png)

**Comment by gregory-latinier** [comment]
I need more information.
What is the context ? Edit, new ?
What object ? assignment, contribution, role

**Comment by sceenius** [comment]
Never mind, Eval Date shows a full cycle, so only one day per month available. Which is as expected, closing this now.

**Comment by sceenius** [comment]
How do you close an issue on GitHub? @gregory-latinier
