### ISSUE TITLE
Configuration Page (L)

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#565]
Summary: 
As a DHO admin user I would like to be able to see all configurations in one overview page and change them.

Acceptance Criteria:

- [x] Add Settings icon on top bar (next to help icon)
- [x] Headline: Configuration Settings
- [x] Add Tabs for each configuration category
- [x] Show page to everyone but only have "admin badge" holders be able to adjust settings

Individual Tabs: to be done

Design:
https://xd.adobe.com/view/7cc1de2c-4b1e-466b-8ac4-eb37f309c3bb-2992/screen/5874d328-e48f-4b52-9d56-656db168d1b0

![image](https://user-images.githubusercontent.com/75991832/143141199-f0d98636-cd1c-47d8-9c88-21dbd60fe5f2.png)

**Comment by leonieherma1** [comment]
@n13 @sceenius we don't really have an admin badge either - how should we handle this? Maybe we have the initial DHO members to be admins (with an admin badge) which is also an enroller at the same time?

**Comment by sceenius** [comment]
Let' keep it simple and define the "owners" group only, the parametric badges (badges with access to features) can come later.

**Comment by leonieherma1** [comment]
@sceenius ok sounds good. Who is the owner group? The ones we initially define at the beginning? What if they change...we could also add "admins" or owners on this page: https://xd.adobe.com/view/27bc7fff-1845-449c-913a-4ecfb3c9461c-72ef/screen/7a5aa689-fbc9-4cd9-9bd0-9b1e3c5ed162/

**Comment by sceenius** [comment]
Possible, but then who has access to the configuration page? I think the owners will stay constant for a while and then we can introduce the parametric badges.

**Comment by sceenius** [comment]
Here is the "launch team" page - https://xd.adobe.com/view/27bc7fff-1845-449c-913a-4ecfb3c9461c-72ef/screen/be7c5ff0-9fd6-4c50-a22f-4a642c4d15a7/ - which should suffice to give root permissions

**Comment by leonieherma1** [comment]
@arsenijesavic some feedback for the config page:

1. Add a tooltip for non admins on all widgets "Only DAO admins can change the settings"
2. The preview for primary and secondary color is missing
3. non admins should not be able to open the colour picker
The color preview is not correct:
5. Primary Color = Buttons
6. Secondary Color = Buttons Secondary
7. Pattern color = the color of the pattern e.g. grey or black
See: https://xd.adobe.com/view/27bc7fff-1845-449c-913a-4ecfb3c9461c-72ef/screen/f0c32adb-78e8-463d-81f6-0e1e36239de0

For the banners I should see a preview and be able to change the background colours (tabs)

<img width="878" alt="image" src="https://user-images.githubusercontent.com/75991832/161868694-adb1c263-9cb7-4c8d-afd6-d2ce559fb276.png">

**Comment by arsenijesavic** [comment]
@leonieherma1 what needs to be done here ?

**Comment by leonieherma1** [comment]
> @leonieherma1 what needs to be done here ?

please update the configuratin page according to Massimos new design: https://xd.adobe.com/view/7cc1de2c-4b1e-466b-8ac4-eb37f309c3bb-2992/screen/5874d328-e48f-4b52-9d56-656db168d1b0

**Comment by leonieherma1** [comment]
@arsenijesavic the patterns are ready: https://xd.adobe.com/view/dff2df13-c8f4-480e-8a2e-2a74a54a6db5-8aa1/screen/6f29268a-92a5-4d1f-a5c5-f0c1f57303f6

The final design for the config page comes tomorrow (there is only a field for button name and link missing - we totally forgot that)

https://xd.adobe.com/view/7cc1de2c-4b1e-466b-8ac4-eb37f309c3bb-2992/screen/5874d328-e48f-4b52-9d56-656db168d1b0

**Comment by leonieherma1** [comment]
@arsenijesavic here are the missing assets:

<i class="fa-solid fa-arrow-up-from-bracket"></i>
<i class="fa fa-bell-o" aria-hidden="true"></i>
<i class="fa fa-pencil" aria-hidden="true"></i>
<i class="fa fa-file-o" aria-hidden="true"></i>



![Group 2877 (1)](https://user-images.githubusercontent.com/75991832/169080316-b7baccfe-7679-4181-83cf-07910d7f3591.svg)

![Group 2877](https://user-images.githubusercontent.com/75991832/169080319-394c6a31-f83c-4cf0-b022-91bac91b09da.svg)

![Path 12719](https://user-images.githubusercontent.com/75991832/169080302-8d785846-c6f0-45d4-bd17-8c81f93d95e9.svg)
![Group 2874](https://user-images.githubusercontent.com/75991832/169080309-83dff462-04b3-46d2-9c59-a1f45e66a87f.svg)
![Group 2876](https://user-images.githubusercontent.com/75991832/169080312-4635a7f4-7c76-4b4b-af28-b44182bd4148.svg)

**Comment by leonieherma1** [comment]
@arsenijesavic i forgot one pattern
![Group 2879](https://user-images.githubusercontent.com/75991832/169082698-e48679df-e538-4274-8bf1-8729f9faadb9.svg)
