### ISSUE TITLE
Organisational Page - Treasury [S]

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#566]
**Summary:**
As a DHO user I would like to see an overview page about the Hypha Organization with links to organisational pages (e.g. treasury, archetypes, all projects, etc...) in order to understand the organisation better and navigate to pages with more info. 

**Description:**

old URL:

new URL:
/organization

Treasury:
- [ ] Headline: Treasury
- [ ] Copy: none
- [ ] HUSD, HYPHA, SEEDS
- [ ] see more link (leads to /treasury)

**Ressources:**

Attachement: 

https://docs.google.com/document/d/1KHC_6Cha8MC2NMKDV6XRXKuZGS7kPdVGuLtF_kSYvbU/edit

https://xd.adobe.com/view/a31415be-a724-49ad-8070-1a7d67dd6880-f647/screen/d4abf3d4-9283-4877-8d6d-8a80653bd50c?fullscreen

![image](https://user-images.githubusercontent.com/75991832/137363423-fd647040-5a7f-4e34-a9a8-621ff54bb96e.png)

**Comment by leonieherma1** [comment]
@jmgayosso hide "see more" for treasury and add copy "Overview of all Token in the {DAO NAME} Treasury". Actually I would prefer to hide the copy, if that is possible?

**Comment by jmgayosso** [comment]
> Overview of all Token in the {DAO NAME} Treasury"

I can do wherever you want, both options are too fast, what do you prefer??

**Comment by leonieherma1** [comment]
> > Overview of all Token in the {DAO NAME} Treasury"
> 
> I can do wherever you want, both options are too fast, what do you prefer??

I prefer to hide it - gracias

**Comment by jmgayosso** [comment]
Done
