### ISSUE TITLE
Organisational Page - KPIs [S]

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#568]
**Summary:**
As a DHO user I would like to see an overview page about the Hypha Organization with links to organisational pages (e.g. treasury, archetypes, all projects, etc...) in order to understand the organisation better and navigate to pages with more info. 

**Description:**

old URL:

new URL:
/organization

**Acceptance Criteria:**

KPIS: leades to /search result page with respective filter activated
- [x] Active Assignments
- [x] Active Quests
- [x] Recent Payouts
- [x] Active Badges
- [x] Recent Strategies (separate story https://github.com/hypha-dao/dho-web-client/issues/625)

**Ressources:**

Attachement: 

https://docs.google.com/document/d/1KHC_6Cha8MC2NMKDV6XRXKuZGS7kPdVGuLtF_kSYvbU/edit

https://xd.adobe.com/view/a31415be-a724-49ad-8070-1a7d67dd6880-f647/screen/d4abf3d4-9283-4877-8d6d-8a80653bd50c?fullscreen

https://xd.adobe.com/view/d802317c-bf4d-4084-a77e-b6c2d046d49c-8d51/

![image](https://user-images.githubusercontent.com/75991832/137363423-fd647040-5a7f-4e34-a9a8-621ff54bb96e.png)

**Comment by jmgayosso** [comment]
The Kpis of this page should have the same design that home page kpis, right?

**Comment by leonieherma1** [comment]
@jmgayosso hide Quest and Policy Widget

**Comment by jmgayosso** [comment]
> @jmgayosso hide Quest and Policy Widget

Done!

**Comment by jmgayosso** [comment]
> @jmgayosso is it on staging yet?

what do you mean? I will push a new version with all my changes today later, I will let you know

**Comment by leonieherma1** [comment]
> > @jmgayosso is it on staging yet?
> 
> what do you mean? I will push a new version with all my changes today later, I will let you know

yes perfect, let me know when its done (today or tomorrow)
