### ISSUE TITLE
Proposals showing up 30 min after proposing

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#600]
### Current Behavior

When I propose a new assignment or contribution it takes +/- 30 minutes to show up in the frontend. 

### Expected Behavior

The proposal / contribution should show up instantly. 

### Steps To Reproduce

1. Login to the DHO
2. Create a new Contribution or Assignment
3. Click Propose
4. Wait 

### What browsers are you seeing the problem on?

Chrome

### How critical do you perceive the bug?

Major

**Comment by pugakn** [comment]
I talked with @Gerard097 and it might be that dgraph is not replicating the data immediately for some reason.

**Comment by leonieherma1** [comment]
> I talked with @Gerard097 and it might be that dgraph is not replicating the data immediately for some reason.

Ok thanks. What are next steps / who can look into this?

**Comment by Gerard097** [comment]
> 

@sebastianmontero Is looking into it
