### ISSUE TITLE
Member List - Filter Search Functionality (S)

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#638]
**Summary**
As a DHO user I would like to be able to search for a member.

**Design**
https://xd.adobe.com/view/0d46ebe4-2b4b-437b-86f7-c3c5c18e05ac-5815/?fullscreen&hints=off

![image](https://user-images.githubusercontent.com/75991832/152033404-c3ac7008-afac-4645-a429-29fe97bc9835.png)

**Comment by leonieherma1** [comment]
@pugakn the search doesnt work for me yet. We have Jose Maria as a Member but when I search for Jo nothing shows up

<img width="1449" alt="image" src="https://user-images.githubusercontent.com/75991832/155203270-d0b98286-ef6d-4a4a-9788-f1c925473757.png">

**Comment by pugakn** [comment]
@leonieherma1 Currently you need to write the whole exact same username because is the only way to filter it on the backend, let me check with @Gerard097 if we can do something about that
