### ISSUE TITLE
Proposal Creation Wizard - Recurring Activity / Role Assignment (M)

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#646]
**Summary:**
As a DHO user I would like to be able to easily set up new proposals so I can actively contributing in governing Hypha.

**Description:**

old URL:
sidebar

new URL:
/proposals/create?type=role-assignment: Apply for Role

**Acceptance Criteria**
- [x] Headline: Chose an option

Step 1 "Proposal Type": 

Card Level 1:
- [x] Recurring Activity
- [x] Icon (Calendar)
- [x] Copy: Propose a recurring payout per cycle for doing regular work in a circle.

Card Level 2:
- [x] Headline: Chose a proposal type
- [x] Role Assignment
- [x] Icon (Person in a box)
- [x] Copy: A role assignment is a set of activities based on an archetype. It can be revisited on a regular basis (e.g. every 3 month) and extended if the objectives and key results have been met.

Card Level 3:
- [x] Headline: Chose a Role Archetype
- [ ] Dorpdown: Role Archetypes (alphabetically)
- [x] List of all Role Archetypes with Title, Description and Salary Band

Step 2 "Description":
- [x] Field 1: Title
- [ ] ~ Field 2: Circle Dropdown~
- [x] Field 3: Description Field (Objectives & Key Results combined)
- [x] Field 4: Attachment

Step 3 "Date & Duration"

- [x] Date Picker for start date 
- [x] Duration in cycles as boxes

Step 4 "Compensation":

- [x] Headline: Chose your commitment level
- [ ] Copy: to be done
- [x] Commitment Level Slider & Field

- [x] Chose the deferral amount
- [ ] Copy; to be done
- [x] Slider & Field

- [x] Headline: Salary Calculation
- [x] Field 1: HUSD
- [x] Field 2: Hypha
- [x] Field 3: HVoice
- [x] Field 4: Total USD equivalent
- [x] Toggle: Custom Compensation

Step 5 "Review"
- [x] Label "Role Assignment"
- [x] Title
- [x] Subheadline: Role Archetype 
- [x] Date & Duration, Deferred Amount, Commitment
- [x] Description
- [ ] ~Attachment~
- [x] Compensation
- [ ] ~Publish to Staging Button~
- [x] Publish Button

Design: 
https://xd.adobe.com/view/2e6dc275-76dc-4722-a922-cc60c5d7d653-7b3e/screen/28f557eb-70cf-4115-bb95-a34b9bea84f2/

**Comment by jmgayosso** [comment]
@leonieherma1 I moved this to testing because we do not ned atachment for this process
