### ISSUE TITLE
Proposal Creation Wizard - Organizational Asset / Badge Type [M]

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#648]
**Summary:**
As a DHO user I would like to be able to easily set up new proposals so I can actively contributing in governing Hypha.

**Description:**

old URL:
sidebar

new URL:
/proposals/create?type=badge-type: Create a Badge

**Acceptance Criteria**
- [x] Headline: Chose an option

Step 1 "Proposal Type": 

Card Level 1:
- [x] Recurring Activity
- [x] Icon (Calendar)
- [x] Copy: Propose a recurring payout per cycle for doing regular work in a circle.

Card Level 2:
- [x] Headline: Chose a proposal type
- [x] Badge Type
- [x] Icon (Badge)
- [x] Copy: Badges can be assigned to people to indicate certain skills, perks, capabilities and general reputation.

Step 2 "Description":
- [x] Field 1: Title 
- [ ] Field 2: Badge Restriction Dropdown
- [x] Field 4: Description Field (Combined with Powers, Perks & Possibilities Field)

Step 3 "Icon Selection"
- [x] Headline: Chose an icon
- [x] Search Bar
- [x] List of Icons
- [x] Load more button

Step 4 "Compensation":
- [x] Headline: Multiplier
- [x] Field 1: HUSD
- [x] Field 2: Hypha
- [x] Field 3: HVoice

Step 5 "Review"
- [x] Label "Badge"
- [x] Title
- [x] Icon
- [x] Compensation
- [ ] ~Publish to Staging Button~
- [x] Publish Button

Design: 
https://xd.adobe.com/view/2e6dc275-76dc-4722-a922-cc60c5d7d653-7b3e/screen/098ae22b-b056-4d24-a734-c1180f36199b/

**Comment by jmgayosso** [comment]
Hi @leonieherma1 for badge type we dont have badge restrictions and purpose fields on backend side, should I move this to Test???

**Comment by jmgayosso** [comment]
Also for Badge type we dont have duration

**Comment by jmgayosso** [comment]
Also for Badge type we dont have duration

**Comment by leonieherma1** [comment]
> Also for Badge type we dont have duration

no duration but we have the badge restriction: 
<img width="538" alt="image" src="https://user-images.githubusercontent.com/75991832/154586257-d01480f0-39bc-4700-9602-3d2555a4a2e8.png">

**Comment by leonieherma1** [comment]
> Hi @leonieherma1 for badge type we dont have badge restrictions and purpose fields on backend side, should I move this to Test???

Yes purpose can be in the description (one big field)

**Comment by jmgayosso** [comment]
> > Also for Badge type we dont have duration
> 
> no duration but we have the badge restriction: <img alt="image" width="538" src="https://user-images.githubusercontent.com/75991832/154586257-d01480f0-39bc-4700-9602-3d2555a4a2e8.png">

Ok I will ping gerry!

**Comment by jmgayosso** [comment]
Hi @leonieherma1 I will move this to test, we dont need duration for this proposal type I implemented the badge restrictions
