### ISSUE TITLE
Proposal Creation Wizard - Organizational Asset / Role Archetype [M]

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#649]
**Summary:**
As a DHO user I would like to be able to easily set up new proposals so I can actively contributing in governing Hypha.

**Description:**

old URL:
sidebar

new URL:
/proposals/create?type=assignment: Create Role

**Acceptance Criteria**
- [x] Headline: Chose an option

Step 1 "Proposal Type": 

Card Level 1:
- [x] Recurring Activity
- [x] Icon (Calendar)
- [x] Copy: Propose a recurring payout per cycle for doing regular work in a circle.

Card Level 2:
- [x] Headline: Chose a proposal type
- [x] Role Assignment
- [x] Icon (Person in a box)
- [x] Copy: A role assignment is a set of activities based on an archetype. It can be revisited on a regular basis (e.g. every 3 month) and extended if the objectives and key results have been met.

Card Level 3:
- [x] Headline: Chose a Role Archetype
- [ ] ~Dorpdown: Role Archetypes (alphabetically)~
- [x] List of all Role Archetypes with Title, Description and Salary Band

Step 2 "Description":
- [x] Field 1: Role Archetype Name
- [ ] ~ Field 2: Purpose~
- [x] Field 3: Description Field (Accountabilities inside this field as a placeholder)
- [ ] Field 4: Attachment

Step 3 "Compensation":

- [x] Headline: Chose Salary Band
- [ ] ~Copy: to be done~
- [x] Dropdown: Salary Bands

- [x] Headline: Select Role Capacity
- [ ] ~Copy: to be done~
- [x] Text Field

- [x] Headline: Chose the minimum deferred amount
- [ ] Copy: to be done
- [x] Deferred Amount Slider & Field

- [x] Headline: Salary Calculation (all fields prefilled)
- [x] Field 1: HUSD
- [x] Field 2: Hypha
- [x] Field 3: HVoice
- [x] Field 4: Total USD equivalent

Step 5 "Review"
- [x] Label "Role Archetype"
- [x] Title
- [x] Salary Band 
- [x] DMin deferred amount
- [x] Role Capacity
- [x] Description
- [ ] ~Attachment~
- [ ] ~Publish to Staging Button~
- [x] Publish Button

Design: 
https://xd.adobe.com/view/2e6dc275-76dc-4722-a922-cc60c5d7d653-7b3e/screen/2ed2c760-d95d-4f18-a53f-082df09ac045/

**Comment by jmgayosso** [comment]
@leonieherma1 I moved this to testing 
- We don't need attachmet for this process
- We don't need Role archetype selector
- The copy is not needed with the new Massimo design
