### ISSUE TITLE
Only DAO Members should be able to login

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#675]
Summary:
Only DAO members should be able to login

Experienced Result:
1. Open https://dao-dev.hypha.earth/#/daoxpr/login
2. Click on "Login"
3. Login as Johnny Hypha (johnnyhypha1 5HwnoWBuuRmNdcqwBzd1LABFRKnTk2RY2kUMYKkZfF8tKodubtK)
4. See Dashboard
5. See Sidebar with username @ null 

<img width="1781" alt="Screenshot 2022-02-17 at 17 47 14" src="https://user-images.githubusercontent.com/75991832/154584954-689a7c1f-899a-43a9-a2ed-37b6694b5cbf.png">

<img width="1002" alt="Screenshot 2022-02-17 at 17 47 44" src="https://user-images.githubusercontent.com/75991832/154584969-297b97b8-c4ae-47ea-93c6-3627d1920ade.png">

<img width="1781" alt="Screenshot 2022-02-17 at 17 48 08" src="https://user-images.githubusercontent.com/75991832/154584980-e94e7133-ef41-4d63-a076-fe423597a927.png">

Expected Result:
When I try to login to a DAO that I am not member of I should get an error message. 
"Looks like you are not a member of this DAO yet. Click here to register (link to /register).
<img width="240" alt="image" src="https://user-images.githubusercontent.com/75991832/154584896-b6754752-4113-4a0b-bda9-2b66a637becd.png">

https://xd.adobe.com/view/dff2df13-c8f4-480e-8a2e-2a74a54a6db5-8aa1/screen/a107c024-b148-437e-92b6-af9a1d9b414d/

**Comment by jmgayosso** [comment]
Hi I remember ask before, you said any one can login into any dao, So I am confused. we have any user flow for this? what the idea is if you aren't member of the dao, you can see the same that a guest user

**Comment by leonieherma1** [comment]
@jmgayosso yes you can see every dho "as a guest" and you will have those rights:

https://github.com/hypha-dao/dho-web-client/issues/679

You should not be able to login if you are not a member.

Exception: you can login with your Telos account, then you can have the same view as a guest (but will see a button that says "become member": https://github.com/hypha-dao/dho-web-client/issues/680

**Comment by jmgayosso** [comment]
@leonieherma1 Hi! What is the status for this ticket? I thinks this is a confusion, could you try again please???

**Comment by leonieherma1** [comment]
@jmgayosso yes I think it is ok now. I will close the issue.
