### ISSUE TITLE
Profile Widgets - Empty State (S)

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#682]
**Summary**
As a DHO user I would like to see placeholder copy when my profile widgets are emtpy.

**Acceptance Criteria**

Own profile:

- [x] Assignments: "Looks like you don't have any active assignments. You can browse all Role Archetypes (link to /organization/assets/role) and apply for a Role Archetype."
- [x] Contributions: Looks like you don't have any contributions yet. You can create a new contribution in the Proposal Creation Wizard. (link to /proposals/create with "Generic Contribution" preselected.  
- [x] About: "Write something about yourself here and let other users know about your purpose."
- [x] Recent Votes: "You haven't cast any votes yet. Go and take a look at all proposals (link to /proposals) and support a contribution, assignment or badge."
- [x] Badges: "No Badges yet - apply for a Badge here (link to /organization/assets/badge).

Other Profile:
- [x] Assignments: "No active or archived assignments to see here."
- [x] Contributions: Hide when empty
- [x] About: "Looks like {username} didn't write anything about their purpose in this DAO yet."
- [x] Recent Votes: "No votes casted yet"
- [x] Badges:  Hide Component if empty

Design:
https://xd.adobe.com/view/2e6dc275-76dc-4722-a922-cc60c5d7d653-7b3e/screen/6af6ade4-6f28-4939-a667-1740c0d6367d

<img width="1002" alt="image" src="https://user-images.githubusercontent.com/75991832/154602267-1164c71b-73a1-41e8-ba80-1bdfaf1fb6b4.png">

**Comment by leonieherma1** [comment]
@pugakn 

The Vote Button takes me to an error page:

<img width="968" alt="image" src="https://user-images.githubusercontent.com/75991832/157363909-361cb5e3-83bf-46a6-b9cd-5e9c48fae66b.png">

https://dao-dev.hypha.earth/#/daoxpr/organization/proposals

<img width="1393" alt="image" src="https://user-images.githubusercontent.com/75991832/157363955-c677a5ca-80a7-4c47-9c70-93335c1f660c.png">

**Comment by leonieherma1** [comment]
@pugakn 
the copy for the Assignment widget for other peoples profile is missing:

<img width="1326" alt="image" src="https://user-images.githubusercontent.com/75991832/157364288-b16c5409-3db9-42d3-97f8-240d678a0e53.png">
https://dao-dev.hypha.earth/#/daoxpr/@danielpoot22

**Comment by pugakn** [comment]
Assignment widget is related to this other story https://github.com/hypha-dao/dho-web-client/issues/799
