### ISSUE TITLE
Re-enable capacity limit for role-assignment

### ISSUE THREAD

**Issue by sceenius** [hypha-dao/dho-web-client#69]
Prior action (Max):

We have temporarily disabled this functionality due to a bug in computing capacity when extending/editing objects.. This has been addressed now and we can activate this check again upon 1) creation of the proposal and 2) submitting of the proposal. 

We will come back to this in the week of Sep 21 to allow for some user cleanup time.

New action (Joachim):

We are now re-enabling this capacity limit. 

This will also include removal of the "Now Hiring" ribbon ~~and Apply button~~.

Capacity is calculated as the sum of all active assignments for a given role. Once the sum total is larger than the capacity of the role, an error occurs and the applicant cannot apply for the role. 

We can use the existing functionality we had in place before, and add the additional features of (1) removing the ribbon "Now Hiring" ~~and the button for "Apply"~~.

**Comment by sceenius** [comment]
@gregory-latinier Is this on test? I didn't see this implemented, here's what I did:

1) Applied for Role "TEst 5 role"
2) Voted the assignment in at 100& commitment
3) Applied for same role again
4) Voted this in as well

Expected: 1.2 capacity limit would not allow me to propose the 2nd time. I also see "Now hiring" on all approved roles, I'm sure some are taken already and Apply should be hidden.

**Comment by sceenius** [comment]
Also, if I recall correctly, we are not comparing against individual periods for availability, only total commitment for current role fillers. With the shorter assignment periods (3 months) we also don't need this anymore (for now), methinks.

**Comment by gregory-latinier** [comment]
I'm not sure what you're expecting actually.
I though this issue had for purpose to solve the committed % setting verification when applying to a role.
So I re-enabled the verification in the UI and that's it.
Do you want me to add the field when we create a role too ?

**Comment by sceenius** [comment]
@gregory-latinier The second thing was a UI change

> This will also include removal of the "Now Hiring" ribbon and Apply button.

in addition to the check so you don't even get to the error. 

If that is a complex query, I can take it out and we do it later. Let me know.

**Comment by gregory-latinier** [comment]
Yes, as always this type of things requires me to query all the assignments.
So we have to wait for dgraph to be finalized

**Comment by sceenius** [comment]
Yes, let's just remove that for now.
