### ISSUE TITLE
The Timezone Bug

### ISSUE THREAD

**Issue by sceenius** [hypha-dao/dho-web-client#71]
Users from a different timezone (ahead, e.g. Australia or New Zealand) see the claim button and when pressed get an error message.

![image](https://user-images.githubusercontent.com/24725582/92734123-40e17880-f346-11ea-9ecc-2d83d445e3e3.png)

**Comment by gregory-latinier** [comment]
The only way to check is it wait for the end of the claiming period or control the countdown value

**Comment by sceenius** [comment]
I don't know how to test this.. let's release if you think this is fixed.
