### ISSUE TITLE
Design Feedback Proposal Detail Page (S)

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#718]
**Summary**

- [x] check column width of main column and side column. Should be the same ratio as on e.g. Proposal List or Homepage. Overall 1270px wide.
- [x] Make Voting widget "longer" / add spacing between buttons and copy. 
- [x] Add more spacing above "description"
- [x] Voting widget: Date should be aligned with the word "Rejected" / "Passed"
- [x] Remove Commitment level for "Generic contribution"

Please check the designs to make it really look 100% like the design.
https://xd.adobe.com/view/2e6dc275-76dc-4722-a922-cc60c5d7d653-7b3e/screen/9e4d3c8c-ea69-46b9-a065-e1dcf85fd9a6/

**Comment by leonieherma1** [comment]
@DaniPoot I am missing my username here:

<img width="941" alt="image" src="https://user-images.githubusercontent.com/75991832/158091585-9c492839-2778-424b-a609-3a56c0f9862e.png">


Design:
<img width="580" alt="image" src="https://user-images.githubusercontent.com/75991832/158091608-ec43aec9-de23-45b4-b735-974224ad98bc.png">

**Comment by jmgayosso** [comment]
> @DaniPoot I am missing my username here:
> 
> <img alt="image" width="941" src="https://user-images.githubusercontent.com/75991832/158091585-9c492839-2778-424b-a609-3a56c0f9862e.png">
> 
> Design: <img alt="image" width="580" src="https://user-images.githubusercontent.com/75991832/158091608-ec43aec9-de23-45b4-b735-974224ad98bc.png">

Hi @leonieherma1 could your describe you steps to replicate this issue please, works for me. Do you know the proposal id???  this is in the url

**Comment by leonieherma1** [comment]
@DaniPoot sure.

1. Go to https://dao-dev.hypha.earth/cooldao/proposals/
2. Check login with Anchor (leoniefeb252)
3. Click on the first proposal ID 655 (https://dao-dev.hypha.earth/cooldao/proposals/655)
4. It happens for my own proposal (I see Pugas and your names on the other proposals)

**Comment by jmgayosso** [comment]
@leonieherma1 thanks Leonie! now I can replicate it! I'm going to take a look on it!

**Comment by jmgayosso** [comment]
@leonieherma1 Do you have configured profile picture and custom name for leoniefeb252???? I changed my account name to 152 becasue was 'leoniefeb252', so maybe you confused accounts

**Comment by leonieherma1** [comment]
@jmgayosso no the problem is not the wrong name but no name shows up next to the avatar:

<img width="1532" alt="image" src="https://user-images.githubusercontent.com/75991832/158267108-07ef2fd4-ab2e-44c4-b55f-1ff769c3914f.png">

**Comment by jmgayosso** [comment]
> @jmgayosso no the problem is not the wrong name but no name shows up next to the avatar:
> 
> <img alt="image" width="1532" src="https://user-images.githubusercontent.com/75991832/158267108-07ef2fd4-ab2e-44c4-b55f-1ff769c3914f.png">

Yes, I mean if you dont have custom name in your profile account the component will show nothing

**Comment by leonieherma1** [comment]
@jmgayosso I am getting a transaction error when I try to update my profile picture. Lets close it for now and see if it happens again. thank you
