### ISSUE TITLE
[governance] Add HVOICE decay function

### ISSUE THREAD

**Issue by sceenius** [hypha-dao/dho-web-client#73]
Rieki: 1 yr half-life for voice, applied each phase... 
This way we can just apply the same %decay to all HVoice and don't have to track when voice came in...

https://blog.springrole.com/how-eosio-vote-decay-works-7becb5f77048
By implementing “Vote Decay” the power of each vote cast halves every year (i.e. 365 days). In order to re-assert the strength of each vote, a voter must re-cast their vote every single week. Now this has the potential to make each and every vote count and circumvent the “free rider problem” by giving the voters a chance to re-evaluate their vote and change it if needed.

https://www.researchgate.net/publication/305074253_Measuring_Spatial_Accessibility_of_Health_Care_Providers_-_Introduction_of_a_Variable_Distance_Decay_Function_within_the_Floating_Catchment_Area_FCA_Method/figures?lo=1
![image](https://user-images.githubusercontent.com/24725582/92761067-49927880-f35f-11ea-8b80-ccd85d0cc3d4.png)

Joachim: Vote decay + vote acquisition

**Comment by sceenius** [comment]
This function requires more socializing and 1-2 months of development time. 

2 approaches - change the HVOICE directly via historical decay or create a function(HVOICE, last activity) and natural decay

**Comment by leonieherma1** [comment]
Is this the same as https://github.com/hypha-dao/dao-contracts/issues/36? (Cleaning up the boards) @sceenius

**Comment by n13** [comment]
3rd approach si what EOS did, factor F on HVOICE payout which doubles every year. Same effect ;) No one loses vote but they get diluted out.
