### ISSUE TITLE
Error Messages & User Feedback (M)

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#739]
**Summary**
As a DHO user I would like to know if my actions worked or if a error occured.

**AC**
Show error or success message according to styleguide for the following actions:

- [ ] Transaction successful (green)
- [ ] Transaction processing
- [ ] Transaction error - please check the help page
- [ ] Link copied to your clipboard

**Design:**
https://xd.adobe.com/view/dff2df13-c8f4-480e-8a2e-2a74a54a6db5-8aa1/screen/3606a5a8-442e-41b6-886d-62be151ad73c/

**Comment by leonieherma1** [comment]
@pugakn please update styling so the error message is not cut off by sidebar:

<img width="1764" alt="image" src="https://user-images.githubusercontent.com/75991832/158092505-fe46a4cc-acd9-4849-b0f2-14aa58394977.png">

**Comment by pugakn** [comment]
Fixed
