### ISSUE TITLE
Small Bugs / Feedback Creation Wizard & Proposal List

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#742]
**Summary**
Please check bugs / feedback from Design Meeting (March 3rd)

**Acceptance Criteria**
Proposal List:
- [x]  Quorum not updating after vote
- [x] x to close header not working (on all pages)

Proposal Creation Wizard:
- [x] Placeholder copy should be inside the fiels (I will send you the final copy for now you can take the copy from the design) https://xd.adobe.com/view/2e6dc275-76dc-4722-a922-cc60c5d7d653-7b3e/screen/51af5355-7c2f-4a44-b621-73890f8b5e3b/
- [x] Headline missing before first step "New Proposal"
- [x] Button "prev step" on the last screen in the proposal wizard should be inside the white box like on all other screens (not outside)
- [x] After publishing a proposal you should redirect to /proposals list

**Comment by jmgayosso** [comment]
@leonieherma1 the quorum update is working just I changed to 2 decimals to note small votes
![Screen Shot 2022-03-07 at 11 13 17](https://user-images.githubusercontent.com/58195358/157083992-7ec9939c-f2eb-4791-8461-c89579e3d08e.png)

**Comment by leonieherma1** [comment]
@jmgayosso @DaniPoot can't test this because when I click on "create proposal" I get redirected to login page (PK), please check that issue so I can start testing.

**Comment by leonieherma1** [comment]
@jmgayosso @DaniPoot  the placeholder text in the description is still missing:

<img width="1148" alt="image" src="https://user-images.githubusercontent.com/75991832/157792344-423459f7-07a8-4d49-8d0f-620c37dd6706.png">


Hypha applies a pattern of Objectives and Key Results (OKRs) to all contributions. 
Please state the Objective (something you hoped to accomplish) as well as 2-5 Key Results* for this contribution, which are measurable expressions of success justifying this payment. 
We also recommend to add a link to other supporting documentation in the text box below.

**Comment by jmgayosso** [comment]
@leonieherma1 regarding placeholders, will be dynamic for each DHO??? I mean this placeholder looks specific for Hypha DHO

**Comment by leonieherma1** [comment]
@jmgayosso yes good question. I think for MVP we will change the copy to:

"Please state the Objective (something you hoped to accomplish) as well as 2-5 Key Results for this contribution, which are measurable expressions of success justifying this payment.
We also recommend to add a link to other supporting documentation in the text box below."

Is it possible to have a field later in the settings screen with different copy for every DHO?

**Comment by jmgayosso** [comment]
> @jmgayosso yes good question. I think for MVP we will change the copy to:
> 
> "Please state the Objective (something you hoped to accomplish) as well as 2-5 Key Results for this contribution, which are measurable expressions of success justifying this payment. We also recommend to add a link to other supporting documentation in the text box below."
> 
> Is it possible to have a field later in the settings screen with different copy for every DHO?

Ok I will change the copy, sure Leonie to do this we have to add the new description_creation_proposal field in backend and front side

**Comment by leonieherma1** [comment]
@jmgayosso yes looks great.
