### ISSUE TITLE
Multi Sig Page (M)

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#744]
**Summary**
As a Hypha DHO dev who has the power to sign releases, I would like to see the Mutli Sig Page.

**Description**
Some DHO users have the permission to sign new releases. Those users should see the Multi Sig Widget in their profile and be able to see the Multi Sig Page and sign transactions there.

https://dho.hypha.earth/#/multi-sig

**AC**
- [x] Headline: Multi Sig
- [x] Table with Type, Name, Proposer, Developer, Notes, Links, Approvers

Widget:

State 1 - Active PRs to sign: 
- [x] Headline: Click on your initials to sign a transaction
- [x] Description: Multisig enables us to sign transactions in a secure way. To release new PRs we need at least 3 signatures. 

State 2 - After clicking on initials:
- [x] Button: Sign

State 3 - No Transactions to sign:
- [x] Headline: No Transactions to sign at the moment
- [x] Description:  Multisig enables us to sign transactions in a secure way. To release new PRs we need at least 3 signatures. 

**Design:**
https://xd.adobe.com/view/2e6dc275-76dc-4722-a922-cc60c5d7d653-7b3e/screen/4cf9cb4d-9a03-45f0-9c74-54e0b2e860ba/

Original Story about Multi Sig:
https://github.com/hypha-dao/dho-web-client/issues/79

**Comment by leonieherma1** [comment]
@arsenijesavic where can I see / test that page? When I click on the Multi Sig Widget in my profile in the cooldao I see this:
https://dao-dev.hypha.earth/multi-sig

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/75991832/158935405-33b08266-f5e9-4674-b97a-ae079d1a34f3.png">


Thanks

**Comment by arsenijesavic** [comment]
@leonieherma1 when https://github.com/hypha-dao/dho-web-client/pull/838 is merged into develop
