### ISSUE TITLE
Project Detail Page - Withdraw (S)

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#745]
**Summary:**
As a DHO user I would like to be able to withdraw my own badge types, badge assignments, role archetypes & role assignments.

https://dao-dev.hypha.earth/#/cooldao/proposals/id

**Acceptance Criteria:**

- [x] Withdraw button in "Voting Widget"
- [x] Widget: Are you sure? Yes, I changed my mind (=cancel)
- [x] Redirect to "Proposal Detail Page" status "voting"
- [x] Add label "suspension"
- [x] After voting period ended show grey widget "suspended" if vote passed
- [x] If vote did not pass keep assignment active

**Attachement:** 

https://xd.adobe.com/view/2e6dc275-76dc-4722-a922-cc60c5d7d653-7b3e/screen/cfe7117f-3faa-4949-8ffd-b39df0044479

**Comment by DaniPoot** [comment]
Hi, @leonieherma1 I have a question about this part. The grey widget is a different widget because on the design page we have a red one ( #534 ). It's only for confirming the correct color for that. And are correct the types for proposal? I tried to withdraw a badge and the error says it is only for assignments. @jmgayosso

**Comment by leonieherma1** [comment]
@Gerard097 I think you also made it possible to withdraw badges? Let's discuss the design question later befor standup

**Comment by leonieherma1** [comment]
@DaniPoot on my own assignment I can only withdraw. Please remove "suspend" button.

<img width="304" alt="image" src="https://user-images.githubusercontent.com/75991832/159931964-95e9ccd6-6be3-41db-af37-d97e92cf4dc3.png">



On another person I can only suspend (not withdraw)

Withdraw = delete my own assignment
Suspend = delete some other persons assignment

**Comment by leonieherma1** [comment]
@DaniPoot When I click "withdraw" and then "yes" nothing happens, I just see this screen:

<img width="1382" alt="image" src="https://user-images.githubusercontent.com/75991832/160006191-2128e719-8621-4bb6-bac4-470a1c16330f.png">

**Comment by leonieherma1** [comment]
@DaniPoot @jmgayosso it's not working on this one:

https://dao-dev.hypha.earth/cooldao/proposals/6431

<img width="942" alt="image" src="https://user-images.githubusercontent.com/75991832/161614607-2ba43401-cdfd-4bfa-b24b-70147e70f37c.png">

Archived documents should be able to suspend and withdraw too.

**Comment by jmgayosso** [comment]
> https://dao-dev.hypha.earth/cooldao/proposals/6431

@leonieherma1 this is an issue from backend, @Gerard097 could you take a look please??
