### ISSUE TITLE
Dynamic Title on Homepage & Organizational Page

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#748]
**Summary**
As a DHO user I would like to see the correct DAO Name and description on the Homepage & Organizatonal Page Header

**Acceptance Criteria**
Homepage:

- [x] Header Title: Welcome to {DAO Name}
- [x] Description: Take manually for now (later from DHO Creation Process)

Organisational Page:

- [x] Header Title: The purpose of {DAO Name}
- [x] Description: Create manually now (later from DHO Creation Process)

<img width="1074" alt="image" src="https://user-images.githubusercontent.com/75991832/156696543-8456bb20-c93c-40ab-96c4-a3a1e48ad379.png">

**Comment by jmgayosso** [comment]
@leonieherma1  the description will be in dgraph? so we have to retrive this from graphql, right?

**Comment by leonieherma1** [comment]
> @leonieherma1 the description will be in dgraph? so we have to retrive this from graphql, right?

I don't know where the descrription will be. It will be added to while creating a dho: https://xd.adobe.com/view/27bc7fff-1845-449c-913a-4ecfb3c9461c-72ef/screen/c0b2078b-7a17-4c4f-9004-c8dd57d4c273/
But not sure where it will be stored
