### ISSUE TITLE
Login with wrong username and wrong password (S)

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#754]
Reproduce:
1. Go to https://dao-dev.hypha.earth/#/testdao/login
2. Click "Login" and "Private Key"
3. Use a random username that does not exist: randomuser33
4. Use a random key e.g: 5JTDC4qqTMn5pbuWB8563qFKimZK2moX3nZk3GHk1cikeasdozp

Experienced behaviour:
I can login and see the "guest" screen with "Logout" & "Become Member" Button

Expected behaviour:
1. Error message "username doesnt exist - register here" (link to /register)
2. Error message "Invalid private key"

<img width="1782" alt="image" src="https://user-images.githubusercontent.com/75991832/156831962-ebf165aa-5807-4d40-b03b-7f3445676010.png">

**Comment by pugakn** [comment]
We no longer use PK login
