### ISSUE TITLE
Project Detail Page - "You didn't vote" Button

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#764]
Reproduce:
1. Go to e.g. https://dao-dev.hypha.earth/#/testdao/proposals/598 (or any proposal whose voting period is over and you did not vote)
2. Check the "You did not vote" Button in the Voting Widget
3. It looks like a button but is not clickable

**Acceptance Criteria**

- [x] Remove Mouse "finger" so it doesn't seem clickable
- [x] Remove outline of Button so it is just text

<img width="487" alt="image" src="https://user-images.githubusercontent.com/75991832/157238209-497e5e90-44b7-4a7b-ba24-e7cdb90f9ca4.png">

**Comment by leonieherma1** [comment]
@DaniPoot sorry, this was my mistake. Please do use the outline for the button. Use the "disabled" style from the styleguide:

https://xd.adobe.com/view/dff2df13-c8f4-480e-8a2e-2a74a54a6db5-8aa1/screen/273c0266-a967-46e4-850d-514bf0b16522/

<img width="208" alt="image" src="https://user-images.githubusercontent.com/75991832/159930938-4a994f83-c695-42ee-b6a1-cf8a42c48efc.png">

**Comment by leonieherma1** [comment]
@DaniPoot @jmgayosso now I dont see the you didnt vote test at all anymore

<img width="315" alt="image" src="https://user-images.githubusercontent.com/75991832/161609047-c6c228a5-c42e-4cf0-b1f6-9b2d49e8b1a4.png">

https://dao-dev.hypha.earth/hypha/proposals/7608

**Comment by jmgayosso** [comment]
> @DaniPoot @jmgayosso now I dont see the you didnt vote test at all anymore
> 
> <img alt="image" width="315" src="https://user-images.githubusercontent.com/75991832/161609047-c6c228a5-c42e-4cf0-b1f6-9b2d49e8b1a4.png">
> 
> https://dao-dev.hypha.earth/hypha/proposals/7608

Yes, We have this just for rejected proposals, not for archived, but we will add them
