### ISSUE TITLE
(PK) Create new proposal takes me to /login (S)

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#765]
Reproduce:
1. Go to e.g. https://dao-dev.hypha.earth/#/testdao/
2. Click "New Proposal" in the sidebar

Expected behaviour:
I go to /proposals/create and can create a proposal

Experienced behaviour:
I go to /login

**Comment by pugakn** [comment]
We no longer use PK login

**Comment by leonieherma1** [comment]
@pugakn yes perfect, will close it now
