### ISSUE TITLE
Explore Page - New DAOs don't show up

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#766]
Reproduce:
1. Go to e.g. https://dao-dev.hypha.earth/#/testdao/explore
2. Check if all DAOs are there (e.g. Hypha)

Expected behaviour:
See all new DAOS (e.g. hypha)

Experienced behaviour:
I don't see all new DAOs (e.g. hypha)

**Comment by leonieherma1** [comment]
@jmgayosso @DaniPoot I noticed two things:

1. Search: When I look for "hypha" I see 5 DHOs but not the Hypha DHO
<img width="1442" alt="image" src="https://user-images.githubusercontent.com/75991832/157792986-2413d0fe-7cae-4e56-a7ee-c47d0bb82334.png">


2. When I open the page I don't see the Hypha DHO. When I change the filter to "alphabetically" it shows up. Is ther paginatin or a "see more Button"- maybe not all DHOs are showing up on the first load?

**Comment by jmgayosso** [comment]
Hi @leonieherma1 ! @DaniPoot uploaded the fix for this issue, can you try again and let us know if works for you please?

**Comment by leonieherma1** [comment]
@jmgayosso How many DAOs do we have at the moment? I always see 18 but not sure if there should be more loading.... Also when I search for "newdao" - the New DAO comes first but also those show up that have nothing to do with "new" or "dao" - e.g. "scheduletest" is number 2 in the results

![image](https://user-images.githubusercontent.com/75991832/157922237-b45e0b79-dc56-4b06-9f3e-96070b633b12.png)

**Comment by jmgayosso** [comment]
Hi @leonieherma1 thanks for the FB! yes, just there are 18 daos, We now are working to user regex in the search for dos, this would improve the beahaivor, I will let you know today when you can test on dev.

**Comment by jmgayosso** [comment]
@leonieherma1 done, now you can test it in dev

**Comment by leonieherma1** [comment]
@jmgayosso works like a charm!! closing the issue
