### ISSUE TITLE
Navigation should not be clickable when I am only member in one DAO or guest

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#768]
Reproduce:
1. Go to e.g. https://dao-dev.hypha.earth/#/testdao/login
2. Click continue as guest
3. Click in the Navigation on "DA" 

Experienced behaviour:
The blue circle "DA" is clickable and the navigation items (home, propoals, members, organization) disappear. But no other DAOs show up, since I am a guest (or member of only one DAO).

Expected behaviour:
The blue circle "DA" should not be clickable, because I am not a member of any other DAO.

<img width="285" alt="image" src="https://user-images.githubusercontent.com/75991832/157239875-e751d18c-4892-48c7-9f70-8f6f026000ca.png">

**Comment by jmgayosso** [comment]
@leonieherma1  done I will upload this later today with other fixes

**Comment by leonieherma1** [comment]
> @leonieherma1 done I will upload this later today with other fixes

@jmgayosso yes please give me an update in discord when the changs are life and i can test

**Comment by leonieherma1** [comment]
@jmgayosso My account leoniefeb252 is member of many DHOs:
<img width="529" alt="image" src="https://user-images.githubusercontent.com/75991832/157361916-6125fb88-5d63-4072-8295-0ee8bae3cffd.png">


but now the navigation is not clickable:
<img width="435" alt="image" src="https://user-images.githubusercontent.com/75991832/157361946-71feac55-09dc-44eb-901c-18285843d845.png">


Please make it only "not clickable" when I am only a member of one DHO. 

Also please remove the grey overlay and the sign (do not enter). Simply make it not clickable (don't change the mouse)

**Comment by jmgayosso** [comment]
Hi @leonieherma1 could you do a hard refresh and try again please?

**Comment by leonieherma1** [comment]
@jmgayosso perfect
