### ISSUE TITLE
Navigation doesn't show all DHOS (Login with PK)

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#769]
Reproduce:
1. Go to https://dao-dev.hypha.earth/#/hypha
2. Login as Johnny Hypha 
johnnyhypha1
5HwnoWBuuRmNdcqwBzd1LABFRKnTk2RY2kUMYKkZfF8tKodubtK
3. Check sidebar Navigation 

Experienced Behaviour:
I only see one DAO (HY) in the dropdown

Expected behaviour:
I should see all DAOs that Johnny Hypha is member of in the sidebar (e.g bestdao, testdao, bestdaox, etc....)

<img width="327" alt="image" src="https://user-images.githubusercontent.com/75991832/157240340-aabf8649-bead-4a03-ab3e-6810fdc8e3c5.png">

<img width="327" alt="image" src="https://user-images.githubusercontent.com/75991832/157240360-e824050e-ccfc-4571-a26e-5e1ff6a732fc.png">

**Comment by jmgayosso** [comment]
done

**Comment by leonieherma1** [comment]
I will close this because we are not using PK anymore
