### ISSUE TITLE
KPI on homepage links to 404

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#770]
Reproduce:
1. Go to e.g. https://dao-dev.hypha.earth/#/testdao/login
2. Click "continue as guest"
3. Klick on "3 new Proposals" on Homepage (KPI)

Experienced Behaviour:
I should go to /proposals and see 3 proposals

Expected behaviour:
I get to an error page 404 https://dao-dev.hypha.earth/#/not-found

https://dao-dev.hypha.earth/#/not-found

**Comment by jmgayosso** [comment]
@leonieherma1 I can not replicate this issue in  https://dao-dev.hypha.earth/#/testdao/login, can you try again please?

**Comment by leonieherma1** [comment]
@jmgayosso the "new proposal" ist for the last 7 days right?

**Comment by jmgayosso** [comment]
> @jmgayosso the "new proposal" ist for the last 7 days right?

Its correct
