### ISSUE TITLE
Emergency Banner 

### ISSUE THREAD

**Issue by sceenius** [hypha-dao/dho-web-client#78]
Clicking on remove gives me an error:
![image](https://user-images.githubusercontent.com/24725582/92955720-ab241700-f433-11ea-9457-50fcc5aab888.png)

**Comment by sceenius** [comment]
#2 The yellow bg color is not correct, see feature

**Comment by sceenius** [comment]
Lastly, the right slider is showing because of the additional space:
![image](https://user-images.githubusercontent.com/24725582/92955978-1968d980-f434-11ea-86e7-5b53b8eb0735.png)

**Comment by gregory-latinier** [comment]
> Clicking on remove gives me an error:
> ![image](https://user-images.githubusercontent.com/24725582/92955720-ab241700-f433-11ea-9457-50fcc5aab888.png)

@dappdever what could cause this error ?
