### ISSUE TITLE
Login - Remove PK, Scatter, SQRL

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#786]
**Summary**
As a DHO user I should only be able to login via Anchor.

**AC**

- [x] Remove PK field
- [x] Remove Scatter
- [x] Remove SQRL
- [x] Update Copy (to be done)

**Comment by jmgayosso** [comment]
@leonieherma1  just awaiting the copy, should move this to testing? or keep in progress?

**Comment by leonieherma1** [comment]
@jmgayosso you can put it in blocked - i hope I have the copy by monday or tuesday....
