### ISSUE TITLE
Restrict Descriptions of Proposals to 2000 characters

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#788]
**AC**
Restrict Descriptions of all proposal types to max 2000 characters

Backend Story:
https://github.com/hypha-dao/dao-contracts/issues/209

**Comment by leonieherma1** [comment]
@jmgayosso I added over 2000 characters and got the correct error message. Then I deleted most of the characters but the error message didnt go away and I can also not click "next".

<img width="1002" alt="image" src="https://user-images.githubusercontent.com/75991832/157791960-62d97782-9e3c-4ffc-9c2d-eaf673190a46.png">

**Comment by jmgayosso** [comment]
@leonieherma1 I will update this to do easy debugger, now will contain a count of characters in the error message
![Screen Shot 2022-03-11 at 11 19 06](https://user-images.githubusercontent.com/58195358/157915916-73479b82-0217-4dbf-a5b9-045d352cbff9.png)

**Comment by leonieherma1** [comment]
@jmgayosso let me know when I can test

**Comment by jmgayosso** [comment]
@leonieherma1 done, now you can test it on dev
