### ISSUE TITLE
Remove "upload picture" from account creation

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#795]
**AC**

- [ ] Remove "upload picture" from account creation step 3
<img width="854" alt="Screenshot 2022-03-13 at 22 11 21" src="https://user-images.githubusercontent.com/75991832/158093030-507dbadb-00fe-461c-af2e-9e499c2d2d52.png">

**Comment by jmgayosso** [comment]
@leonieherma1 done
