### ISSUE TITLE
Add Warning when I leave proposal creation without saving draft

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#806]
**Summary**
As a DHO user I should get a warning that  when I leave the proposal creation wizard process I will lose my data if I don't click "Save Draft".

**Acceptance Criteria**

- [ ] When I leave a proposal creation without saving show error message on the bottom that says: "Heads up, you are discarding your proposal. Click "Save Draft" if you want to continue working on it later."
- [x] Or do we have the possibility to automatically save the draft when the user leaves the process? Then we should say "Are you sure you want to leave without saving your draft? Button 1: "Leave without saving draft" Button 2:"Save Draft"

Please chose what is easier / faster.

**Comment by jmgayosso** [comment]
Done

**Comment by leonieherma1** [comment]
@jmgayosso it works but when I publish and then leave the draft I see the message:

<img width="1741" alt="image" src="https://user-images.githubusercontent.com/75991832/158722529-33c91d7d-cdb2-4cee-827d-8aeb0e8366e8.png">


But when I already click publish I should not see the message. Only if I exit the flow before I click "Publish"

**Comment by leonieherma1** [comment]
@jmgayosso @pugakn can one of you update the pop up so it looks like the design system:

<img width="1027" alt="image" src="https://user-images.githubusercontent.com/75991832/161609291-8d237c19-c483-4831-9668-63b2ece49672.png">


https://xd.adobe.com/view/dff2df13-c8f4-480e-8a2e-2a74a54a6db5-8aa1/screen/3606a5a8-442e-41b6-886d-62be151ad73c/

**Comment by jmgayosso** [comment]
> @jmgayosso @pugakn can one of you update the pop up so it looks like the design system:
> 
> <img alt="image" width="1027" src="https://user-images.githubusercontent.com/75991832/161609291-8d237c19-c483-4831-9668-63b2ece49672.png">
> 
> https://xd.adobe.com/view/dff2df13-c8f4-480e-8a2e-2a74a54a6db5-8aa1/screen/3606a5a8-442e-41b6-886d-62be151ad73c/

@leonieherma1 I am on it

**Comment by jmgayosso** [comment]
@leonieherma1 its done! will be on the next deploy :-)
