### ISSUE TITLE
Continue Proposal Draft should start where I left

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#807]
Reproduce:
1. Go to https://dao-dev.hypha.earth/cooldao/proposals/create
2. Start a Generic Contribution until step 2
3. Leave the platform
4. Login again and click "continue draft"

Expected behaviour:
I start again on step 2

Experienced behaviour:
I start again on page 0 in the process.

**Comment by jmgayosso** [comment]
Done
