### ISSUE TITLE
Keep HVOICE Voting Quorum

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#809]
**Summary**
As a DHO user I would like to see the "real Quorum" for old proposals even when the HVOICE of the users changes.

**Description**
When the HVOICE changes (e.g. it got reset for everyone to 5 some weeks ago), then the quorum of old assignments suddenly shows e.g. 5000%. 

**AC**

- [ ] Check with Gery for the backend integration
- [ ] Show in Frontend the correct quorum when the vote ended

Backend Story: 
https://github.com/hypha-dao/dao-contracts/issues/188

**Comment by leonieherma1** [comment]
@Gerard097 can you change the quorum for one DAO (e.g. testdao) to something different so I can test this story?

**Comment by leonieherma1** [comment]
> > @Gerard097 can you change the quorum for one DAO (e.g. testdao) to something different so I can test this story?
> 
> Sure! jonnhy?

what do you mean with johnny?

**Comment by leonieherma1** [comment]
@Gerard097 I want to test if the "accepted" or "rejected" value shows up correctly when we change the quorum (or unity). 

So e.g. for cooldao I don't know the values at the moment - but I found an example contribution that got acceptec with 71% quorum. So if we change the value to 90% this proposal should still be passed (from the time it was voted on) but with the new quorum it should not pass anymore. But it should still show "passed"

<img width="306" alt="image" src="https://user-images.githubusercontent.com/75991832/159964087-d4aa9af9-6825-483c-82ba-9812bc977b20.png">


https://dao-dev.hypha.earth/cooldao/proposals/613

**Comment by Gerard097** [comment]
> > > @Gerard097 can you change the quorum for one DAO (e.g. testdao) to something different so I can test this story?
> > 
> > 
> > Sure! jonnhy?
> 
> what do you mean with johnny?

Sorry, I meant if you were voting with jonnyhyha account

**Comment by Gerard097** [comment]
> @Gerard097 I want to test if the "accepted" or "rejected" value shows up correctly when we change the quorum (or unity).
> 
> So e.g. for cooldao I don't know the values at the moment - but I found an example contribution that got acceptec with 71% quorum. So if we change the value to 90% this proposal should still be passed (from the time it was voted on) but with the new quorum it should not pass anymore. But it should still show "passed"
> 
> <img alt="image" width="306" src="https://user-images.githubusercontent.com/75991832/159964087-d4aa9af9-6825-483c-82ba-9812bc977b20.png">
> 
> https://dao-dev.hypha.earth/cooldao/proposals/613

Ahh got it, It's very likely that it won't work since we don't store the quorum in the proposal, we just use the one in the settings of the DAO. So this needs an extra change on the backend side to store that value when the proposal is closed like we did with the VOICE supply.
