### ISSUE TITLE
Publish Document gets stucked (related to Draft)

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#819]
When I try to pubilsh a proposal it gets stuck.

<img width="704" alt="image" src="https://user-images.githubusercontent.com/75991832/158869426-b2776f98-7d02-436b-a351-66d66b8629e2.png">

**Comment by jmgayosso** [comment]
Test To do

- [ ] Create general contribution
- [ ] Role Assignment
- [ ] Bagde Assignment
- [ ] Role Archetype
- [ ] badge Type

**Comment by leonieherma1** [comment]
@jmgayosso let me know when I can test too.

**Comment by jmgayosso** [comment]
Anway I found and issue regarding min deferred and comitment in assignmet Role, I fixed that (Just add some front validations), So these fix will be on next deploy

**Comment by leonieherma1** [comment]
@jmgayosso yes sounds good, thanks
