### ISSUE TITLE
Link field in proposal creation process works with plain text

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#823]
Reproduce:
1. Go to https://dao-dev.hypha.earth/testdao/proposals/create
2. Click any document type
3. Add plain text e.g. "abcdefg" to link field
4. Click publish

Expected behaviour:
I should only be able to post a link.

Experienced behaviour:
I am able to put in plain text and then later when I click on it on the proposal detail page it doens't work.

<img width="695" alt="image" src="https://user-images.githubusercontent.com/75991832/158872370-84fb48af-84b6-4b92-89b3-ad6b8e4c6154.png">

**Comment by jmgayosso** [comment]
Done, will be on next deploy

**Comment by leonieherma1** [comment]
@jmgayosso thanks
