### ISSUE TITLE
Login Screen: Logo should take me back to /login screen

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#824]
**Summary**
As a DHO user I would like to be able to go back to the /login screen during login and registration

**AC**

- [x] Add link to the first step of the /login to the Logo 

<img width="664" alt="image" src="https://user-images.githubusercontent.com/75991832/158873146-404f00e0-e2a1-4759-b295-e8726c8c0c2f.png">

**Comment by jmgayosso** [comment]
done
