### ISSUE TITLE
Change Favicon in Browser to DAO Logo

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#826]
**Summary**
As a DHO user I would like to see the logo of my DAO in the browser tab.

**AC**
Change logo in browser (favicon) to respective DAO logo

 
<img width="283" alt="image" src="https://user-images.githubusercontent.com/75991832/158874723-71a9f460-2cc4-4413-b937-c6c3811cf550.png">

**Comment by jmgayosso** [comment]
Hi @leonieherma1 , what we should do for the moment?? I mean the daos dont have custom logo for the moment... I think we would move this to blocked

**Comment by leonieherma1** [comment]
@jmgayosso yes you can move it to blockes. Can we use a placeholder for now the new Hypha Logo
![LogoTop-Left copy](https://user-images.githubusercontent.com/75991832/158899342-5b917dc0-9675-408b-a7cc-e2f67cb91dfd.png)
?

**Comment by jmgayosso** [comment]
Sure

> @jmgayosso yes you can move it to blockes. Can we use a placeholder for now the new Hypha Logo ![LogoTop-Left copy](https://user-images.githubusercontent.com/75991832/158899342-5b917dc0-9675-408b-a7cc-e2f67cb91dfd.png) ?

Sure, It Will be on the next deploy

**Comment by leonieherma1** [comment]
@jmgayosso yes please add the hypha default icon while it is loading and check if you can make it load faster
