### ISSUE TITLE
Save draft in the last step of creation wizard

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#830]
Reproduce:
1. Create a proposal (e.g. generic contribution). 
2. Go through all the steps and click "publish"
3. Cancel the Anchor transaction signing process

Experienced behaviour:
The proposal does not show up in drafts

Expected behavior:
The draft should be autosaved when I click "publish" so if I get an error during the publishing process not all changes are lost.

**Comment by jmgayosso** [comment]
@leonieherma1 regarding this issue, I think is better show the error message and keep on the same page, what do you think???

**Comment by jmgayosso** [comment]
@leonieherma1 I Just uploaded a new version with this feature (My suggested behavior), So you can test and decide if works for you

**Comment by leonieherma1** [comment]
@jmgayosso perfect thanks

**Comment by leonieherma1** [comment]
@jmgayosso the pop up if I want to save the draft works. But when I click yes the /proposal page doesnt load anymore. Will try again tomorrow

**Comment by jmgayosso** [comment]
> @jmgayosso the pop up if I want to save the draft works. But when I click yes the /proposal page doesnt load anymore. Will try again tomorrow

Hi @leonieherma1 sorry I don't get it, what do you mean with "yes" button?

**Comment by leonieherma1** [comment]
@jmgayosso 

I made a screen video:

The problem is that the page gets stuck. Nothing is loading anymore.

Steps:
 1. Create Contribution
 2. Click Publish
 3. Cancel transaction in anchor
 4. try to navigate to /proposal or homepage doesnt work

https://user-images.githubusercontent.com/75991832/159055971-9e5dbc46-b7b0-4b44-a39a-d69bcd0e1f65.mov

**Comment by jmgayosso** [comment]
Thanks @leonieherma1 the fix now is on dev, could you test again please?
