### ISSUE TITLE
Proposal Page Bugs

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#854]
Reproduce

1. Go go https://dao-dev.hypha.earth/cooldao/proposals/create
2. Create a proposal

See the following bugs:

- [x] colours of bars (unity & quorum) not updated 
- [x] check if we can see the time of voting left in real time (countdown) - only if it is a small fix, if not just leave it (also on proposal detail page
-

**Comment by garcia-alejandro** [comment]
https://github.com/hypha-dao/dho-web-client/pull/864
