### ISSUE TITLE
Poposal Detail Page bugs

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#855]
Reproduce

1. Go go https://dao-dev.hypha.earth/cooldao/proposals/create
2. Create a proposal

See the following bugs:

- [x] quorum bar has no colour (grey for the progress and green as soon as it has reached 20%)
- [x] refresh screen after I activate my proposal (so the activate button goes away)
- [x] badge type icon is clickable in overview and also not same padding on top and the bottom

**Comment by leonieherma1** [comment]
@DaniPoot @jmgayosso when I click "publish" during the creation process, I get forwarded to the /proposal page but it is empty. So I think there is a bug:

<img width="1413" alt="image" src="https://user-images.githubusercontent.com/75991832/161606989-5f0525b1-159b-4a25-8f1e-8ce221a593ae.png">


Can we either:

1. Force a refresh of the page
2.  Or even better forward to the proposal e.g. https://dao-dev.hypha.earth/hypha/proposals/7601

**Comment by jmgayosso** [comment]
@leonieherma1 I thinks is better redirect to proposal page detail

**Comment by leonieherma1** [comment]
> @leonieherma1 I thinks is better redirect to proposal page detail, Im not sure if we can get the docId for the new proposal @Gerard097 ? Do you known?

yes to proposal detail page is good, thanks
