### ISSUE TITLE
suspension not working

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#858]
Reproduce

1. Go go https://dao-dev.hypha.earth/cooldao/proposals
2. Try to suspend a proposal

Expected behaviour: 
I should see the suspend button and when I click it it should go away

Experienced behaviour:
I don't see the button

<img width="1659" alt="image" src="https://user-images.githubusercontent.com/75991832/159779328-48f90d71-303f-46f6-a113-9d3132d15584.png">

**Comment by DaniPoot** [comment]
I checked this one. The suspend button is disabled because the state is not correct at the moment for this action. The proposal owner needs to active the proposal 
@jmgayosso

**Comment by leonieherma1** [comment]
> I checked this one. The suspend button is disabled because the state is not correct at the moment for this action. The proposal owner needs to active the proposal @jmgayosso

doesnt it get activated automatically every few hours?

**Comment by leonieherma1** [comment]
@DaniPoot @jmgayosso 

Also in this one, when I click "suspend" and then "yes" it still shows the "suspend button" but doesnt create a new proposal.

<img width="368" alt="image" src="https://user-images.githubusercontent.com/75991832/160040078-701b1ce7-69b6-4a38-b694-3d6c36d352db.png">


https://dao-dev.hypha.earth/cooldao/proposals/6442

**Comment by jmgayosso** [comment]
> 

Hi @leonieherma1 I think you need confirm this action too, I mean you have to do click on "publish" and then sign the transaction

**Comment by leonieherma1** [comment]
@DaniPoot @jmgayosso I click "Suspend" then "Publish" and nothing happens. I see this after clickin "publish":

<img width="1362" alt="image" src="https://user-images.githubusercontent.com/75991832/160248220-362348dc-3a48-4f08-92b0-b46fbd40974b.png">


https://dao-dev.hypha.earth/cooldao/proposals/6442

**Comment by leonieherma1** [comment]
@DaniPoot @jmgayosso here I don't see the suspend button at all:

https://dao-dev.hypha.earth/cooldao/proposals/613

https://dao-dev.hypha.earth/cooldao/proposals/613
