### ISSUE TITLE
Policy Change: Reduce Equity Multiple (End of Seed Round)

### ISSUE THREAD

**Issue by sceenius** [hypha-dao/dho-web-client#88]
As soon as the vote passes, change the Hypha multiplier for salary from 0.6 to 0.5. The new token salary will be computed as follows:

:::
#### Salary Computation

* **Deferred Seeds** = USD/SeedsConversion * Committed * Deferred * (1+SeedsBonus)
* **Liquid Seeds** = USD/SeedsConversion * Committed * (1-Deferred) * (1-HUSD)
* **HVOICE** = USD * Committed * 2 for Role Assignments ONLY, otherwise USD*Committed
* **HYPHA** = USD * Committed * Deferred * HyphaBonus
* **HUSD** = USD * Committed * (1-Deferred) * HUSD

with
* **Committed** = [0-100%] (input)
* **HUSD** =  [0-100%] (input)
* **SeedsConversion** = 0.011 (feed)
* **HyphaBonus** = 0.5 (fixed, per vote ID 373 changed from 0.6 to 0.5)
* **SeedsBonus** = 0.3 (fixed)
* **Lunar Phases Weekly Multiplier** = 7.4/365

#### [TRY THIS HERE](https://docs.google.com/spreadsheets/d/1xngcdfqhoqE9uCUURybUDU5pCYrI3UjY6aIgf1auD38/edit#)
:::

Per policy contribution vote:
This proposal is for a policy change to reduce the current multiplier for Hypha equity to 0.5X from 0.6X.

----

  | Key | Value
-- | -- | --
  | assets.husd_amount | "0.00 HUSD"
  | assets.hvoice_amount | "1.00 HVOICE"
  | assets.hypha_amount | "0.60 HYPHA"
  | assets.seeds_escrow_amount | "110.75 SEEDS"
  | created_date | 2020-09-14T03:23:24.000
  | id | 373
  | ints.end_period | 2020-10-23T13:23:00.000
  | ints.start_period | 2020-09-17T11:01:00.000
  | names.ballot_id | "hypha1.....sg"
  | names.owner | "thealchemist"
  | names.recipient | "thealchemist"
  | names.trx_action_contract | "dao.hypha"
  | names.trx_action_name | "makepayout"
  | names.type | "payout"
  | strings.client_version | "1.0.13 0c81dde6"
  | strings.contract_version | "a2c01393ba575ed0babdfaff344b5c965be0ee8b"
add | strings.description | "This proposal is for a policy change to reduce the current multiplier for Hypha equity to 0.5X from 0.6X.&nbsp;<div><br></div><div>This is 1 drop dow...
  | strings.title | "Policy Change: Reduce Equity Multiple (End of Seed Round)"
  | strings.url | "null"
  | updated_date | 2020-09-14T03:23:24.000

**Comment by dappdever** [comment]
Update the calculation to pull from the contract configuration setting
