### ISSUE TITLE
Login flow

### ISSUE THREAD

**Issue by n13** [hypha-dao/dho-web-client#881]
### Current Behavior

After registering my account, and going through all steps, I am back at the main DAO page 

<img width="1308" alt="image" src="https://user-images.githubusercontent.com/65412/160505107-8bb1bef7-6851-441e-9b82-a6244126e3b1.png">

### Expected Behavior

Should redirect to login page and explain how to set up Anchor

<img width="409" alt="image" src="https://user-images.githubusercontent.com/65412/160505262-f94014aa-6912-4165-85cb-285337dcbc6c.png">

Ideal solution:
The last step of the onboarding walkthrough - after "I saved my keys somewhere" - should be to download anchor.  

### How critical do you perceive the bug?

Critical

### Anything else?

An alpha quality release can get away with this but it adds friction to the process and people might accidentally create additional accounts / register again / think registry didn't work

**Comment by arsenijesavic** [comment]
@pugakn you fixed this last week ?

**Comment by pugakn** [comment]
Yes this should be fixed
