### ISSUE TITLE
After registration i should be redirected to login

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#885]
After registration i should be redirected to login

**Comment by jmgayosso** [comment]
Hi @leonieherma1 currently when you do click on "done" (When you finish you TLOS creation account) you see this login screen 
![Screen Shot 2022-03-29 at 13 16 58](https://user-images.githubusercontent.com/58195358/160690340-7649ee98-da17-4ddd-989a-a4eabadd1de3.png)
 So you hope a diferent screen?

**Comment by leonieherma1** [comment]
@jmgayosso no that is good!
