### ISSUE TITLE
Add Role Sponsor to role card

### ISSUE THREAD

**Issue by sceenius** [hypha-dao/dho-web-client#89]
Add subtitle with the name of the card owner which we take as the "Sponsor" of the role - 

"Sponsored by <name>"  in gray with smaller font so it generally fits onto 1 line.

![image](https://user-images.githubusercontent.com/24725582/93253093-63b7c680-f764-11ea-8db9-8a614b39cdc1.png)

**Comment by dappdever** [comment]
@sceenius is the sponsor the same as the creator/owner/proposer?  I assume so, and this is recorded on the object as "owner".

**Comment by sceenius** [comment]
That is what I am proposing, no need to introduce another field imho.
