### ISSUE TITLE
DHO Creation Wizard Alpha Version

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#930]
**Summary**
As the DHO Dev Team I want to use the creation wizard to create DHOs.

**AC**
Please add the following steps for the Alpha Version and hide the other screens:

Step 1: General Info:
- [x] Title: Organization Name
- [x] Placeholder Copy Field: The display name of your organization (max. 50 character)
- [x] Title: Organization Purpose
- [x] Placeholder Copy Field: Briefly explain what your DAO is all about (max. 300 characters)

Step 2: Token

- [x] Title: Name your Token
- [x] Placeholder copy field: Utility Token Name (max 7 characters, uppercase A-Z)
- [x] Remove number of digits field (default is 4)
- [x] Hide Total Amount and Value fields
- [x] Hide Voice, Treasury and Additional Token fields for now

Step 3: Launch Team
- [x] Title: Launch team
- [x] Copy: The initial launch team is critical for your DAO. The people you list here will have access to configure the DAO, create proposals and enroll other members. Make sure to provide us with the emails of the launch team - in case they do not have a Telos account yet, we can send them a link to create an account. This makes it easier for you and your team to get started from day 1. 
- [x] Fields: Name*, Email*, Telos / SEEDS Account, Discord 
- [x] * = mandatory fields
- [x] Add more / Remove Accounts

Step 4: Voting
- [x] Hide for Alpha

Step 5: Compensation
- [x] Hide for Alpha

Step 6: Templates (will probably be step 4 and if users chose a template we don't need voting and compensation. If users don't chose a template we need voting and compensation)
- [x] Hide for Alpha

Step 7: Design
- [x] Title: Design your DAO
- [x] Copy: The logo, copy and colours can be changed later in the configuration page.
- [x] Hide all fields except:
- [x] Logo (max 3MB)
- [x] Primary Colour: Colour picker
- [x] Secondary Colour: Colour picker
- [x] All other fields will probably be hidden and users can find it in the configuration page and update the headers, copy, etc... there

https://xd.adobe.com/view/7cc1de2c-4b1e-466b-8ac4-eb37f309c3bb-2992/screen/d5c95ab2-8d69-4b99-ac5c-ea2c2e0ac5b8/

**Comment by leonieherma1** [comment]
https://xd.adobe.com/view/7cc1de2c-4b1e-466b-8ac4-eb37f309c3bb-2992/screen/d5c95ab2-8d69-4b99-ac5c-ea2c2e0ac5b8/

@arsenijesavic I got the new design

**Comment by leonieherma1** [comment]
@arsenijesavic we need to think about how to validate the Token Names in the form in the Front End - every token can only be used once. So please check with @n13 and @Gerard097 how we can check if a token name has already been taken.

Also: is this sustainable to only have 5 letters? the combinations will be pretty quickly exhausted, no? @sceenius

**Comment by arsenijesavic** [comment]
@leonieherma1 What are we missing here ?

**Comment by leonieherma1** [comment]
@arsenijesavic see comment above (about token validation)
