### ISSUE TITLE
Add "x" to search filters

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#957]
**Summary**
As a DHO user I would like to be able to delete my search query with one click on a "X".

**AC**
- [x] Add "X" to all search filters in the sidebars around the DHO (members, search results, proposals, archetype list, badge list)
- [x] X should remove the whole search query (similar to global search on top)

<img width="206" alt="image" src="https://user-images.githubusercontent.com/75991832/162836540-1d6c94a0-31b1-4ba9-b272-dcd60c06d5ff.png">
https://xd.adobe.com/view/dff2df13-c8f4-480e-8a2e-2a74a54a6db5-8aa1/screen/83049a35-6039-42f4-a77d-1e1090376c7d/

**Comment by leonieherma1** [comment]
@jmgayosso @garcia-alejandro I can see the "x" in the sidebar search but not in the global search (on top).

1. Go to https://dao-dev.hypha.earth/hypha/
2. Type "test" in the search bar on top:
3. I get redirected to the search page right away but the field is empty 
4. https://dao-dev.hypha.earth/hypha/search?q=tes&filter=All
<img width="1507" alt="image" src="https://user-images.githubusercontent.com/75991832/166987267-dc993094-1e38-412b-950a-d3c83e93d4f6.png">
5. So I can't delete my search term "Test" it is stuck in the headline:
<img width="1370" alt="image" src="https://user-images.githubusercontent.com/75991832/166987349-b83ddb46-fddd-422a-8788-a704e7dcbc84.png">


Expected behaviour:
"Test" should still be visible in the field and the "x" should show up so I can delete my search


Also the sidebar search is not working:
1. Go to https://dao-dev.hypha.earth/hypha/proposals/
2. Type "test" in the sidebar filter
3. Hit enter
4. Nothing happens
<img width="1357" alt="image" src="https://user-images.githubusercontent.com/75991832/166987504-2ec2a3f2-534c-4bb8-9348-c6b2e8331e3e.png">


Please test this again and only put it in "test" when you are really sure this works

**Comment by leonieherma1** [comment]
@jmgayosso just a small thing: When I delete my "test" search word the headline looks like this:

<img width="1348" alt="image" src="https://user-images.githubusercontent.com/75991832/167713898-f473f37d-3723-4266-a889-9161515edf37.png">

<img width="1348" alt="image" src="https://user-images.githubusercontent.com/75991832/167714094-ecb0afe3-edcd-4866-bca2-23dec5de7c7a.png">

No big deal, also not sure how to handle it.

- [ ] Ideally when I click "x" on the word "test" the search results go back and just load all docuements sorted by the default (by date created ascending + active)

What do you think?

**Comment by DaniPoot** [comment]
@leonieherma1 It's necessary to have a value on the input. We don't load all documents because that is how Elastic Search works.

**Comment by jmgayosso** [comment]
> @leonieherma1 It's necessary to have a value on the input. We don't load all documents because that is how Elastic Search works.

can we replace by somthing like "*"? to load all documents??

**Comment by leonieherma1** [comment]
@jmgayosso ok then let's leave it like this for now

**Comment by jmgayosso** [comment]
@leonieherma1 Daniel talked with Sebastian and he found a solution, now this is working! could you test please?

**Comment by leonieherma1** [comment]
@jmgayosso the test results show all document types now, cool!

But the search query still shows "" - can we just show "Search Results" and remove the "for """ ? If not no big deal

<img width="1176" alt="image" src="https://user-images.githubusercontent.com/75991832/168116525-37e604ed-d3f7-4add-b6e0-02553439612e.png">
