### ISSUE TITLE
Add publish button to last step of creation wizard

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#959]
**Summary**
As a DHO user I would like to be able to publish my proposal directly

**Summary**
Right now, if I click through the proposal wizard, I always click "next", "next", "next", and then suddenly the same spot is "previous step" which is confusing

**AC**

- [ ] add "publish" button to last step of all document creation steps

**Design**
<img width="1227" alt="image" src="https://user-images.githubusercontent.com/75991832/162837556-82fca4bd-62a0-494c-8e4d-7bedcac38cdd.png">

**Comment by arsenijesavic** [comment]
@leonieherma1 I can take this one as the logic should be emulate on profile creation and dho-creation as well
