### ISSUE TITLE
Emergency banner cannot be removed

### ISSUE THREAD

**Issue by sceenius** [hypha-dao/dho-web-client#97]
When attempting to remove the banner, I get the following error msg: 

![image](https://user-images.githubusercontent.com/24725582/93676528-58251200-fa7a-11ea-9825-5d08e2011d5e.png)

**Comment by gregory-latinier** [comment]
Yes the smartcontract method has changed.
I didn't know it was published.
I'm fixing this

**Comment by sceenius** [comment]
Does this include the 1 week dismiss feature? I forgot if that's in another issue.

**Comment by gregory-latinier** [comment]
Nothing was created about that.
I can include it in the issue though

**Comment by gregory-latinier** [comment]
What is the exact hide rule that you would like to setup ?

**Comment by sceenius** [comment]
[Dismiss] will hide the panel for 7 days (can be on the device, so another device will show this again until you [dismiss])
