### ISSUE TITLE
Hide "Reason for Membership"

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#985]
**Summary**
Hide "Reason for Membership" in Frontend for non enrollers

<img width="338" alt="image" src="https://user-images.githubusercontent.com/75991832/163883016-47d8d137-b20e-45cb-901b-a27a1f98c261.png">

**Comment by arsenijesavic** [comment]
@leonieherma1 on what page is this ?

**Comment by leonieherma1** [comment]
@arsenijesavic on the /members page (only visible when you are an enroller)
